//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <Sparkle/NSSecureCoding-Protocol.h>

@class NSData, NSString;

@interface SPUDownloadData : NSObject <NSSecureCoding>
{
    NSData *_data;
    NSString *_textEncodingName;
    NSString *_MIMEType;
}

+ (BOOL)supportsSecureCoding;
@property(readonly, copy, nonatomic) NSString *MIMEType; // @synthesize MIMEType=_MIMEType;
@property(readonly, copy, nonatomic) NSString *textEncodingName; // @synthesize textEncodingName=_textEncodingName;
@property(readonly, nonatomic) NSData *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithData:(id)arg1 textEncodingName:(id)arg2 MIMEType:(id)arg3;

@end

