//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString, SPUURLRequest;

@protocol SPUDownloaderProtocol
- (void)cancel;
- (void)cleanup;
- (void)downloadDidFinish;
- (void)startTemporaryDownloadWithRequest:(SPUURLRequest *)arg1;
- (void)startPersistentDownloadWithRequest:(SPUURLRequest *)arg1 bundleIdentifier:(NSString *)arg2 desiredFilename:(NSString *)arg3;
@end

