//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <Sparkle/SPUDownloaderProtocol-Protocol.h>

@class NSString;
@protocol SPUDownloaderDelegate;

__attribute__((visibility("hidden")))
@interface SPUDownloader : NSObject <SPUDownloaderProtocol>
{
    BOOL _disabledAutomaticTermination;
    BOOL _receivedExpectedBytes;
    id <SPUDownloaderDelegate> _delegate;
    NSString *_bundleIdentifier;
    NSString *_desiredFilename;
    NSString *_downloadFilename;
    unsigned long long _mode;
}

@property(nonatomic) BOOL receivedExpectedBytes; // @synthesize receivedExpectedBytes=_receivedExpectedBytes;
@property(nonatomic) unsigned long long mode; // @synthesize mode=_mode;
@property(nonatomic) BOOL disabledAutomaticTermination; // @synthesize disabledAutomaticTermination=_disabledAutomaticTermination;
@property(copy, nonatomic) NSString *downloadFilename; // @synthesize downloadFilename=_downloadFilename;
@property(copy, nonatomic) NSString *desiredFilename; // @synthesize desiredFilename=_desiredFilename;
@property(copy, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(retain, nonatomic) id <SPUDownloaderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)getAndCleanTempDirectory;
- (void)downloadDidFinishWithData:(id)arg1;
- (void)downloadDidFinish;
- (void)cancel;
- (void)cleanup;
- (void)enableAutomaticTermination;
- (void)startTemporaryDownloadWithRequest:(id)arg1;
- (void)startPersistentDownloadWithRequest:(id)arg1 bundleIdentifier:(id)arg2 desiredFilename:(id)arg3;
- (id)initWithDelegate:(id)arg1;

@end

