//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Sparkle/SPUDownloader.h>

#import <Sparkle/NSURLDownloadDelegate-Protocol.h>
#import <Sparkle/SPUDownloaderProtocol-Protocol.h>

@class NSString, NSURLDownload, NSURLResponse;

__attribute__((visibility("hidden")))
@interface SPUDownloaderDeprecated : SPUDownloader <NSURLDownloadDelegate, SPUDownloaderProtocol>
{
    NSURLDownload *_download;
    NSURLResponse *_response;
}

@property(retain, nonatomic) NSURLResponse *response; // @synthesize response=_response;
@property(retain, nonatomic) NSURLDownload *download; // @synthesize download=_download;
- (void).cxx_destruct;
- (void)cancel;
- (void)cleanup;
- (void)downloadDidFinish;
- (BOOL)download:(id)arg1 shouldDecodeSourceDataOfMIMEType:(id)arg2;
- (void)download:(id)arg1 didFailWithError:(id)arg2;
- (void)downloadDidFinish:(id)arg1;
- (void)download:(id)arg1 didReceiveDataOfLength:(unsigned long long)arg2;
- (void)download:(id)arg1 didReceiveResponse:(id)arg2;
- (void)download:(id)arg1 didCreateDestination:(id)arg2;
- (void)download:(id)arg1 decideDestinationWithSuggestedFilename:(id)arg2;
- (void)startTemporaryDownloadWithRequest:(id)arg1;
- (void)startPersistentDownloadWithRequest:(id)arg1 bundleIdentifier:(id)arg2 desiredFilename:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

