//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Sparkle/NSObject-Protocol.h>

@class NSError, NSString, SPUDownloadData;

@protocol SPUDownloaderDelegate <NSObject>
- (void)downloaderDidFailWithError:(NSError *)arg1;
- (void)downloaderDidFinishWithTemporaryDownloadData:(SPUDownloadData *)arg1;
- (void)downloaderDidReceiveDataOfLength:(unsigned long long)arg1;
- (void)downloaderDidReceiveExpectedContentLength:(long long)arg1;
- (void)downloaderDidSetDestinationName:(NSString *)arg1 temporaryDirectory:(NSString *)arg2;
@end

