//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString, NSURL, SUSignatures;

@interface SUAppcastItem : NSObject
{
    NSString *dateString;
    NSDictionary *deltaUpdates;
    NSString *displayVersionString;
    SUSignatures *signatures;
    NSURL *fileURL;
    unsigned long long _contentLength;
    NSURL *infoURL;
    NSString *itemDescription;
    NSString *maximumSystemVersion;
    NSString *minimumSystemVersion;
    NSURL *releaseNotesURL;
    NSString *title;
    NSString *versionString;
    NSString *osString;
    NSDictionary *propertiesDictionary;
}

@property(copy) NSDictionary *propertiesDictionary; // @synthesize propertiesDictionary;
@property(copy) NSString *osString; // @synthesize osString;
@property(copy) NSString *versionString; // @synthesize versionString;
@property(copy) NSString *title; // @synthesize title;
@property(retain) NSURL *releaseNotesURL; // @synthesize releaseNotesURL;
@property(copy) NSString *minimumSystemVersion; // @synthesize minimumSystemVersion;
@property(copy) NSString *maximumSystemVersion; // @synthesize maximumSystemVersion;
@property(copy) NSString *itemDescription; // @synthesize itemDescription;
@property(retain) NSURL *infoURL; // @synthesize infoURL;
@property(readonly, nonatomic) unsigned long long contentLength; // @synthesize contentLength=_contentLength;
@property(retain) NSURL *fileURL; // @synthesize fileURL;
@property(retain) SUSignatures *signatures; // @synthesize signatures;
@property(copy) NSString *displayVersionString; // @synthesize displayVersionString;
@property(copy) NSDictionary *deltaUpdates; // @synthesize deltaUpdates;
@property(copy) NSString *dateString; // @synthesize dateString;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1 failureReason:(id *)arg2;
- (id)initWithDictionary:(id)arg1;
@property(readonly, getter=isInformationOnlyUpdate) BOOL informationOnlyUpdate;
@property(readonly, getter=isMacOsUpdate) BOOL macOsUpdate;
@property(readonly, getter=isCriticalUpdate) BOOL criticalUpdate;
@property(readonly, getter=isDeltaUpdate) BOOL deltaUpdate;

@end

