//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Sparkle/SUBasicUpdateDriver.h>

@class NSTimer, SUAutomaticUpdateAlert;

__attribute__((visibility("hidden")))
@interface SUAutomaticUpdateDriver : SUBasicUpdateDriver
{
    BOOL postponingInstallation;
    BOOL willUpdateOnTermination;
    BOOL isTerminating;
    SUAutomaticUpdateAlert *alert;
    NSTimer *showUpdateAlertTimer;
}

@property(retain) NSTimer *showUpdateAlertTimer; // @synthesize showUpdateAlertTimer;
@property(retain) SUAutomaticUpdateAlert *alert; // @synthesize alert;
@property BOOL isTerminating; // @synthesize isTerminating;
@property BOOL willUpdateOnTermination; // @synthesize willUpdateOnTermination;
@property BOOL postponingInstallation; // @synthesize postponingInstallation;
- (void).cxx_destruct;
- (void)terminateApp;
- (void)applicationWillTerminate:(id)arg1;
- (void)systemWillPowerOff:(id)arg1;
- (void)installWithToolAndRelaunch:(BOOL)arg1 displayingUserInterface:(BOOL)arg2;
- (void)automaticUpdateAlertFinishedWithChoice:(long long)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)abortUpdate;
- (void)dealloc;
- (void)invalidateShowUpdateAlertTimer;
- (void)stopUpdatingOnTermination;
- (BOOL)downloadsUpdatesInBackground;
- (BOOL)resumeUpdateInteractively;
- (void)unarchiverDidFinish:(id)arg1;
- (void)showUpdateAlert;

@end

