//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SUCodeSigningVerifier : NSObject
{
}

+ (BOOL)bundleAtURLIsCodeSigned:(id)arg1;
+ (void)logSigningInfoForCode:(struct __SecCode *)arg1 label:(id)arg2;
+ (id)codeSignatureInfoForCode:(struct __SecCode *)arg1;
+ (id)codeSignatureInfoAtBundleURL:(id)arg1;
+ (BOOL)codeSignatureIsValidAtBundleURL:(id)arg1 error:(id *)arg2;
+ (BOOL)codeSignatureAtBundleURL:(id)arg1 matchesSignatureAtBundleURL:(id)arg2 error:(id *)arg3;

@end

