//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSFileManager, NSString;

__attribute__((visibility("hidden")))
@interface SUFileManager : NSObject
{
    struct AuthorizationOpaqueRef *_auth;
    NSFileManager *_fileManager;
    NSString *_authorizationToolPath;
}

+ (id)fileManagerWithAuthorizationToolPath:(id)arg1;
+ (id)defaultManager;
- (void).cxx_destruct;
- (BOOL)executePackageAtURL:(id)arg1 progressBlock:(CDUnknownBlockType)arg2 error:(id *)arg3;
- (BOOL)moveItemAtURLToTrash:(id)arg1 error:(id *)arg2;
- (BOOL)removeItemAtURL:(id)arg1 error:(id *)arg2;
- (id)makeTemporaryDirectoryWithPreferredName:(id)arg1 appropriateForDirectoryURL:(id)arg2 error:(id *)arg3;
- (BOOL)makeDirectoryAtURL:(id)arg1 error:(id *)arg2;
- (BOOL)updateModificationAndAccessTimeOfItemAtURL:(id)arg1 error:(id *)arg2;
- (BOOL)changeOwnerAndGroupOfItemAtRootURL:(id)arg1 toMatchURL:(id)arg2 error:(id *)arg3;
- (BOOL)_changeOwnerAndGroupOfItemAtURL:(id)arg1 ownerID:(id)arg2 groupID:(id)arg3 needsAuth:(char *)arg4 error:(id *)arg5;
- (BOOL)moveItemAtURL:(id)arg1 toURL:(id)arg2 error:(id *)arg3;
- (BOOL)_getVolumeID:(short *)arg1 ofItemAtURL:(id)arg2;
- (BOOL)copyItemAtURL:(id)arg1 toURL:(id)arg2 error:(id *)arg3;
- (BOOL)releaseItemFromQuarantineAtRootURL:(id)arg1 error:(id *)arg2;
- (BOOL)_releaseItemFromQuarantineAtRootURL:(id)arg1 withQuarantineRetrieval:(CDUnknownBlockType)arg2 quarantineRemoval:(CDUnknownBlockType)arg3 isAccessError:(CDUnknownBlockType)arg4 error:(id *)arg5;
- (BOOL)_removeQuarantineWithAuthenticationAtRootURL:(id)arg1 error:(id *)arg2;
- (int)_removeXAttr:(const char *)arg1 fromFile:(id)arg2 options:(int)arg3;
- (long long)_getXAttr:(const char *)arg1 fromFile:(id)arg2 options:(int)arg3;
- (BOOL)_itemExistsAtURL:(id)arg1 isDirectory:(char *)arg2;
- (BOOL)_itemExistsAtURL:(id)arg1;
- (void)dealloc;
- (void)parseLines:(id)arg1 lineCallback:(CDUnknownBlockType)arg2;
- (BOOL)_authorizeAndExecuteCommand:(char *)arg1 sourcePath:(char *)arg2 destinationPath:(char *)arg3 lineCallback:(CDUnknownBlockType)arg4 error:(id *)arg5;
- (BOOL)_authorizeAndExecuteCommand:(char *)arg1 sourcePath:(char *)arg2 destinationPath:(char *)arg3 error:(id *)arg4;
- (BOOL)_acquireAuthorizationWithError:(id *)arg1;
- (id)fileManagerByPreservingAuthorizationRights;
- (id)initWithAuthorizationToolPath:(id)arg1;

@end

