//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface SUOperatingSystem : NSObject
{
}

+ (id)systemVersionString;
+ (BOOL)isOperatingSystemAtLeastVersion:(CDStruct_2ec95fd7)arg1;
+ (CDStruct_2ec95fd7)operatingSystemVersion;

@end

