//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface SUPublicKeys : NSObject
{
    unsigned char ed25519_public_key[32];
    NSString *_dsaPubKey;
}

@property(readonly) NSString *dsaPubKey; // @synthesize dsaPubKey=_dsaPubKey;
- (void).cxx_destruct;
@property(readonly, nonatomic) const char *ed25519PubKey;
- (BOOL)isEqualToKey:(id)arg1;
- (id)initWithDsa:(id)arg1 ed:(id)arg2;

@end

