//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData;

__attribute__((visibility("hidden")))
@interface SUSignatures : NSObject
{
    unsigned char ed25519_signature[64];
    NSData *_dsaSignature;
}

@property(readonly) NSData *dsaSignature; // @synthesize dsaSignature=_dsaSignature;
- (void).cxx_destruct;
@property(readonly, nonatomic) const char *ed25519Signature;
- (id)initWithDsa:(id)arg1 ed:(id)arg2;

@end

