//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Sparkle/SUBasicUpdateDriver.h>

@class SUStatusController, SUUpdateAlert;

__attribute__((visibility("hidden")))
@interface SUUIBasedUpdateDriver : SUBasicUpdateDriver
{
    BOOL showErrors;
    SUStatusController *statusController;
    SUUpdateAlert *updateAlert;
}

@property BOOL showErrors; // @synthesize showErrors;
@property(retain) SUUpdateAlert *updateAlert; // @synthesize updateAlert;
@property(retain) SUStatusController *statusController; // @synthesize statusController;
- (void).cxx_destruct;
- (void)showAlert:(id)arg1;
- (void)abortUpdate;
- (void)abortUpdateWithError:(id)arg1;
- (void)terminateApp;
- (void)installWithToolAndRelaunch:(BOOL)arg1;
- (void)installAndRestart:(id)arg1;
- (void)unarchiverDidFinish:(id)arg1;
- (void)unarchiver:(id)arg1 extractedProgress:(double)arg2;
- (void)extractUpdate;
- (void)cancelDownload:(id)arg1;
- (void)downloaderDidReceiveDataOfLength:(unsigned long long)arg1;
- (id)localizedStringFromByteCount:(long long)arg1;
- (void)downloaderDidReceiveExpectedContentLength:(long long)arg1;
- (void)downloadUpdate;
- (void)updateAlertFinishedWithChoice:(long long)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)didNotFindUpdate;
- (BOOL)shouldDisableKeyboardShortcutForInstallButton;
- (void)didFindValidUpdate;
- (id)initWithUpdater:(id)arg1;

@end

