//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface SUUnarchiverNotifier : NSObject
{
    CDUnknownBlockType _completionBlock;
    CDUnknownBlockType _progressBlock;
}

@property(readonly, copy, nonatomic) CDUnknownBlockType progressBlock; // @synthesize progressBlock=_progressBlock;
@property(readonly, copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
- (void).cxx_destruct;
- (void)notifyProgress:(double)arg1;
- (void)notifyFailureWithError:(id)arg1;
- (void)notifySuccess;
- (id)initWithCompletionBlock:(CDUnknownBlockType)arg1 progressBlock:(CDUnknownBlockType)arg2;

@end

