//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURL, SUHost;
@protocol SUUpdaterPrivate;

__attribute__((visibility("hidden")))
@interface SUUpdateDriver : NSObject
{
    BOOL interruptible;
    BOOL finished;
    BOOL automaticallyInstallUpdates;
    id <SUUpdaterPrivate> updater;
    SUHost *host;
    NSURL *appcastURL;
}

@property BOOL automaticallyInstallUpdates; // @synthesize automaticallyInstallUpdates;
@property(copy) NSURL *appcastURL; // @synthesize appcastURL;
@property(readonly) BOOL finished; // @synthesize finished;
@property(getter=isInterruptible) BOOL interruptible; // @synthesize interruptible;
@property(retain) SUHost *host; // @synthesize host;
@property __weak id <SUUpdaterPrivate> updater; // @synthesize updater;
- (void).cxx_destruct;
- (void)showAlert:(id)arg1;
@property(readonly) BOOL downloadsUpdatesInBackground;
@property(readonly) BOOL downloadsAppcastInBackground;
- (BOOL)resumeUpdateInteractively;
- (void)abortUpdate;
- (void)checkForUpdatesAtURL:(id)arg1 host:(id)arg2;
- (id)description;
- (id)initWithUpdater:(id)arg1;

@end

