//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <Sparkle/SUUpdaterPrivate-Protocol.h>

@class NSBundle, NSDate, NSDictionary, NSString, NSTimer, NSURL, SUHost, SUUpdateDriver;
@protocol SUUpdaterDelegate;

@interface SUUpdater : NSObject <SUUpdaterPrivate>
{
    id <SUUpdaterDelegate> delegate;
    NSTimer *checkTimer;
    NSString *customUserAgentString;
    NSDictionary *httpHeaders;
    SUUpdateDriver *driver;
    SUHost *host;
    NSBundle *sparkleBundle;
    NSString *decryptionPassword;
    NSDate *updateLastCheckedDate;
}

+ (id)updaterForBundle:(id)arg1;
+ (id)sharedUpdater;
@property(copy) NSDate *updateLastCheckedDate; // @synthesize updateLastCheckedDate;
@property(copy, nonatomic) NSString *decryptionPassword; // @synthesize decryptionPassword;
@property(retain) NSBundle *sparkleBundle; // @synthesize sparkleBundle;
@property(retain) SUHost *host; // @synthesize host;
@property(retain) SUUpdateDriver *driver; // @synthesize driver;
@property(copy) NSDictionary *httpHeaders; // @synthesize httpHeaders;
@property(copy, nonatomic) NSString *userAgentString; // @synthesize userAgentString=customUserAgentString;
@property(retain) NSTimer *checkTimer; // @synthesize checkTimer;
@property id <SUUpdaterDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
@property(readonly) NSBundle *hostBundle;
@property(readonly) BOOL updateInProgress;
- (BOOL)validateMenuItem:(id)arg1;
- (void)dealloc;
@property double updateCheckInterval;
@property(readonly, copy) NSURL *parameterizedFeedURL;
@property BOOL sendsSystemProfile;
@property(copy) NSURL *feedURL;
@property BOOL automaticallyDownloadsUpdates;
@property BOOL automaticallyChecksForUpdates;
- (void)resetUpdateCycle;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)unregisterAsObserver;
- (void)registerAsObserver;
- (void)checkForUpdatesWithDriver:(id)arg1;
- (void)installUpdatesIfAvailable;
- (void)checkForUpdateInformation;
- (void)checkForUpdates:(id)arg1;
- (void)checkForUpdatesInBackground;
- (void)scheduleNextUpdateCheck;
- (void)updateLastUpdateCheckDate;
@property(readonly, copy) NSDate *lastUpdateCheckDate;
- (void)updateDriverDidFinish:(id)arg1;
- (void)updatePermissionRequestFinishedWithResponse:(id)arg1;
- (void)startUpdateCycle;
@property(readonly, copy) NSString *description;
- (id)init;
- (void)checkIfConfiguredProperly;
- (void)showAlertText:(id)arg1 informativeText:(id)arg2;
- (id)initForBundle:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

