//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Sparkle/NSObject-Protocol.h>

@class NSBundle, NSDictionary, NSString;
@protocol SUUpdaterDelegate;

@protocol SUUpdaterPrivate <NSObject>
@property(readonly) NSBundle *sparkleBundle;
@property(copy, nonatomic) NSString *decryptionPassword;
@property(copy) NSDictionary *httpHeaders;
@property(copy, nonatomic) NSString *userAgentString;
@property id <SUUpdaterDelegate> delegate;
@end

