//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Sparkle/SUUIBasedUpdateDriver.h>

@class SUStatusController;

__attribute__((visibility("hidden")))
@interface SUUserInitiatedUpdateDriver : SUUIBasedUpdateDriver
{
    BOOL canceled;
    SUStatusController *checkingController;
}

@property(getter=isCanceled) BOOL canceled; // @synthesize canceled;
@property(retain) SUStatusController *checkingController; // @synthesize checkingController;
- (void).cxx_destruct;
- (BOOL)itemContainsValidUpdate:(id)arg1;
- (BOOL)downloadsAppcastInBackground;
- (void)abortUpdate;
- (void)abortUpdateWithError:(id)arg1;
- (void)appcastDidFinishLoading:(id)arg1;
- (void)checkForUpdatesAtURL:(id)arg1 host:(id)arg2;
- (void)cancelCheckForUpdates:(id)arg1;
- (void)closeCheckingWindow;

@end

