//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;

@protocol SUVersionComparison
- (long long)compareVersion:(NSString *)arg1 toVersion:(NSString *)arg2;
@end

