//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface COCacheBox : NSObject
{
    struct OpaqueJSContext *_context;
    const struct OpaqueJSValue *_jsValueRef;
}

@property(readonly) const struct OpaqueJSValue *jsValueRef; // @synthesize jsValueRef=_jsValueRef;
- (void)cleanup;
- (id)initWithJSValueRef:(struct OpaqueJSValue *)arg1 inContext:(struct OpaqueJSContext *)arg2;

@end

