//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSAlert, NSMutableArray;

@interface COSAlertWindow : NSObject
{
    NSAlert *_alert;
    NSMutableArray *_views;
}

@property(retain) NSMutableArray *views; // @synthesize views=_views;
@property(retain) NSAlert *alert; // @synthesize alert=_alert;
- (void).cxx_destruct;
- (id)accessoryView;
- (void)setAccessoryView:(id)arg1;
- (BOOL)showsSuppressionButton;
- (void)setShowsSuppressionButton:(BOOL)arg1;
- (id)buttons;
- (id)addButtonWithTitle:(id)arg1;
- (id)icon;
- (void)setIcon:(id)arg1;
- (id)informativeText;
- (id)messageText;
- (void)setInformativeText:(id)arg1;
- (void)setMessageText:(id)arg1;
- (long long)runModal;
- (void)layout;
- (id)viewAtIndex:(unsigned long long)arg1;
- (void)addTextFieldWithValue:(id)arg1;
- (void)addTextLabelWithValue:(id)arg1;
- (void)addAccessoryView:(id)arg1;
- (id)init;

@end

