//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class Mocha, NSDictionary, NSMutableArray, NSMutableDictionary, NSString;
@protocol COPrintController;

@interface COScript : NSObject
{
    Mocha *_mochaRuntime;
    NSMutableArray *_activeFibers;
    int _nextFiberId;
    NSMutableDictionary *moduleCache;
    BOOL _shouldPreprocess;
    BOOL _shouldKeepAround;
    id <COPrintController> _printController;
    NSMutableDictionary *_env;
    NSString *_processedSource;
    NSDictionary *_coreModuleMap;
}

+ (id)proxyForApp:(id)arg1;
+ (id)app:(id)arg1;
+ (id)application:(id)arg1;
+ (id)applicationOnPort:(id)arg1;
+ (id)currentCOScript;
+ (id)currentCOSThreadStack;
+ (void)loadBridgeSupportFileAtURL:(id)arg1;
+ (void)loadPlugins;
+ (void)resetPlugins;
+ (void)loadExtraAtPath:(id)arg1;
+ (void)resetCache;
+ (void)setShouldLoadJSTPlugins:(BOOL)arg1;
+ (void)setShouldLoadExtras:(BOOL)arg1;
+ (void)listen;
+ (id)setFlowDelegate:(id)arg1;
+ (void)cosLogCIContextDrawImageInRectFromRect;
+ (void)cosShowSpelunker:(id)arg1;
+ (BOOL)insertInMainMenu;
@property(retain, nonatomic) NSDictionary *coreModuleMap; // @synthesize coreModuleMap=_coreModuleMap;
@property(retain) NSString *processedSource; // @synthesize processedSource=_processedSource;
@property BOOL shouldKeepAround; // @synthesize shouldKeepAround=_shouldKeepAround;
@property BOOL shouldPreprocess; // @synthesize shouldPreprocess=_shouldPreprocess;
@property(retain) NSMutableDictionary *env; // @synthesize env=_env;
@property __weak id <COPrintController> printController; // @synthesize printController=_printController;
- (void).cxx_destruct;
- (void)print:(id)arg1;
- (void)printException:(id)arg1;
- (void)include:(id)arg1;
- (void)protect:(id)arg1;
- (void)unprotect:(id)arg1;
- (id)callJSFunction:(struct OpaqueJSValue *)arg1 withArgumentsInArray:(id)arg2;
- (id)callFunctionNamed:(id)arg1 withArguments:(id)arg2;
- (BOOL)hasFunctionNamed:(id)arg1;
- (id)executeString:(id)arg1 baseURL:(id)arg2;
- (struct OpaqueJSValue *)executeStringAndReturnJSValue:(id)arg1 baseURL:(id)arg2;
- (struct OpaqueJSValue *)executeStringAndReturnJSValue:(id)arg1;
- (id)executeString:(id)arg1;
- (struct OpaqueJSValue *)executeModuleAtURL:(id)arg1;
- (struct OpaqueJSValue *)require:(id)arg1;
- (id)resolveModule:(id)arg1 currentURL:(id)arg2 isRequiringCoreModule:(char *)arg3;
- (void)deleteObjectWithName:(id)arg1;
- (void)pushJSValue:(struct OpaqueJSValue *)arg1 withName:(id)arg2;
- (void)pushObject:(id)arg1 withName:(id)arg2;
- (void)popAsCurrentCOScript;
- (void)pushAsCurrentCOScript;
- (void)addExtrasToRuntime;
- (struct OpaqueJSContext *)context;
- (BOOL)shouldKeepRunning;
- (void)garbageCollect;
- (void)fiberWasCleared;
- (void)cleanup;
- (void)dealloc;
- (id)initWithCoreModules:(id)arg1 andName:(id)arg2;
- (id)init;
- (id)createFiber;
- (void)removeFiber:(id)arg1;
- (void)cleanupFibers;
- (void)addFiber:(id)arg1;
- (void)system:(id)arg1;
- (void)sleep:(double)arg1;
- (void)keyCode:(id)arg1;
- (void)keyCode:(id)arg1 using:(id)arg2;
- (void)keystroke:(id)arg1;
- (void)keystroke:(id)arg1 using:(id)arg2;
- (void)modifiers:(id)arg1 down:(BOOL)arg2;
- (void)exit:(int)arg1;
- (id)scheduleWithInterval:(double)arg1 jsFunction:(id)arg2;
- (id)scheduleWithRepeatingInterval:(double)arg1 jsFunction:(id)arg2;

@end

