//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class COScript, MOJavaScriptObject;

@interface COSFiber : NSObject
{
    COScript *_coscript;
    MOJavaScriptObject *_cleanUpJSfunc;
}

+ (id)createWithCocoaScript:(id)arg1;
@property(retain) MOJavaScriptObject *cleanUpJSfunc; // @synthesize cleanUpJSfunc=_cleanUpJSfunc;
@property __weak COScript *coscript; // @synthesize coscript=_coscript;
- (void).cxx_destruct;
- (void)cleanup;
- (void)onCleanup:(id)arg1;

@end

