//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class COScript;

@interface COSGifAnimator : NSObject
{
    COScript *_jstalk;
    double _fps;
    double _seconds;
    struct CGSize _size;
}

@property struct CGSize size; // @synthesize size=_size;
@property double seconds; // @synthesize seconds=_seconds;
@property double fps; // @synthesize fps=_fps;
- (void).cxx_destruct;
- (void)drawInBlock:(id)arg1;
- (void)mouseDown:(id)arg1;

@end

