//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface COSImageTools : NSObject
{
}

+ (void)setDisplayTransferUsingRed:(double)arg1 green:(double)arg2 blue:(double)arg3;
+ (void)setMainDisplayTransferUsingRed:(double)arg1 green:(double)arg2 blue:(double)arg3;
+ (id)pathOfImageNamed:(id)arg1;
+ (void)setShouldUseCICPURenderer:(BOOL)arg1;
+ (void)setShouldUseCISofwareRenderer:(BOOL)arg1;
+ (void)viewCIImage:(id)arg1;
+ (void)viewCIImage:(id)arg1 inWindowNamed:(id)arg2 extent:(struct CGRect)arg3;
+ (void)dumpPixelsInBuffer:(id)arg1;
+ (void)viewNSImage:(id)arg1 inWindowNamed:(id)arg2;
+ (void)viewImageBuffer:(id)arg1 inWindowNamed:(id)arg2;
+ (id)getImageViewWindowNamed:(id)arg1 defaultSize:(struct CGSize)arg2;
+ (id)tiffDataFromImageBuffer:(id)arg1;
+ (struct CGImage *)createImageRefFromBuffer:(id)arg1;

@end

