//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CocoaScript/COSFiber.h>

@class MOJavaScriptObject, NSTimer;

@interface COSInterval : COSFiber
{
    MOJavaScriptObject *_jsfunc;
    NSTimer *_timer;
    BOOL _onshot;
}

+ (id)scheduleWithInterval:(double)arg1 cocoaScript:(id)arg2 jsFunction:(id)arg3 repeat:(BOOL)arg4;
@property(retain) MOJavaScriptObject *jsfunc; // @synthesize jsfunc=_jsfunc;
- (void).cxx_destruct;
- (void)timerHit:(id)arg1;
- (void)cancel;
- (void)cleanup;

@end

