//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface COSMarkdown : NSObject
{
}

+ (id)convertStringToMarkdown:(id)arg1 usingFlags:(unsigned long long)arg2;
+ (id)convertStringToMarkdown:(id)arg1;

@end

