//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class COSOpenCLContext, NSMutableDictionary, NSString;

@interface COSOpenCLProgram : NSObject
{
    COSOpenCLContext *context;
    NSString *sourceCode;
    struct _cl_program *computeProgram;
    NSMutableDictionary *computeKernels;
}

@property(copy) NSString *sourceCode; // @synthesize sourceCode;
@property(readonly) COSOpenCLContext *context; // @synthesize context;
- (void).cxx_destruct;
- (id)kernelWithName:(id)arg1;
- (id)createKernel:(id)arg1;
- (void)build;
- (void)dealloc;
- (id)initWithContext:(id)arg1;

@end

