//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CocoaScript/JSTOpenCLBuffer.h>

@interface COSOpenCLImageBuffer : JSTOpenCLBuffer
{
    unsigned long long _width;
    unsigned long long _height;
    unsigned long long _bytesPerRow;
    CDUnion_bc1bcd03 *_bitmapData;
}

+ (id)instanceWithContext:(id)arg1 usingImageAtPath:(id)arg2;
+ (id)instanceWithContext:(id)arg1 width:(unsigned long long)arg2 height:(unsigned long long)arg3;
@property(readonly) unsigned long long bytesPerRow; // @synthesize bytesPerRow=_bytesPerRow;
@property(readonly) CDUnion_bc1bcd03 *bitmapData; // @synthesize bitmapData=_bitmapData;
@property(readonly) unsigned long long height; // @synthesize height=_height;
@property(readonly) unsigned long long width; // @synthesize width=_width;
- (void)dealloc;
- (id)initWithContext:(id)arg1 usingImageAtPath:(id)arg2;
- (id)initWithContext:(id)arg1 width:(unsigned long long)arg2 height:(unsigned long long)arg3;

@end

