//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <QuartzCore/CIFilter.h>

@class CIFilterShape, CIKernel, MOJavaScriptObject, NSMutableArray;

@interface COSQuickCIFilter : CIFilter
{
    CIKernel *_theKernel;
    NSMutableArray *_kernelArgs;
    CIFilterShape *_applyDefinitionShape;
    MOJavaScriptObject *_roiMethod;
    MOJavaScriptObject *_outputImageMethod;
}

+ (id)quickFilterWithKernel:(id)arg1;
@property(retain) MOJavaScriptObject *outputImageMethod; // @synthesize outputImageMethod=_outputImageMethod;
@property(retain) MOJavaScriptObject *roiMethod; // @synthesize roiMethod=_roiMethod;
@property(retain) NSMutableArray *kernelArgs; // @synthesize kernelArgs=_kernelArgs;
@property(retain) CIKernel *theKernel; // @synthesize theKernel=_theKernel;
@property(retain) CIFilterShape *applyDefinitionShape; // @synthesize applyDefinitionShape=_applyDefinitionShape;
- (void).cxx_destruct;
- (id)outputImage;
- (id)applyWithArguments:(id)arg1 options:(id)arg2;
- (struct CGRect)xxregionOf:(int)arg1 destRect:(struct CGRect)arg2 userInfo:(id)arg3;
- (void)addKernelArgument:(id)arg1;
- (struct CGRect)regionOf:(int)arg1 destRect:(struct CGRect)arg2 userInfo:(id)arg3;

@end

