//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface JSTPSymbolGroup : NSObject
{
    unsigned short _openSymbol;
    NSMutableArray *_args;
    JSTPSymbolGroup *_parent;
}

@property(retain) JSTPSymbolGroup *parent; // @synthesize parent=_parent;
@property(retain) NSMutableArray *args; // @synthesize args=_args;
- (void).cxx_destruct;
- (id)description;
- (int)nonWhitespaceCountInArray:(id)arg1;
- (void)addSymbol:(id)arg1;
- (void)dealloc;
- (id)init;

@end

