//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@class CIImage;

@interface JSTSimpleCIView : NSView
{
    CIImage *_theImage;
}

@property(retain) CIImage *theImage; // @synthesize theImage=_theImage;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;

@end

