//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MOBoxManager;

@interface MOBoxManagerBoxContext : NSObject
{
    MOBoxManager *_manager;
    id _object;
}

@property(retain, nonatomic) id object; // @synthesize object=_object;
@property(retain, nonatomic) MOBoxManager *manager; // @synthesize manager=_manager;
- (void).cxx_destruct;
- (void)finishMakingBoxForObject:(struct OpaqueJSValue *)arg1;
- (id)initWithManager:(id)arg1 object:(id)arg2;

@end

