//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSString;

@interface MOBridgeSupportArgument : NSObject
{
    NSMutableArray *_arguments;
    BOOL _cArrayOfFixedLength;
    BOOL _cArrayDelimitedByNull;
    BOOL _cArrayOfVariableLength;
    BOOL _cArrayLengthInReturnValue;
    BOOL _acceptsNull;
    BOOL _acceptsPrintfFormat;
    BOOL _alreadyRetained;
    BOOL _functionPointer;
    NSString *_type;
    NSString *_type64;
    NSString *_typeModifier;
    NSString *_signature;
    NSString *_signature64;
    NSString *_cArrayLengthInArg;
    unsigned long long _index;
    MOBridgeSupportArgument *_returnValue;
}

@property(retain) MOBridgeSupportArgument *returnValue; // @synthesize returnValue=_returnValue;
@property(getter=isFunctionPointer) BOOL functionPointer; // @synthesize functionPointer=_functionPointer;
@property(getter=isAlreadyRetained) BOOL alreadyRetained; // @synthesize alreadyRetained=_alreadyRetained;
@property BOOL acceptsPrintfFormat; // @synthesize acceptsPrintfFormat=_acceptsPrintfFormat;
@property BOOL acceptsNull; // @synthesize acceptsNull=_acceptsNull;
@property unsigned long long index; // @synthesize index=_index;
@property(getter=isCArrayLengthInReturnValue) BOOL cArrayLengthInReturnValue; // @synthesize cArrayLengthInReturnValue=_cArrayLengthInReturnValue;
@property(getter=isCArrayOfVariableLength) BOOL cArrayOfVariableLength; // @synthesize cArrayOfVariableLength=_cArrayOfVariableLength;
@property(getter=isCArrayDelimitedByNull) BOOL cArrayDelimitedByNull; // @synthesize cArrayDelimitedByNull=_cArrayDelimitedByNull;
@property(getter=isCArrayOfFixedLength) BOOL cArrayOfFixedLength; // @synthesize cArrayOfFixedLength=_cArrayOfFixedLength;
@property(copy) NSString *cArrayLengthInArg; // @synthesize cArrayLengthInArg=_cArrayLengthInArg;
@property(copy) NSString *signature64; // @synthesize signature64=_signature64;
@property(copy) NSString *signature; // @synthesize signature=_signature;
@property(copy) NSString *typeModifier; // @synthesize typeModifier=_typeModifier;
@property(copy) NSString *type64; // @synthesize type64=_type64;
@property(copy) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)removeArgument:(id)arg1;
- (void)addArgument:(id)arg1;
@property(copy) NSArray *arguments;
- (id)description;
- (id)init;

@end

