//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <CocoaScript/NSXMLParserDelegate-Protocol.h>

@class MOBridgeSupportLibrary, NSMutableArray, NSString, NSXMLParser;

@interface MOBridgeSupportParser : NSObject <NSXMLParserDelegate>
{
    NSXMLParser *_parser;
    MOBridgeSupportLibrary *_library;
    NSMutableArray *_symbolStack;
}

- (void).cxx_destruct;
- (void)parser:(id)arg1 didEndElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4;
- (void)parser:(id)arg1 didStartElement:(id)arg2 namespaceURI:(id)arg3 qualifiedName:(id)arg4 attributes:(id)arg5;
- (void)parserDidEndDocument:(id)arg1;
- (void)parserDidStartDocument:(id)arg1;
- (id)libraryWithBridgeSupportURL:(id)arg1 error:(id *)arg2;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

