//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CocoaScript/MOBridgeSupportSymbol.h>

@class NSString;

@interface MOBridgeSupportStringConstant : MOBridgeSupportSymbol
{
    BOOL _hasNSString;
    NSString *_value;
}

@property BOOL hasNSString; // @synthesize hasNSString=_hasNSString;
@property(copy) NSString *value; // @synthesize value=_value;
- (void).cxx_destruct;

@end

