//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CocoaScript/MOBridgeSupportSymbol.h>

@class MOBridgeSupportArgument, NSArray, NSMutableArray, NSNumber, NSString;

@interface MOBridgeSupportMethod : MOBridgeSupportSymbol
{
    NSMutableArray *_arguments;
    BOOL _classMethod;
    BOOL _variadic;
    BOOL _ignored;
    SEL _selector;
    NSString *_type;
    NSString *_type64;
    MOBridgeSupportArgument *_returnValue;
    NSNumber *_sentinel;
    NSString *_suggestion;
}

@property(copy) NSString *suggestion; // @synthesize suggestion=_suggestion;
@property(getter=isIgnored) BOOL ignored; // @synthesize ignored=_ignored;
@property(copy) NSNumber *sentinel; // @synthesize sentinel=_sentinel;
@property(getter=isVariadic) BOOL variadic; // @synthesize variadic=_variadic;
@property(getter=isClassMethod) BOOL classMethod; // @synthesize classMethod=_classMethod;
@property(retain) MOBridgeSupportArgument *returnValue; // @synthesize returnValue=_returnValue;
@property(copy) NSString *type64; // @synthesize type64=_type64;
@property(copy) NSString *type; // @synthesize type=_type;
@property SEL selector; // @synthesize selector=_selector;
- (void).cxx_destruct;
- (void)removeArgument:(id)arg1;
- (void)addArgument:(id)arg1;
@property(copy) NSArray *arguments;
- (id)init;

@end

