//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CocoaScript/MOBridgeSupportSymbol.h>

@class NSNumber, NSString;

@interface MOBridgeSupportEnum : MOBridgeSupportSymbol
{
    BOOL _ignored;
    NSNumber *_value;
    NSNumber *_value64;
    NSString *_suggestion;
}

@property(copy) NSString *suggestion; // @synthesize suggestion=_suggestion;
@property(getter=isIgnored) BOOL ignored; // @synthesize ignored=_ignored;
@property(copy) NSNumber *value64; // @synthesize value64=_value64;
@property(copy) NSNumber *value; // @synthesize value=_value;
- (void).cxx_destruct;

@end

