//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MOBridgeSupportParser, NSDictionary, NSMutableArray, NSMutableDictionary;

@interface MOBridgeSupportController : NSObject
{
    NSMutableArray *_loadedURLs;
    NSMutableArray *_loadedLibraries;
    NSMutableDictionary *_symbols;
    MOBridgeSupportParser *_parser;
}

+ (id)sharedController;
- (void).cxx_destruct;
- (id)performQueryForSymbolName:(id)arg1 ofType:(Class)arg2;
- (id)performQueryForSymbolName:(id)arg1;
- (id)performQueryForSymbolsOfType:(id)arg1;
@property(readonly, copy) NSDictionary *symbols;
- (BOOL)loadBridgeSupportAtURL:(id)arg1 error:(id *)arg2;
- (BOOL)isBridgeSupportLoadedForURL:(id)arg1;
- (void)reset;
- (id)init;

@end

