//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CocoaScript/MOBridgeSupportSymbol.h>

@class NSString;

@interface MOBridgeSupportCFType : MOBridgeSupportSymbol
{
    NSString *_type;
    NSString *_type64;
    NSString *_tollFreeBridgedClassName;
    NSString *_getTypeIDFunctionName;
}

@property(copy) NSString *getTypeIDFunctionName; // @synthesize getTypeIDFunctionName=_getTypeIDFunctionName;
@property(copy) NSString *tollFreeBridgedClassName; // @synthesize tollFreeBridgedClassName=_tollFreeBridgedClassName;
@property(copy) NSString *type64; // @synthesize type64=_type64;
@property(copy) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;

@end

