//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, NSURL;

@interface MOBridgeSupportLibrary : NSObject
{
    NSMutableArray *_dependencies;
    NSMutableDictionary *_symbols;
    NSString *_name;
    NSURL *_URL;
}

@property(copy) NSURL *URL; // @synthesize URL=_URL;
@property(copy) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (void)removeSymbolForName:(id)arg1;
- (void)setSymbol:(id)arg1 forName:(id)arg2;
- (id)symbolWithName:(id)arg1;
@property(copy) NSDictionary *symbols;
- (void)removeDependency:(id)arg1;
- (void)addDependency:(id)arg1;
@property(copy) NSArray *dependencies;
- (id)init;

@end

