//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MOClosure : NSObject
{
    id _block;
}

+ (id)closureWithBlock:(id)arg1;
@property(readonly, copy) id block; // @synthesize block=_block;
- (void).cxx_destruct;
@property(readonly) const char *typeEncoding;
@property(readonly) void *callAddress;
- (id)initWithBlock:(id)arg1;

@end

