//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MOInstanceVariableDescription : NSObject
{
    NSString *_name;
    NSString *_typeEncoding;
}

+ (id)instanceVariableWithName:(id)arg1 typeEncoding:(id)arg2;
@property(copy) NSString *typeEncoding; // @synthesize typeEncoding=_typeEncoding;
@property(copy) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)description;
- (id)initWithName:(id)arg1 typeEncoding:(id)arg2;

@end

