//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <CocoaScript/NSCopying-Protocol.h>

@class MOJavaScriptObject, NSMethodSignature;

@interface MOJSBlock : NSObject <NSCopying>
{
    int _flags;
    int _reserved;
    CDUnknownFunctionPointerType _invoke;
    struct BlockDescriptor *_descriptor;
    MOJavaScriptObject *_function;
    NSMethodSignature *_signature;
}

+ (id)blockWithSignature:(id)arg1 function:(id)arg2;
@property(readonly, nonatomic) NSMethodSignature *signature; // @synthesize signature=_signature;
@property(readonly, nonatomic) MOJavaScriptObject *function; // @synthesize function=_function;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithSignature:(const char *)arg1 function:(id)arg2;

@end

