//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MOMethodDescription : NSObject
{
    SEL _selector;
    NSString *_typeEncoding;
}

+ (id)methodWithSelector:(SEL)arg1 typeEncoding:(id)arg2;
@property(copy) NSString *typeEncoding; // @synthesize typeEncoding=_typeEncoding;
@property SEL selector; // @synthesize selector=_selector;
- (void).cxx_destruct;
- (id)description;
- (id)initWithSelector:(SEL)arg1 typeEncoding:(id)arg2;

@end

