//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MOMethod : NSObject
{
    id _target;
    SEL _selector;
    id _block;
}

+ (id)methodWithBlock:(id)arg1;
+ (id)methodWithTarget:(id)arg1 selector:(SEL)arg2;
@property(copy) id block; // @synthesize block=_block;
@property SEL selector; // @synthesize selector=_selector;
@property(retain) id target; // @synthesize target=_target;
- (void).cxx_destruct;
- (id)description;

@end

