//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface MOObjCRuntime : NSObject
{
}

+ (id)sharedRuntime;
@property(readonly, copy) NSArray *protocols;
@property(readonly, copy) NSArray *classes;
- (id)init;

@end

