//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString, Protocol;

@interface MOProtocolDescription : NSObject
{
    Protocol *_protocol;
}

+ (id)allocateDescriptionForProtocolWithName:(id)arg1;
+ (id)descriptionForProtocol:(id)arg1;
+ (id)descriptionForProtocolWithName:(id)arg1;
- (void).cxx_destruct;
- (void)addProtocol:(id)arg1;
@property(readonly, copy) NSArray *protocols;
- (void)addProperty:(id)arg1 required:(BOOL)arg2;
@property(readonly, copy) NSArray *properties;
- (void)addInstanceMethod:(id)arg1 required:(BOOL)arg2;
@property(readonly, copy) NSArray *optionalInstanceMethods;
@property(readonly, copy) NSArray *requiredInstanceMethods;
- (void)addClassMethod:(id)arg1 required:(BOOL)arg2;
@property(readonly, copy) NSArray *optionalClassMethods;
@property(readonly, copy) NSArray *requiredClassMethods;
@property(readonly, copy) NSString *name;
@property(readonly) Protocol *protocol;
- (id)description;
- (id)initWithProtocol:(id)arg1;

@end

