//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MOPropertyDescription : NSObject
{
    BOOL _dynamic;
    BOOL _nonAtomic;
    BOOL _readOnly;
    BOOL _weak;
    NSString *_name;
    NSString *_typeEncoding;
    NSString *_ivarName;
    SEL _getterSelector;
    SEL _setterSelector;
    unsigned long long _ownershipRule;
}

@property(getter=isWeak) BOOL weak; // @synthesize weak=_weak;
@property(getter=isReadOnly) BOOL readOnly; // @synthesize readOnly=_readOnly;
@property(getter=isNonAtomic) BOOL nonAtomic; // @synthesize nonAtomic=_nonAtomic;
@property(getter=isDynamic) BOOL dynamic; // @synthesize dynamic=_dynamic;
@property unsigned long long ownershipRule; // @synthesize ownershipRule=_ownershipRule;
@property SEL setterSelector; // @synthesize setterSelector=_setterSelector;
@property SEL getterSelector; // @synthesize getterSelector=_getterSelector;
@property(copy) NSString *ivarName; // @synthesize ivarName=_ivarName;
@property(copy) NSString *typeEncoding; // @synthesize typeEncoding=_typeEncoding;
@property(copy) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)description;

@end

