//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSRulerView.h>

@class NSColor, NSFont, NSMutableArray, NSMutableDictionary;

@interface NoodleLineNumberView : NSRulerView
{
    NSMutableArray *lineIndices;
    NSMutableDictionary *linesToMarkers;
    NSFont *font;
    NSColor *textColor;
    NSColor *alternateTextColor;
    NSColor *backgroundColor;
}

- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)removeMarker:(id)arg1;
- (void)addMarker:(id)arg1;
- (void)setMarkers:(id)arg1;
- (void)drawHashMarksAndLabelsInRect:(struct CGRect)arg1;
- (double)requiredThickness;
- (id)markerTextAttributes;
- (id)textAttributes;
- (unsigned long long)lineNumberForCharacterIndex:(unsigned long long)arg1 inText:(id)arg2;
- (void)calculateLines;
- (id)markerAtLine:(unsigned long long)arg1;
- (long long)lineNumberForLocation:(double)arg1;
- (void)textDidChange:(id)arg1;
- (void)invalidateLineIndices;
- (id)lineIndices;
- (void)setClientView:(id)arg1;
- (id)backgroundColor;
- (void)setBackgroundColor:(id)arg1;
- (id)alternateTextColor;
- (void)setAlternateTextColor:(id)arg1;
- (id)textColor;
- (void)setTextColor:(id)arg1;
- (id)font;
- (void)setFont:(id)arg1;
- (void)dealloc;
- (void)awakeFromNib;
- (id)initWithScrollView:(id)arg1;

@end

