//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSApplication.h>

@interface NSApplication (COSExtras)
+ (void)JSTAXSetSelectedTextRangeAttributeOnFocusedElement:(struct _NSRange)arg1;
+ (void)JSTAXSetSelectedTextAttributeOnFocusedElement:(id)arg1;
+ (id)JSTAXStuff;
- (id)standardUserDefaults;
- (id)sharedDocumentController;
- (long long)displayDialog:(id)arg1;
- (long long)displayDialog:(id)arg1 withTitle:(id)arg2;
- (void)activate;
- (id)open:(id)arg1;
@end

