//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSMutableOrderedSet.h>

@interface NSMutableOrderedSet (MochaAdditions)
- (void)mo_setObject:(id)arg1 forIndexedSubscript:(unsigned long long)arg2;
@end

