//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSObject (COSTargetAdditions)
+ (SEL)selectorForMochaPropertyName:(id)arg1;
+ (BOOL)isSelectorExcludedFromMochaScript:(SEL)arg1;
+ (id)mo_mocha;
+ (void)mo_swizzleAdditions;
- (void)setCOSJSTargetFunction:(id)arg1;
- (void)finalizeForMochaScript;
- (Class)ojbcClass;
@end

