//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <CocoaScript/NSCopying-Protocol.h>

@class NSMutableArray, NSString;

@interface TDAssembly : NSObject <NSCopying>
{
    NSMutableArray *stack;
    id target;
    unsigned long long index;
    NSString *string;
    NSString *defaultDelimiter;
}

+ (id)assemblyWithString:(id)arg1;
@property(retain, nonatomic) NSString *defaultDelimiter; // @synthesize defaultDelimiter;
@property(retain, nonatomic) NSString *string; // @synthesize string;
@property(nonatomic) unsigned long long index; // @synthesize index;
@property(retain, nonatomic) id target; // @synthesize target;
@property(retain, nonatomic) NSMutableArray *stack; // @synthesize stack;
- (id)description;
- (id)objectsAbove:(id)arg1;
- (BOOL)isStackEmpty;
- (void)push:(id)arg1;
- (id)pop;
- (id)peek;
@property(readonly, nonatomic) unsigned long long objectsRemaining;
@property(readonly, nonatomic) unsigned long long objectsConsumed;
@property(readonly, nonatomic) unsigned long long length;
- (id)remainingObjectsJoinedByString:(id)arg1;
- (id)consumedObjectsJoinedByString:(id)arg1;
- (BOOL)hasMore;
- (id)next;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)_init;
- (id)initWithString:(id)arg1;
- (id)init;

@end

