//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CocoaScript/TDTokenizerState.h>

@class TDMultiLineCommentState, TDSingleLineCommentState, TDSymbolRootNode;

@interface TDCommentState : TDTokenizerState
{
    TDSymbolRootNode *rootNode;
    TDSingleLineCommentState *singleLineState;
    TDMultiLineCommentState *multiLineState;
    BOOL reportsCommentTokens;
    BOOL balancesEOFTerminatedComments;
}

@property(nonatomic) BOOL balancesEOFTerminatedComments; // @synthesize balancesEOFTerminatedComments;
@property(nonatomic) BOOL reportsCommentTokens; // @synthesize reportsCommentTokens;
@property(retain, nonatomic) TDMultiLineCommentState *multiLineState; // @synthesize multiLineState;
@property(retain, nonatomic) TDSingleLineCommentState *singleLineState; // @synthesize singleLineState;
@property(retain, nonatomic) TDSymbolRootNode *rootNode; // @synthesize rootNode;
- (id)nextTokenFromReader:(id)arg1 startingWith:(long long)arg2 tokenizer:(id)arg3;
- (void)removeMultiLineStartSymbol:(id)arg1;
- (void)addMultiLineStartSymbol:(id)arg1 endSymbol:(id)arg2;
- (void)removeSingleLineStartSymbol:(id)arg1;
- (void)addSingleLineStartSymbol:(id)arg1;
- (void)dealloc;
- (id)init;

@end

