//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CocoaScript/TDTokenizerState.h>

@class NSMutableArray, NSString;

@interface TDMultiLineCommentState : TDTokenizerState
{
    NSMutableArray *startSymbols;
    NSMutableArray *endSymbols;
    NSString *currentStartSymbol;
}

@property(copy, nonatomic) NSString *currentStartSymbol; // @synthesize currentStartSymbol;
@property(retain, nonatomic) NSMutableArray *endSymbols; // @synthesize endSymbols;
@property(retain, nonatomic) NSMutableArray *startSymbols; // @synthesize startSymbols;
- (id)nextTokenFromReader:(id)arg1 startingWith:(long long)arg2 tokenizer:(id)arg3;
- (void)unreadSymbol:(id)arg1 fromReader:(id)arg2;
- (void)removeStartSymbol:(id)arg1;
- (void)addStartSymbol:(id)arg1 endSymbol:(id)arg2;
- (void)dealloc;
- (id)init;

@end

