//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CocoaScript/TDTokenizerState.h>

@interface TDQuoteState : TDTokenizerState
{
    BOOL balancesEOFTerminatedQuotes;
}

@property(nonatomic) BOOL balancesEOFTerminatedQuotes; // @synthesize balancesEOFTerminatedQuotes;
- (id)nextTokenFromReader:(id)arg1 startingWith:(long long)arg2 tokenizer:(id)arg3;
- (void)dealloc;

@end

