//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CocoaScript/TDParser.h>

@interface TDRepetition : TDParser
{
    TDParser *subparser;
    id preassembler;
    SEL preassemblerSelector;
}

+ (id)repetitionWithSubparser:(id)arg1;
@property(nonatomic) SEL preassemblerSelector; // @synthesize preassemblerSelector;
@property(retain, nonatomic) id preassembler; // @synthesize preassembler;
@property(retain, nonatomic) TDParser *subparser; // @synthesize subparser;
- (id)allMatchesFor:(id)arg1;
- (void)setPreassembler:(id)arg1 selector:(SEL)arg2;
- (void)dealloc;
- (id)initWithSubparser:(id)arg1;
- (id)init;

@end

