//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CocoaScript/TDTokenizerState.h>

@class NSMutableArray, TDSymbolRootNode;

@interface TDSymbolState : TDTokenizerState
{
    TDSymbolRootNode *rootNode;
    NSMutableArray *addedSymbols;
}

@property(retain, nonatomic) NSMutableArray *addedSymbols; // @synthesize addedSymbols;
@property(retain, nonatomic) TDSymbolRootNode *rootNode; // @synthesize rootNode;
- (void)remove:(id)arg1;
- (void)add:(id)arg1;
- (id)nextTokenFromReader:(id)arg1 startingWith:(long long)arg2 tokenizer:(id)arg3;
- (void)dealloc;
- (id)init;

@end

