//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSString;

@interface TDSymbolNode : NSObject
{
    NSString *ancestry;
    TDSymbolNode *parent;
    NSMutableDictionary *children;
    long long character;
    NSString *string;
}

@property(retain, nonatomic) NSMutableDictionary *children; // @synthesize children;
@property(retain, nonatomic) NSString *string; // @synthesize string;
@property(nonatomic) long long character; // @synthesize character;
@property(nonatomic) TDSymbolNode *parent; // @synthesize parent;
@property(retain, nonatomic) NSString *ancestry; // @synthesize ancestry;
- (id)description;
- (void)determineAncestry;
- (void)dealloc;
- (id)initWithParent:(id)arg1 character:(long long)arg2;

@end

