//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CocoaScript/TDTerminal.h>

@class TDToken;

@interface TDSymbol : TDTerminal
{
    TDToken *symbol;
}

+ (id)symbolWithString:(id)arg1;
+ (id)symbol;
@property(retain, nonatomic) TDToken *symbol; // @synthesize symbol;
- (id)description;
- (BOOL)qualifies:(id)arg1;
- (void)dealloc;
- (id)initWithString:(id)arg1;

@end

