//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CocoaScript/TDParser.h>

@class NSString;

@interface TDTerminal : TDParser
{
    NSString *string;
    BOOL discardFlag;
}

@property(copy, nonatomic) NSString *string; // @synthesize string;
- (id)discard;
- (BOOL)qualifies:(id)arg1;
- (id)matchOneAssembly:(id)arg1;
- (id)allMatchesFor:(id)arg1;
- (void)dealloc;
- (id)initWithString:(id)arg1;
- (id)init;

@end

