//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CocoaScript/TDAssembly.h>

#import <CocoaScript/NSCopying-Protocol.h>

@class NSArray, TDTokenizer;

@interface TDTokenAssembly : TDAssembly <NSCopying>
{
    TDTokenizer *tokenizer;
    NSArray *tokens;
    BOOL preservesWhitespaceTokens;
}

+ (id)assemblyWithTokenArray:(id)arg1;
+ (id)assemblyWithTokenizer:(id)arg1;
@property(nonatomic) BOOL preservesWhitespaceTokens; // @synthesize preservesWhitespaceTokens;
@property(copy, nonatomic) NSArray *tokens; // @synthesize tokens;
@property(retain, nonatomic) TDTokenizer *tokenizer; // @synthesize tokenizer;
- (id)objectsFrom:(long long)arg1 to:(long long)arg2 separatedBy:(id)arg3;
- (void)tokenize;
- (id)remainingObjectsJoinedByString:(id)arg1;
- (id)consumedObjectsJoinedByString:(id)arg1;
- (unsigned long long)objectsRemaining;
- (unsigned long long)objectsConsumed;
- (unsigned long long)length;
- (BOOL)hasMore;
- (id)next;
- (id)peek;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithString:(id)arg1 tokenzier:(id)arg2 tokenArray:(id)arg3;
- (id)initWithString:(id)arg1;
- (id)initWithTokenArray:(id)arg1;
- (id)initWithTokenzier:(id)arg1;

@end

