//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CocoaScript/TDToken.h>

@interface TDTokenEOF : TDToken
{
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)instance;
- (id)debugDescription;
- (id)description;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

