//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <CocoaScript/TDSequence.h>

@interface TDTrack : TDSequence
{
}

+ (id)track;
- (void)throwTrackExceptionWithPreviousState:(id)arg1 parser:(id)arg2;
- (id)allMatchesFor:(id)arg1;

@end

