//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SketchPluginManager/CODebugControllerDelegate-Protocol.h>

@interface MSPluginDebugController : NSObject <CODebugControllerDelegate>
{
}

- (void)output:(id)arg1 args:(struct __va_list_tag [1])arg2;

@end

