//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MSImageData, NSFileWrapper, NSImage, NSString;

@interface MSPluginBundleIconInfo : NSObject
{
    NSString *_path;
    MSImageData *_imageWrapper;
}

@property(retain, nonatomic) MSImageData *imageWrapper; // @synthesize imageWrapper=_imageWrapper;
@property(retain, nonatomic) NSString *path; // @synthesize path=_path;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSFileWrapper *fileWrapper;
@property(readonly, nonatomic) NSImage *image;
- (id)initWithImage:(id)arg1;
- (id)initWithPath:(id)arg1 imageData:(id)arg2;

@end

