//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC10Assistants9RunResult : NSObject
{
    MISSING_TYPE *code;
    MISSING_TYPE *violations;
    MISSING_TYPE *errors;
    MISSING_TYPE *metadata;
}

- (void).cxx_destruct;

@end

