//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC10Assistants14PlainRuleError : _TtCs12_SwiftObject
{
    MISSING_TYPE *assistantName;
    MISSING_TYPE *message;
    MISSING_TYPE *stack;
    MISSING_TYPE *ruleName;
}

@end

