//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <Assistants/NSSecureCoding-Protocol.h>

@class MISSING_TYPE, NSArray;

@interface _TtC10Assistants20AssistantsRunResults : NSObject <NSSecureCoding>
{
    MISSING_TYPE *$__lazy_storage_$_violationCount;
    MISSING_TYPE *$__lazy_storage_$_maxViolationSeverity;
    MISSING_TYPE *results;
    MISSING_TYPE *$__lazy_storage_$_violations;
    MISSING_TYPE *$__lazy_storage_$_ruleErrors;
}

+ (void)setSupportsSecureCoding:(BOOL)arg1;
+ (BOOL)supportsSecureCoding;
- (void).cxx_destruct;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(nonatomic, copy) NSArray *violations;

@end

