//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface MSAssistantsConfiguration : NSObject
{
    MISSING_TYPE *dependencies;
    MISSING_TYPE *dependencyMetadata;
}

+ (id)fromDataWithData:(id)arg1 error:(id *)arg2;
- (void).cxx_destruct;
- (id)getDataAndReturnError:(id *)arg1;
- (id)init;

@end

