//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, MSImmutableDocumentData, MSImmutableLayer, NSArray, NSIndexPath;

@interface _TtC11SketchModel24MSImmutableLayerAncestry : NSObject
{
    MISSING_TYPE *layer;
    MISSING_TYPE *ancestors;
    MISSING_TYPE *document;
    MISSING_TYPE *$__lazy_storage_$_indexPath;
    MISSING_TYPE *$__lazy_storage_$_absoluteRect;
}

- (void).cxx_destruct;
- (id)init;
- (id)ancestryToPage;
@property(nonatomic) struct CGRect absoluteRect;
@property(nonatomic, copy) NSIndexPath *indexPath;
- (id)ancestorsAndSelf;
- (id)artboard;
- (id)parentGroup;
- (id)page;
- (id)initWithLayer:(id)arg1 ancestors:(id)arg2 document:(id)arg3;
- (id)initWithPage:(id)arg1 document:(id)arg2;
- (id)initWithMutableLayer:(id)arg1;
@property(nonatomic, readonly) MSImmutableDocumentData *document; // @synthesize document;
@property(nonatomic, readonly) NSArray *ancestors;
@property(nonatomic, readonly) MSImmutableLayer *layer; // @synthesize layer;

@end

