//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class MSTreeDiff, _TtC11SketchModel16MSEditingContext;

@protocol _TtP11SketchModel26MSEditingContextSubscriber_
- (void)editingContext:(_TtC11SketchModel16MSEditingContext *)arg1 didChange:(MSTreeDiff *)arg2;
@end

