//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/NSObject-Protocol.h>

@class NSData, NSString;

@protocol _TtP8Chocolat27MSEmbeddedFontRepresentable_ <NSObject>
@property(readonly, copy, nonatomic) NSString *fontFileName;
@property(readonly, copy, nonatomic) NSData *fontFileData;
@property(readonly, copy, nonatomic) NSString *fontFamilyName;
@end

