//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/NSObject-Protocol.h>

@class BCJSONDecoder, BCJSONEncoder, NSObject;

@protocol BCJSONEncoding <NSObject>
- (id)initWithJSONDecoder:(BCJSONDecoder *)arg1;
- (void)encodeAsJSON:(BCJSONEncoder *)arg1;

@optional
- (NSObject *)replacementObjectForJSONEncoder:(BCJSONEncoder *)arg1;
@end

