//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class FMDatabaseQueue, NSMutableDictionary, NSURL;

@interface BCStructuredFile : NSObject
{
    NSURL *_url;
    NSMutableDictionary *_cachedMetadata;
    FMDatabaseQueue *_db;
}

+ (id)errorWithCode:(unsigned long long)arg1;
@property(retain, nonatomic) FMDatabaseQueue *db; // @synthesize db=_db;
@property(retain, nonatomic) NSMutableDictionary *cachedMetadata; // @synthesize cachedMetadata=_cachedMetadata;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
- (void).cxx_destruct;
- (BOOL)checkDatabaseIsOpen:(id *)arg1;
- (BOOL)readMetaData:(id *)arg1;
- (BOOL)close:(id *)arg1;
- (id)dataWithKey:(id)arg1 error:(id *)arg2;
- (id)metaDataWithKey:(id)arg1;
- (id)metadata;
- (BOOL)openForReadingWithError:(id *)arg1;
- (id)initWithURL:(id)arg1 error:(id *)arg2;
- (id)init;

@end

