//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface MSArtboardPresetsCategory : NSObject
{
    NSString *_name;
    NSArray *_sections;
}

+ (id)categoriesWithContentsOfURL:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *sections; // @synthesize sections=_sections;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)initWithDictionaryRepresentation:(id)arg1;
- (id)initWithName:(id)arg1 sections:(id)arg2;

@end

