//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSString;

@interface MSArtboardPresetsSection : NSObject
{
    NSString *_name;
    NSArray *_presets;
}

+ (BOOL)writeSections:(id)arg1 toURL:(id)arg2 error:(id *)arg3;
+ (id)sectionsWithContentsOfURL:(id)arg1;
@property(copy, nonatomic) NSArray *presets; // @synthesize presets=_presets;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)description;
@property(readonly, nonatomic) NSDictionary *dictionaryRepresentation;
- (id)initWithDictionaryRepresentation:(id)arg1;
- (id)init;
- (id)initWithName:(id)arg1 presets:(id)arg2;

@end

