//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/_MSAssetContainer.h>

@protocol MSAsset;

@interface MSAssetContainer : _MSAssetContainer
{
}

@property(retain, nonatomic) id <MSAsset> asset;
- (id)initWithAsset:(id)arg1 name:(id)arg2;

@end

