//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, MSBatchedSymbolMasters, NSArray, NSString;

@interface MSBatchedOverrides : NSObject
{
    MISSING_TYPE *batchedMasters;
    MISSING_TYPE *overrides;
    MISSING_TYPE *affectedLayerName;
    MISSING_TYPE *enabled;
    MISSING_TYPE *_canOverride;
}

- (void).cxx_destruct;
- (id)init;
- (BOOL)setPropertiesForOverride:(id)arg1 atIndex:(long long)arg2;
- (id)initWithBatchedMasters:(id)arg1 overrides:(id)arg2;
@property(nonatomic, readonly) BOOL affectsSingleOverride;
@property(nonatomic) long long canOverrideDescendants;
@property(nonatomic) long long canOverride;
@property(nonatomic) BOOL enabled; // @synthesize enabled;
@property(nonatomic, copy) NSString *affectedLayerName;
@property(nonatomic, readonly) NSArray *overrides;
@property(nonatomic, readonly) MSBatchedSymbolMasters *batchedMasters; // @synthesize batchedMasters;
@property(nonatomic, readonly) NSArray *masters;

@end

