//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/_MSBaseGrid.h>

@interface MSBaseGrid : _MSBaseGrid
{
    BOOL _forceDraw;
}

@property(nonatomic) BOOL forceDraw; // @synthesize forceDraw=_forceDraw;

@end

