//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSBezierJoin.h>

@interface MSBezierLineLineJoin : MSBezierJoin
{
}

+ (id)segmentsByJoiningSegment1:(id)arg1 segment2:(id)arg2 strategy:(unsigned long long)arg3;
+ (id)joinWithSegment1:(id)arg1 segment2:(id)arg2 strategy:(unsigned long long)arg3;

@end

