//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSManifestMaker.h>

@class NSSet, NSString;
@protocol MSCloudManifestMakerDelegate;

@interface MSCloudManifestMaker : MSManifestMaker
{
    id <MSCloudManifestMakerDelegate> _delegate;
    NSSet *_objectsToExport;
    NSString *_organizationID;
}

@property(retain, nonatomic) NSString *organizationID; // @synthesize organizationID=_organizationID;
@property(retain, nonatomic) NSSet *objectsToExport; // @synthesize objectsToExport=_objectsToExport;
@property(retain, nonatomic) id <MSCloudManifestMakerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)filesMetadataForAncestry:(id)arg1 id:(id)arg2;
- (BOOL)shouldExportLayerGroup:(id)arg1 onPage:(id)arg2;
- (BOOL)validate;
- (BOOL)validateObjectID:(id)arg1;
- (id)createManifest;

@end

