//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/_MSColorAsset.h>

@class NSString;

@interface MSColorAsset : _MSColorAsset
{
}

@property(readonly, nonatomic) NSString *displayName;
- (void)setAsset:(id)arg1;
- (id)asset;

@end

