//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MSColorArchivingFactory : NSObject
{
}

+ (id)colorForEncodingColor:(id)arg1;
+ (void)initialize;

@end

