//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SketchModel/BCTreeComparisonDelegate-Protocol.h>

@class MSImmutableDocumentData, NSArray;

@interface MSCollaborationDiff : NSObject <BCTreeComparisonDelegate>
{
    NSArray *_changes;
    MSImmutableDocumentData *_oldDoc;
    MSImmutableDocumentData *_currentDoc;
}

+ (id)changesBetweenOldDocument:(id)arg1 currentDocument:(id)arg2;
@property(retain, nonatomic) MSImmutableDocumentData *currentDoc; // @synthesize currentDoc=_currentDoc;
@property(retain, nonatomic) MSImmutableDocumentData *oldDoc; // @synthesize oldDoc=_oldDoc;
@property(retain, nonatomic) NSArray *changes; // @synthesize changes=_changes;
- (void).cxx_destruct;
- (id)treeComparison:(id)arg1 propertiesOfObject:(id)arg2 notMatching:(id)arg3;
- (BOOL)treeComparison:(id)arg1 isObject:(id)arg2 theSameObjectAs:(id)arg3;
- (void)treeComparison:(id)arg1 compareChildrenOf:(id)arg2 against:(id)arg3;
- (id)initWithOldDocument:(id)arg1 currentDocument:(id)arg2;

@end

