//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MSCurvePointBehaviour : NSObject
{
}

+ (void)curveToChangedInPoint:(id)arg1;
+ (void)curveFromChangedInPoint:(id)arg1;
+ (void)didAssignBehaviorToHandle:(long long)arg1 ofPoint:(id)arg2 previousMode:(long long)arg3;

@end

