//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSDefaultArchive.h>

@interface MSDefaultStyle : MSDefaultArchive
{
}

+ (void)saveStyleAndPatterns;
+ (void)loadStyleAndPatterns;
+ (void)setDefaultStyle:(id)arg1;
+ (id)defaultStyle;
+ (void)resetCachedStyleForTesting;
- (id)newObject;
- (Class)defaultClass;
- (id)oldDefaultsName;
- (id)filename;

@end

