//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MSSubtreeRoot;

@interface MSDiff : NSObject
{
    MSSubtreeRoot *_firstObjectRoot;
    MSSubtreeRoot *_secondObjectRoot;
}

@property(retain, nonatomic) MSSubtreeRoot *secondObjectRoot; // @synthesize secondObjectRoot=_secondObjectRoot;
@property(retain, nonatomic) MSSubtreeRoot *firstObjectRoot; // @synthesize firstObjectRoot=_firstObjectRoot;
- (void).cxx_destruct;
- (id)description;
- (struct CGRect)contentDirtyDiffRectForPage:(id)arg1;
- (id)init;
- (id)initWithFirstObjectRoot:(id)arg1 secondObjectRoot:(id)arg2;

@end

