//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSDocumentChangeIntervalNotifier.h>

@interface MSDocumentChangeInstantNotifier : MSDocumentChangeIntervalNotifier
{
}

- (void)processDocumentUpdate:(id)arg1;
- (id)initWithUpdateFrequency:(unsigned long long)arg1;

@end

