//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SketchModel/NSMenuDelegate-Protocol.h>

@class MISSING_TYPE;

@interface MSFeatureFlagsDebugMenu : NSObject <NSMenuDelegate>
{
    MISSING_TYPE *menuItems;
}

+ (void)setShared:(id)arg1;
+ (id)shared;
- (void).cxx_destruct;
- (id)init;
- (void)resetAll;
- (void)menuNeedsUpdate:(id)arg1;
- (void)insertFeaturesMenuAtTag:(long long)arg1;

@end

