//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSATSTypesetter.h>

@protocol MSFirstLineTypesetterDelegate;

@interface MSFirstLineHeightTypesetter : NSATSTypesetter
{
    double _forcedBaselineOffset;
    id <MSFirstLineTypesetterDelegate> _delegate;
}

@property(nonatomic) __weak id <MSFirstLineTypesetterDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) double forcedBaselineOffset; // @synthesize forcedBaselineOffset=_forcedBaselineOffset;
- (void).cxx_destruct;
- (void)willSetLineFragmentRect:(struct CGRect *)arg1 forGlyphRange:(struct _NSRange)arg2 usedRect:(struct CGRect *)arg3 baselineOffset:(double *)arg4;

@end

