//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/_MSFlowConnection.h>

@class MSArtboardGroup, MSLayer;

@interface MSFlowConnection : _MSFlowConnection
{
    BOOL _disableDestination;
}

+ (long long)defaultAnimationType;
+ (id)flowConnectionBack;
+ (id)flowConnectionTo:(id)arg1 ofType:(long long)arg2;
@property(nonatomic) BOOL disableDestination; // @synthesize disableDestination=_disableDestination;
@property(readonly, nonatomic) BOOL isValidFlowConnection;
@property(readonly, nonatomic) __weak MSArtboardGroup *destinationArtboard;
@property(readonly, nonatomic) __weak MSLayer *sendingLayer;
@property(nonatomic) BOOL isBackAction;

@end

