//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class MSImmutableDocumentData, MSImmutableFlowConnection;

@protocol MSFlowContainmentCheck
- (BOOL)containsFlowWithSymbolsFromDocument:(MSImmutableDocumentData *)arg1;
- (MSImmutableFlowConnection *)firstFlowWithSymbolsFromDocument:(MSImmutableDocumentData *)arg1;
@end

