//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/_MSForeignLayerStyle.h>

@interface MSForeignLayerStyle : _MSForeignLayerStyle
{
}

+ (id)foreignObjectCollectionInDocument:(id)arg1;
+ (unsigned long long)containerType;
- (void)addToDocument:(id)arg1;
- (void)removeFromOwningDocument;
- (id)unlinkFromRemote;

@end

