//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/_MSForeignObject.h>

@class MSModelObject, NSString;

@interface MSForeignObject : _MSForeignObject
{
}

+ (id)masterFromDocument:(id)arg1 withID:(id)arg2;
+ (id)foreignObjectCollectionInDocument:(id)arg1;
- (id)unlinkFromRemote;
@property(readonly, nonatomic) NSString *remoteShareID;
- (void)setLocalShareID:(id)arg1;
- (id)localShareID;
- (void)setOriginalObject:(id)arg1;
- (id)originalObject;
@property(retain, nonatomic) MSModelObject *localObject;
- (id)masterFromLibrary:(id)arg1;
- (BOOL)isLocalToDocument:(id)arg1;
- (id)matchingForeignObjectInDocument:(id)arg1;
- (void)syncWithRemote:(id)arg1;
- (BOOL)isOutOfDateWithLibrary:(id)arg1;
- (id)initWithOriginalObject:(id)arg1 inLibrary:(id)arg2;
- (void)correctInvalidGamma;

@end

