//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSPointArray.h>

@protocol MSGradientPointArrayDelegate;

@interface MSGradientPointArray : MSPointArray
{
    id <MSGradientPointArrayDelegate> _delegate;
}

@property(nonatomic) __weak id <MSGradientPointArrayDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)replacePointAtIndex:(unsigned long long)arg1 withPoint:(struct CGPoint)arg2;

@end

