//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/_MSGradientStop.h>

#import <SketchModel/MSColorConvertible-Protocol.h>

@class NSString;

@interface MSGradientStop : _MSGradientStop <MSColorConvertible>
{
}

+ (id)stopWithPosition:(double)arg1 color:(id)arg2;
- (void)convertColorsUsing:(id)arg1;
- (double)cappedBounds:(double)arg1;
- (void)setPosition:(double)arg1;
- (id)initWithPosition:(double)arg1 color:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

