//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/_MSImmutableSwatch.h>

#import <SketchModel/BCSortable-Protocol.h>

@class MSImmutableColor, NSString;

@interface MSImmutableSwatch : _MSImmutableSwatch <BCSortable>
{
}

@property(readonly, nonatomic) MSImmutableColor *color;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSString *name;
@property(readonly) Class superclass;

@end

