//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/_MSImmutableRect.h>

#import <SketchModel/MSRectProtocol-Protocol.h>

@interface MSImmutableRect : _MSImmutableRect <MSRectProtocol>
{
}

- (BOOL)isEqual:(id)arg1;
@property(readonly, nonatomic) struct CGPoint origin;
@property(readonly, nonatomic) struct CGSize size;
@property(readonly, nonatomic) struct CGRect rect;
- (id)initWithRect:(struct CGRect)arg1 constrainProportions:(BOOL)arg2;
- (id)initWithRect:(struct CGRect)arg1;

@end

