//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/_MSImmutableInferredGroupLayout.h>

@interface MSImmutableInferredGroupLayout : _MSImmutableInferredGroupLayout
{
}

+ (unsigned long long)traitsForPropertyName:(id)arg1;
- (struct CGSize)capSizeToMinAndMaxBounds:(struct CGSize)arg1;
- (BOOL)hasDefaultValues;
- (BOOL)isInferredLayout;

@end

