//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/_MSImmutableStyleShadow.h>

#import <SketchModel/NSPasteboardReading-Protocol.h>
#import <SketchModel/NSPasteboardWriting-Protocol.h>

@class NSString;

@interface MSImmutableStyleShadow : _MSImmutableStyleShadow <NSPasteboardWriting, NSPasteboardReading>
{
}

+ (id)stylePartPasteboardType;
- (void)migratePropertiesFromV119OrEarlierWithUnarchiver:(id)arg1;
- (id)pasteboardReaderWriter;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

