//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/_MSImmutableHotspotLayer.h>

@interface MSImmutableHotspotLayer : _MSImmutableHotspotLayer
{
}

+ (id)defaultName;
+ (unsigned long long)traitsForPropertyName:(id)arg1;
+ (unsigned long long)traits;
- (BOOL)shouldBeIncludedInParentPath;
- (BOOL)isLayerExportable;
- (id)overridePointAttributeNamesForOverridePropertyMigration;
- (id)directlyApplyOverrides:(id)arg1 inDocument:(id)arg2 withCache_Detach:(id)arg3;
- (id)flowDestination;
- (id)overridePointsWithParent:(id)arg1 overrides:(id)arg2 document:(id)arg3;

@end

