//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/_MSImmutablePolygonShape.h>

@interface MSImmutablePolygonShape : _MSImmutablePolygonShape
{
}

+ (id)defaultName;
- (void)migratePropertiesFromV119OrEarlierWithUnarchiver:(id)arg1;
- (BOOL)hasDefaultCurvePoints;

@end

