//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/_MSImmutableRulerData.h>

@interface MSImmutableRulerData : _MSImmutableRulerData
{
}

- (unsigned long long)hash;
- (BOOL)isEqual:(id)arg1;
- (void)performInitWithUnarchiver:(id)arg1;

@end

