//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/_MSImmutableStyleFill.h>

@interface MSImmutableStyleFill : _MSImmutableStyleFill
{
}

+ (id)defaultName;
+ (id)stylePartPasteboardType;
- (BOOL)patternFillHasOpacity;
@property(readonly, nonatomic) BOOL hasOpacity;
- (id)NSImage;
- (void)performInitWithUnarchiver:(id)arg1;
- (void)migratePropertiesFromV119OrEarlierWithUnarchiver:(id)arg1;
- (void)migratePropertiesFromV115OrEarlierWithUnarchiver:(id)arg1;
- (void)migratePropertiesFromV74OrEarlierWithUnarchiver:(id)arg1;
- (void)migratePropertiesFromV56OrEarlierWithUnarchiver:(id)arg1;

@end

