//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/_MSImmutableTextStyle.h>

@class NSDictionary;

@interface MSImmutableTextStyle : _MSImmutableTextStyle
{
    NSDictionary *_decodedAttributes;
}

@property(copy, nonatomic) NSDictionary *decodedAttributes; // @synthesize decodedAttributes=_decodedAttributes;
- (void).cxx_destruct;
- (void)migratePropertiesFromV97OrEarlierWithUnarchiver:(id)arg1;
- (void)migratePropertiesFromV81OrEarlierWithUnarchiver:(id)arg1;
@property(readonly, copy, nonatomic) NSDictionary *attributes;
- (void)decodePropertiesWithUnarchiver:(id)arg1;
- (void)encodePropertiesWithCoder:(id)arg1;
- (id)treeAsDictionary;
- (id)fontName;
- (BOOL)isFontAvailable;

@end

