//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface MSInferredLayoutState : NSObject
{
    NSMutableArray *_changedLayersRegions;
}

@property(retain, nonatomic) NSMutableArray *changedLayersRegions; // @synthesize changedLayersRegions=_changedLayersRegions;
- (void).cxx_destruct;
- (void)addLayerPair:(id)arg1;
- (id)changedRegions;
- (id)init;

@end

