//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableSet;

@interface MSInferredLayoutChangedRegion : NSObject
{
    NSMutableSet *_layerPairs;
    struct _NSRange _calculatedRange;
}

@property(retain, nonatomic) NSMutableSet *layerPairs; // @synthesize layerPairs=_layerPairs;
@property(nonatomic) struct _NSRange calculatedRange; // @synthesize calculatedRange=_calculatedRange;
- (void).cxx_destruct;
- (id)description;
- (double)changeInSize;
- (BOOL)containsLayer:(id)arg1;
- (void)addLayerPair:(id)arg1;
- (BOOL)shouldIncludeLayerPair:(id)arg1;
- (struct CGRect)updatedLayerUnionRect;
- (struct CGRect)unionRect;
- (id)init;

@end

