//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSJSONUnarchiver.h>

@class BCJSONZippedDecoder;

@interface MSJSONZippedUnarchiver : MSJSONUnarchiver
{
    BCJSONZippedDecoder *_zipDecoder;
}

@property(retain, nonatomic) BCJSONZippedDecoder *zipDecoder; // @synthesize zipDecoder=_zipDecoder;
- (void).cxx_destruct;
- (id)decodeReferenceObjectOfClass:(id)arg1 withIdentifier:(id)arg2;
- (id)filePathsInSubpath:(id)arg1 error:(id *)arg2;
- (id)unarchivedRawDataAtSubpath:(id)arg1 error:(id *)arg2;
- (id)unarchivedObjectAtSubpath:(id)arg1 error:(id *)arg2;
- (BOOL)containsFileAtSubpath:(id)arg1;
- (id)decoder;
- (id)initWithURL:(id)arg1;

@end

