//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSJSONUnarchiver.h>

@class BCJSONDecoder, NSDictionary;

@interface MSJSONDictionaryUnarchiver : MSJSONUnarchiver
{
    BCJSONDecoder *_dataDecoder;
    NSDictionary *_dictionary;
}

+ (id)unarchivedObjectFromDictionary:(id)arg1 asVersion:(long long)arg2 corruptionDetected:(char *)arg3 error:(id *)arg4;
@property(retain, nonatomic) NSDictionary *dictionary; // @synthesize dictionary=_dictionary;
@property(retain, nonatomic) BCJSONDecoder *dataDecoder; // @synthesize dataDecoder=_dataDecoder;
- (void).cxx_destruct;
- (id)decodeReferenceObjectOfClass:(id)arg1 withIdentifier:(id)arg2;
- (id)decodeRoot;
- (id)decoder;
- (id)initForReadingFromDictionary:(id)arg1;

@end

