//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSKeyedArchiver.h>

@class MSBaseArchiver;

@interface MSKeyedArchiverHelper : NSKeyedArchiver
{
    MSBaseArchiver *_archiver;
}

@property(nonatomic) __weak MSBaseArchiver *archiver; // @synthesize archiver=_archiver;
- (void).cxx_destruct;
- (void)encodeObject:(id)arg1 forKey:(id)arg2;

@end

