//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol MSLayerCoordinateSpace;

@protocol MSLayerCoordinateSpace
@property(nonatomic, readonly) struct CGAffineTransform transformForConvertingFromParentCoordinateSpace;
@property(nonatomic, readonly) struct CGAffineTransform transformForConvertingToParentCoordinateSpace;
@property(nonatomic, readonly) id <MSLayerCoordinateSpace> parentCoordinateSpace;
- (struct CGAffineTransform)transformForConvertingFromCoordinateSpace:(id <MSLayerCoordinateSpace>)arg1;
- (struct CGAffineTransform)transformForConvertingToCoordinateSpace:(id <MSLayerCoordinateSpace>)arg1;
- (struct CGVector)convertVector:(struct CGVector)arg1 fromCoordinateSpace:(id <MSLayerCoordinateSpace>)arg2;
- (struct CGVector)convertVector:(struct CGVector)arg1 toCoordinateSpace:(id <MSLayerCoordinateSpace>)arg2;
- (struct CGRect)convertRect:(struct CGRect)arg1 fromCoordinateSpace:(id <MSLayerCoordinateSpace>)arg2;
- (struct CGRect)convertRect:(struct CGRect)arg1 toCoordinateSpace:(id <MSLayerCoordinateSpace>)arg2;
- (struct CGPoint)convertPoint:(struct CGPoint)arg1 fromCoordinateSpace:(id <MSLayerCoordinateSpace>)arg2;
- (struct CGPoint)convertPoint:(struct CGPoint)arg1 toCoordinateSpace:(id <MSLayerCoordinateSpace>)arg2;
@property(nonatomic, readonly) struct CGRect bounds;
@end

