//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSLayerTraits-Protocol.h>
#import <SketchModel/NSObject-Protocol.h>

@class NSAffineTransform, NSArray, NSString;

@protocol MSLayerProtocol <NSObject, MSLayerTraits>
- (BOOL)hasEnabledFill;
- (NSArray *)childrenIncludingSelf:(BOOL)arg1;
- (NSArray *)children;
- (id)layerWithID:(NSString *)arg1;
@property(nonatomic, readonly) BOOL isLayerExportable;
- (NSAffineTransform *)transformForRect:(struct CGRect)arg1;
@property(nonatomic, readonly) struct CGPoint origin;
@property(nonatomic, readonly) struct BCEdgePaddings influenceRectEdgePaddingsThatCascadeToContainedLayers;
@property(nonatomic, readonly) struct CGAffineTransform CGTransformForFrame;
@property(nonatomic, readonly) BOOL hasTransforms;
@property(nonatomic, readonly) struct CGRect bounds;
@property(nonatomic, readonly) struct CGRect rect;
@property(nonatomic, readonly) NSString *objectID;
@property(nonatomic, readonly) double rotation;
@property(nonatomic, readonly) BOOL isFlippedVertical;
@property(nonatomic, readonly) BOOL isFlippedHorizontal;
@property(nonatomic, readonly) BOOL isVisible;
@end

