//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSLayerWithBackgroundColor-Protocol.h>

@class MSColor;

@protocol MSLayerWithMutableBackgroundColor <MSLayerWithBackgroundColor>
@property(retain, nonatomic) MSColor *backgroundColor;
@end

