//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MSLayerMovement : NSObject
{
}

+ (void)moveToBack:(id)arg1;
+ (void)moveToFront:(id)arg1;
+ (void)moveBackward:(id)arg1;
+ (void)moveToTopOfHierarchy:(id)arg1;
+ (BOOL)canMoveLayerToTopOfHierarchy:(id)arg1;
+ (void)moveLayer:(id)arg1 withParent:(id)arg2 toNewParent:(id)arg3 forceTop:(BOOL)arg4;
+ (void)moveLayersUpHierarchy:(id)arg1;
+ (BOOL)canMoveLayerUpHierarchy:(id)arg1;
+ (BOOL)canMoveLayersBackward:(id)arg1;
+ (BOOL)canMoveLayersForward:(id)arg1;
+ (void)moveForward:(id)arg1;

@end

