//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <BCFoundation/BCSingleton.h>

@class NSArray, NSBitmapImageRep;

@interface MSModelResources : BCSingleton
{
    NSArray *_noiseImages;
    NSBitmapImageRep *_errorPattern;
}

- (void).cxx_destruct;
- (id)resourcesNeedingMigration;
- (id)loadNoiseImageWithIndex:(long long)arg1;
- (id)loadImageWithName:(id)arg1;
@property(readonly, nonatomic) NSBitmapImageRep *errorPattern;
@property(readonly, nonatomic) NSArray *noiseImages;

@end

