//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface MSOpenTypeFontAttributes : NSObject
{
    NSMutableDictionary *_attributes;
    double _pointSize;
}

- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
- (id)description;
- (BOOL)containsFontSelector:(id)arg1;
- (id)findFontFeature:(id)arg1;
- (void)toggleFontSelectorDefinition:(id)arg1;
- (BOOL)isFontSelectorDefined:(id)arg1;
- (id)modifiedFont;
- (id)initWithFont:(id)arg1;
- (id)updatedAttributesForTesting;
- (id)initWithFontAttributesForTesting:(id)arg1;

@end

