//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MSOpenTypeFeature, NSDictionary, NSNumber, NSString;

@interface MSOpenTypeSelector : NSObject
{
    NSDictionary *_dictionary;
    MSOpenTypeFeature *_parent;
}

@property(readonly, nonatomic) __weak MSOpenTypeFeature *parent; // @synthesize parent=_parent;
- (void).cxx_destruct;
- (id)description;
- (id)fontAttributeForInsertion;
@property(readonly, nonatomic) BOOL isDefault;
@property(readonly, nonatomic) NSNumber *identifier;
@property(readonly, nonatomic) NSString *name;
- (id)initWithDictionary:(id)arg1 parentFeature:(id)arg2;

@end

