//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MSSymbolInstance, NSAffineTransform, NSArray;

@interface MSOverrideRepresentationBase : NSObject
{
    BOOL _isEditable;
    NSArray *_children;
    MSSymbolInstance *_instance;
}

@property(readonly, nonatomic) BOOL isEditable; // @synthesize isEditable=_isEditable;
@property(readonly, nonatomic) __weak MSSymbolInstance *instance; // @synthesize instance=_instance;
@property(retain, nonatomic) NSArray *children; // @synthesize children=_children;
- (void).cxx_destruct;
@property(readonly, nonatomic) BOOL isOpen;
@property(readonly, nonatomic) NSArray *flattenedChildren;
- (id)firstOverridePassingTest:(CDUnknownBlockType)arg1;
- (void)enumerate:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) NSArray *selectedOverrides;
- (void)updateAfterSelectingChild;
@property(readonly, nonatomic) NSAffineTransform *transformForConvertingToInstance;
- (void)syncChildrenWithOverridesIfNeeded;
- (void)syncChildrenWithOverrides:(id)arg1;
- (id)initWithInstance:(id)arg1;

@end

