//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MSPastingViewport : NSObject
{
    double _zoomValue;
    struct CGRect _visibleRect;
}

+ (id)viewportWithVisibleRect:(struct CGRect)arg1 zoom:(double)arg2;
@property(nonatomic) struct CGRect visibleRect; // @synthesize visibleRect=_visibleRect;
@property(nonatomic) double zoomValue; // @synthesize zoomValue=_zoomValue;
- (id)viewportContainingLayers:(id)arg1;
- (BOOL)isEqual:(id)arg1;

@end

