//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MSPasteboardLayersBase : NSObject
{
}

+ (id)usedSymbolsInContainer:(id)arg1 document:(id)arg2;
+ (void)usedSymbolsInInstance:(id)arg1 document:(id)arg2 foundSet:(id)arg3;
+ (void)usedSymbolsInSymbolWithID:(id)arg1 document:(id)arg2 foundSet:(id)arg3;
+ (id)dictionaryFromPasteboardLayers:(id)arg1;
+ (id)dataFromPasteboardDictionary:(id)arg1;
+ (id)pasteboardDataFromData:(id)arg1;

@end

