//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MSImmutableColor, MSPath, NSString;

@interface MSPathWithColor : NSObject
{
    MSImmutableColor *_color;
    MSPath *_path;
    NSString *_representedString;
}

@property(retain, nonatomic) NSString *representedString; // @synthesize representedString=_representedString;
@property(retain, nonatomic) MSPath *path; // @synthesize path=_path;
@property(retain, nonatomic) MSImmutableColor *color; // @synthesize color=_color;
- (void).cxx_destruct;

@end

