//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/_MSPatchInfo.h>

@class NSObject;

@interface MSPatchInfo : _MSPatchInfo
{
    NSObject *__patchContainer;
}

@property(retain, nonatomic) NSObject *_patchContainer; // @synthesize _patchContainer=__patchContainer;
- (void).cxx_destruct;
- (void)syncPropertiesFromObject:(id)arg1;
- (void)copyPropertiesToObject:(id)arg1 options:(unsigned long long)arg2;
- (void)performInitWithImmutableModelObject:(id)arg1;

@end

