//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MSPath, NSArray;

@interface MSPathNode : NSObject
{
    BOOL _isFilled;
    MSPath *_path;
    NSArray *_children;
}

+ (id)rootNodeFromPath:(id)arg1;
+ (id)pathNodeFromClipperNode:(struct ClipperGraphNode *)arg1 isFilled:(BOOL)arg2;
@property(readonly, nonatomic) BOOL isFilled; // @synthesize isFilled=_isFilled;
@property(readonly, copy, nonatomic) NSArray *children; // @synthesize children=_children;
@property(readonly, nonatomic) MSPath *path; // @synthesize path=_path;
- (void).cxx_destruct;
- (id)debugQuickLookObject;
- (id)collapsedPath;
- (void)recursivelyAddChildPathsToChain:(id)arg1;
- (id)nodeWithInset:(double)arg1 joinStrategy:(unsigned long long)arg2;
- (id)initWithPath:(id)arg1 isFilled:(BOOL)arg2 children:(id)arg3;

@end

