//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/NSObject-Protocol.h>

@class MSRect;

@protocol MSRectDelegate <NSObject>
- (void)rect:(MSRect *)arg1 didChangeFromRect:(struct CGRect)arg2;
@end

