//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/_MSRectangleShape.h>

@interface MSRectangleShape : _MSRectangleShape
{
}

+ (id)defaultPointsWithRadius:(double)arg1;
+ (void)applyRadius:(double)arg1 toPoints:(id)arg2;
+ (id)shapeWithRect:(struct CGRect)arg1 fillColor:(id)arg2;
- (BOOL)canFlatten;
- (void)multiplyBy:(double)arg1;
@property(readonly, nonatomic) double maximumAllowedRadius;
- (void)resetPoints;
- (id)defaultCurvePoints;
- (id)CSSAttributes;
- (id)CSSAttributeString;

@end

