//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/_MSSharedObjectContainer.h>

@interface MSSharedObjectContainer : _MSSharedObjectContainer
{
}

- (id)objectsSortedByName;
- (unsigned long long)numberOfSharedObjects;
- (long long)indexOfSharedObject:(id)arg1;
- (id)sharedObjectAtIndex:(unsigned long long)arg1;
- (id)sharedObjectWithID:(id)arg1;
- (id)objectsReferencing:(id)arg1 inContainer:(id)arg2;
- (void)removeSharedObject:(id)arg1;
- (void)removeSharedObjects:(id)arg1;
@property(readonly, nonatomic) Class sharedObjectClass;

@end

