//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class MSDocumentData, NSString;

@protocol MSSharedStylePasting
@property(readonly, nonatomic) NSString *currentObjectID_MSSharedStylePasting;
- (NSString *)handlePasteIntoDocument:(MSDocumentData *)arg1;
@end

