//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/_MSSliceLayer.h>

#import <SketchModel/MSColorConvertible-Protocol.h>
#import <SketchModel/MSLayerWithMutableBackgroundColor-Protocol.h>

@class MSColor, NSString;

@interface MSSliceLayer : _MSSliceLayer <MSLayerWithMutableBackgroundColor, MSColorConvertible>
{
}

- (void)changeColor:(id)arg1;
- (void)convertColorsUsing:(id)arg1;
- (id)immutableBackgroundColor;
- (id)rootForNameUniquing;
- (BOOL)canRotate;
- (BOOL)canBeTransformed;
- (void)setName:(id)arg1;

// Remaining properties
@property(retain, nonatomic) MSColor *backgroundColor;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) BOOL hasBackgroundColor;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

