//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSBezierFillet.h>

@class NSArray;

@interface MSSmoothBezierFillet : MSBezierFillet
{
    NSArray *_arcSegments;
}

+ (id)smoothBezierFilletWithLineSegment1:(id)arg1 lineSegment2:(id)arg2 filletRadius:(double)arg3;
@property(retain, nonatomic) NSArray *arcSegments; // @synthesize arcSegments=_arcSegments;
- (void).cxx_destruct;
- (void)addArcToBezierPath:(id)arg1 orCGPath:(struct CGPath *)arg2;
- (id)reversedFillet;

@end

