//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/_MSStyleColorControls.h>

@interface MSStyleColorControls : _MSStyleColorControls
{
}

+ (id)keyPathsForValuesAffectingValueForKey:(id)arg1;
- (unsigned long long)styleType;
- (void)resetToDefaultValues;
- (BOOL)hasDefaultColorControlsValues;

@end

