//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/_MSSwatch.h>

@class MSColor;

@interface MSSwatch : _MSSwatch
{
}

- (void)updateWithColor:(id)arg1;
- (id)makeReferencingColor;
- (id)initWithName:(id)arg1 color:(id)arg2;
@property(readonly, nonatomic) MSColor *color;

@end

