//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSAvailableOverride.h>

@class NSArray;

@interface MSSymbolOverride : MSAvailableOverride
{
    NSArray *_internalChildren;
}

@property(readonly, nonatomic) NSArray *internalChildren; // @synthesize internalChildren=_internalChildren;
- (void).cxx_destruct;
- (id)containedPropertyID;
- (void)calculateAppearsOnCanvasWithAncestors:(id)arg1;
- (void)addChild:(id)arg1;
- (id)children;

@end

