//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface MSTextPreviewLayerMetadata : NSObject
{
    NSDictionary *_attributedStringToPageNumberDictionary;
    NSDictionary *_objectIDtoFrames;
}

+ (id)metadataForTextLayers:(id)arg1 pageMapping:(id)arg2;
- (void).cxx_destruct;
- (struct CGRect)previewRectForLayerID:(id)arg1;
- (id)pageIndexForLayer:(id)arg1;
- (id)initWithData:(id)arg1;

@end

