//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSNumber, NSString;

@interface MSVariableFontAxis : NSObject
{
    NSDictionary *_dictionary;
    NSString *_name;
    NSNumber *_minValue;
    NSNumber *_maxValue;
    NSNumber *_identifier;
    NSNumber *_currentValue;
}

@property(copy, nonatomic) NSNumber *currentValue; // @synthesize currentValue=_currentValue;
@property(readonly, nonatomic) NSNumber *identifier; // @synthesize identifier=_identifier;
@property(readonly, nonatomic) NSNumber *maxValue; // @synthesize maxValue=_maxValue;
@property(readonly, nonatomic) NSNumber *minValue; // @synthesize minValue=_minValue;
@property(readonly, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1 currentValue:(id)arg2;

@end

