//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSAttributedString.h>

#import <SketchModel/MSCoding-Protocol.h>

@class NSString;

@interface NSAttributedString (MSBaseArchiver) <MSCoding>
- (id)initWithUnarchiver:(id)arg1;
- (void)encodeWithArchiver:(id)arg1;
- (id)attributeForKey:(id)arg1;
- (id)currentListStyle;
- (id)treeAsDictionary;
- (id)attributedStringAttributes;
- (id)translatedToColorSpace:(id)arg1;
- (id)convertedToColorSpace:(id)arg1;
- (id)attributedStringWithDocumentColorSpace:(id)arg1 convert:(BOOL)arg2;
- (id)standardAttributedStringWithDocumentColorSpace:(id)arg1;
- (id)initWithString:(id)arg1 attributedStringAttributes:(id)arg2;
- (id)attributedStringByApplyingBlock:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, nonatomic) NSString *archiveReferenceIdentifier_bc;
@end

