//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSImage.h>

@interface NSImage (Alpha)
+ (id)imageFromDataArchive:(id)arg1;
- (BOOL)imageHasAlpha;
- (BOOL)isAssetEqual:(id)arg1;
- (unsigned long long)assetType;
- (id)PDFImageRep;
- (id)EPSImageRep;
- (BOOL)hasEPSData;
- (id)bitmapData;
- (BOOL)hasPDFData;
- (id)dataForArchiving;
- (id)treeAsDictionary;
@end

