//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSIndexPath.h>

@interface NSIndexPath (MSPath)
+ (id)indexPathForContour_ms:(unsigned long long)arg1 segment:(unsigned long long)arg2;
- (unsigned long long)segmentIndex_ms;
- (unsigned long long)contourIndex_ms;
@end

