//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextList.h>

@interface NSTextList (BCJSONEncoding)
- (id)initWithJSONDecoder:(id)arg1;
- (void)encodeAsJSON:(id)arg1;
- (id)treeAsDictionary;
- (BOOL)propertiesAreEqual:(id)arg1 forPurpose:(unsigned long long)arg2;
@end

