//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GCDWebServers/NSObject-Protocol.h>

@class NSData;

@protocol GCDWebServerBodyWriter <NSObject>
- (BOOL)close:(id *)arg1;
- (BOOL)writeData:(NSData *)arg1 error:(id *)arg2;
- (BOOL)open:(id *)arg1;
@end

