//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface GCDWebServerMultiPart : NSObject
{
    NSString *_controlName;
    NSString *_contentType;
    NSString *_mimeType;
}

@property(readonly, nonatomic) NSString *mimeType; // @synthesize mimeType=_mimeType;
@property(readonly, nonatomic) NSString *contentType; // @synthesize contentType=_contentType;
@property(readonly, nonatomic) NSString *controlName; // @synthesize controlName=_controlName;
- (void).cxx_destruct;
- (id)initWithControlName:(id)arg1 contentType:(id)arg2;

@end

