//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSMutableArray, NSMutableData, NSString;

@interface GCDWebServerMIMEStreamParser : NSObject
{
    NSData *_boundary;
    NSString *_defaultcontrolName;
    int _state;
    NSMutableData *_data;
    NSMutableArray *_arguments;
    NSMutableArray *_files;
    NSString *_controlName;
    NSString *_fileName;
    NSString *_contentType;
    NSString *_tmpPath;
    int _tmpFile;
    GCDWebServerMIMEStreamParser *_subParser;
}

+ (void)initialize;
- (void).cxx_destruct;
- (BOOL)isAtEnd;
- (BOOL)appendBytes:(const void *)arg1 length:(unsigned long long)arg2;
- (BOOL)_parseData;
- (void)dealloc;
- (id)initWithBoundary:(id)arg1 defaultControlName:(id)arg2 arguments:(id)arg3 files:(id)arg4;

@end

