//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GCDWebServers/GCDWebServerDataRequest.h>

@class NSDictionary;

@interface GCDWebServerURLEncodedFormRequest : GCDWebServerDataRequest
{
    NSDictionary *_arguments;
}

+ (id)mimeType;
@property(readonly, nonatomic) NSDictionary *arguments; // @synthesize arguments=_arguments;
- (void).cxx_destruct;
- (id)description;
- (BOOL)close:(id *)arg1;

@end

