//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GCDWebServers/GCDWebServerBodyEncoder.h>

@interface GCDWebServerGZipEncoder : GCDWebServerBodyEncoder
{
    struct z_stream_s _stream;
    BOOL _finished;
}

- (void)close;
- (id)readData:(id *)arg1;
- (BOOL)open:(id *)arg1;
- (id)initWithResponse:(id)arg1 reader:(id)arg2;

@end

