//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GCDWebServers/GCDWebServerMultiPart.h>

@class NSData, NSString;

@interface GCDWebServerMultiPartArgument : GCDWebServerMultiPart
{
    NSData *_data;
    NSString *_string;
}

@property(readonly, nonatomic) NSString *string; // @synthesize string=_string;
@property(readonly, nonatomic) NSData *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (id)description;
- (id)initWithControlName:(id)arg1 contentType:(id)arg2 data:(id)arg3;

@end

