//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <GCDWebServers/GCDWebServerBodyWriter-Protocol.h>

@class GCDWebServerRequest, NSString;
@protocol GCDWebServerBodyWriter;

@interface GCDWebServerBodyDecoder : NSObject <GCDWebServerBodyWriter>
{
    GCDWebServerRequest *_request;
    id <GCDWebServerBodyWriter> _writer;
}

- (BOOL)close:(id *)arg1;
- (BOOL)writeData:(id)arg1 error:(id *)arg2;
- (BOOL)open:(id *)arg1;
- (id)initWithRequest:(id)arg1 writer:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

