//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GCDWebServers/GCDWebServerRequest.h>

@class GCDWebServerMIMEStreamParser, NSArray, NSMutableArray;

@interface GCDWebServerMultiPartFormRequest : GCDWebServerRequest
{
    GCDWebServerMIMEStreamParser *_parser;
    NSMutableArray *_arguments;
    NSMutableArray *_files;
}

+ (id)mimeType;
@property(readonly, nonatomic) NSArray *files; // @synthesize files=_files;
@property(readonly, nonatomic) NSArray *arguments; // @synthesize arguments=_arguments;
- (void).cxx_destruct;
- (id)description;
- (id)firstFileForControlName:(id)arg1;
- (id)firstArgumentForControlName:(id)arg1;
- (BOOL)close:(id *)arg1;
- (BOOL)writeData:(id)arg1 error:(id *)arg2;
- (BOOL)open:(id *)arg1;
- (id)initWithMethod:(id)arg1 url:(id)arg2 headers:(id)arg3 path:(id)arg4 query:(id)arg5;

@end

