//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GCDWebServers/GCDWebServerRequest.h>

@class NSString;

@interface GCDWebServerFileRequest : GCDWebServerRequest
{
    NSString *_temporaryPath;
    int _file;
}

@property(readonly, nonatomic) NSString *temporaryPath; // @synthesize temporaryPath=_temporaryPath;
- (void).cxx_destruct;
- (id)description;
- (BOOL)close:(id *)arg1;
- (BOOL)writeData:(id)arg1 error:(id *)arg2;
- (BOOL)open:(id *)arg1;
- (void)dealloc;
- (id)initWithMethod:(id)arg1 url:(id)arg2 headers:(id)arg3 path:(id)arg4 query:(id)arg5;

@end

