//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <GCDWebServers/GCDWebServerBodyDecoder.h>

@interface GCDWebServerGZipDecoder : GCDWebServerBodyDecoder
{
    struct z_stream_s _stream;
    BOOL _finished;
}

- (BOOL)close:(id *)arg1;
- (BOOL)writeData:(id)arg1 error:(id *)arg2;
- (BOOL)open:(id *)arg1;

@end

