//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchSVG/SVGBasicShape.h>

@interface _SVGRectangleShape : SVGBasicShape
{
    double _cornerRadius;
}

+ (id)attributeNames;
+ (id)relationshipNames;
+ (id)propertyNames;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;

@end

