//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchSVG/SVGDrawableElement.h>

@class SVGElement;

@interface _SVGLink : SVGDrawableElement
{
    SVGElement *_link;
}

+ (id)attributeNames;
+ (id)relationshipNames;
+ (id)propertyNames;
@property(retain, nonatomic) SVGElement *link; // @synthesize link=_link;
- (void).cxx_destruct;
- (void)primitiveSetLink:(id)arg1;

@end

