//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchSVG/SVGElement.h>

@class MSImmutableColor;

@interface _SVGGradientStop : SVGElement
{
    MSImmutableColor *_color;
    double _position;
}

+ (id)attributeNames;
+ (id)relationshipNames;
+ (id)propertyNames;
@property(nonatomic) double position; // @synthesize position=_position;
@property(retain, nonatomic) MSImmutableColor *color; // @synthesize color=_color;
- (void).cxx_destruct;

@end

