//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSImmutableRectangleShape.h>

@interface MSImmutableRectangleShape (SVGExport)
- (BOOL)isSVGRectangle;
- (void)simplifyPathElement:(id)arg1 exporter:(id)arg2 inset:(double)arg3;
@end

