//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchSVG/MSXMLElementWrapper.h>

@class MSSVGMerge, NSString;

@interface MSSVGFilter : MSXMLElementWrapper
{
    MSSVGMerge *_finalMerge;
}

+ (id)filter;
+ (id)elementName;
@property(retain, nonatomic) MSSVGMerge *finalMerge; // @synthesize finalMerge=_finalMerge;
- (void).cxx_destruct;
- (void)close;
- (void)addFilterOutput:(id)arg1;
- (void)addFilterItem:(id)arg1;
@property(copy, nonatomic) NSString *href; // @dynamic href;
- (void)dealloc;
- (id)initWithName:(id)arg1;

// Remaining properties
@property(copy, nonatomic) NSString *filterRes; // @dynamic filterRes;
@property(copy, nonatomic) NSString *filterUnits; // @dynamic filterUnits;
@property(copy, nonatomic) NSString *height; // @dynamic height;
@property(copy, nonatomic) NSString *primitiveUnits; // @dynamic primitiveUnits;
@property(copy, nonatomic) NSString *width; // @dynamic width;
@property(copy, nonatomic) NSString *x; // @dynamic x;
@property(copy, nonatomic) NSString *y; // @dynamic y;

@end

