//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchSVG/MSSVGfeFilterPrimitive.h>

@class NSString;

@interface MSSVGGaussianBlur : MSSVGfeFilterPrimitive
{
}

+ (id)elementName;

// Remaining properties
@property(copy, nonatomic) NSString *in; // @dynamic in;
@property(copy, nonatomic) NSString *stdDeviation; // @dynamic stdDeviation;

@end

