//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchSVG/MSSVGfeFilterPrimitive.h>

@class NSString;

@interface MSSVGOffset : MSSVGfeFilterPrimitive
{
}

+ (id)elementName;

// Remaining properties
@property(nonatomic) double dx; // @dynamic dx;
@property(nonatomic) double dy; // @dynamic dy;
@property(copy, nonatomic) NSString *in; // @dynamic in;

@end

