//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSBezierPath.h>

@interface NSBezierPath (SVGBezierPath)
+ (id)bezierPathFromSVGString:(id)arg1;
- (id)svgPathAttribute;
- (void)addSVGArcWithAngle:(double)arg1 radius:(struct CGSize)arg2 from:(struct CGPoint)arg3 to:(struct CGPoint)arg4 largeArc:(BOOL)arg5 sweep:(BOOL)arg6;
@end

