//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (SVG)
+ (id)svgStringWithPercentageFractionalValue:(double)arg1;
+ (id)svgStringWithPercentageValue:(double)arg1;
+ (id)svgStringWithNumberValue:(double)arg1;
+ (id)svgStringWithPixelValue:(double)arg1;
+ (id)stringWithInt:(long long)arg1 suffix:(id)arg2;
- (id)svgURL;
- (id)transformTrimmedName;
@end

