//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSXMLDocument.h>

@interface NSXMLDocument (SVGDocument)
+ (id)SVGDocumentWithBezierPath:(id)arg1;
- (id)bezierPathElement:(id)arg1;
- (id)data;
- (id)description;
- (id)createSVGForBezierPath:(id)arg1;
@end

