//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchSVG/_SVGFill.h>

@interface SVGFill : _SVGFill
{
}

+ (id)fillForXML:(id)arg1 element:(id)arg2 parent:(id)arg3;
+ (id)styleDefaults;
- (id)svgAttributesDescription;
- (void)setupFromString:(id)arg1 opacity:(id)arg2;

@end

