//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchSVG/_SVGGradient.h>

@interface SVGGradient : _SVGGradient
{
}

@property(readonly, nonatomic) BOOL usesAbsoluteUnits;
- (id)stopsElements;
- (id)svgAttributesDescription;
- (struct CGPoint)to;
- (struct CGPoint)from;
- (void)setupLinearGradientWithXML:(id)arg1;
- (void)setupRadialGradientWithXML:(id)arg1;
- (void)processSelf:(id)arg1;

@end

