//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchSVG/_SVGMask.h>

@interface SVGMask : _SVGMask
{
}

- (BOOL)containsDrawables;
- (void)resolvedValue:(id)arg1 forProperty:(id)arg2;
- (void)processSelf:(id)arg1;

@end

