//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchSVG/_SVGPathShape.h>

@interface SVGPathShape : _SVGPathShape
{
}

- (void)nameLayer:(id)arg1;
- (id)makeOwnLayerWithParentLayer:(id)arg1;
- (id)svgAttributesDescription;
- (void)processSelf:(id)arg1;
- (void)processPath:(id)arg1;

@end

