//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface SVGTransformImporter : NSObject
{
}

+ (id)matrixTransformFromComponents:(id)arg1;
+ (id)rotateTransformFromComponents:(id)arg1;
+ (id)scaleTransformFromComponents:(id)arg1;
+ (id)translateTransformFromComponents:(id)arg1;
+ (id)transformFromName:(id)arg1 components:(id)arg2;
+ (id)transformFromString:(id)arg1;

@end

