//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchSVG/_SVGText.h>

@interface SVGText : _SVGText
{
}

+ (id)styleDefaults;
- (void)applyEffectsToLayer:(id)arg1;
- (id)enclosingLayerForLayer:(id)arg1 parentLayer:(id)arg2;
- (id)makeOwnLayerWithParentLayer:(id)arg1;
- (id)svgAttributesDescription;
- (id)name;
- (void)processSelf:(id)arg1;
- (BOOL)containsDrawables;
- (double)doubleValueFromXML:(id)arg1 attributeWithName:(id)arg2 orParent:(id)arg3;

@end

