//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC17SketchControllersP33_47F7031F574FC64E2BE62BE063C82B0D16TextViewEditInfo : _TtCs12_SwiftObject
{
    MISSING_TYPE *textView;
    MISSING_TYPE *typingAttributes;
    MISSING_TYPE *storageCopyForUndo;
    MISSING_TYPE *editedRanges;
}

@end

