//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPopUpButton.h>

@class MISSING_TYPE, NSColor;

@interface _TtC17SketchControllers20MSToolbarPopUpButton : NSPopUpButton
{
    MISSING_TYPE *badgeView;
}

+ (void)setCellClass:(Class)arg1;
+ (Class)cellClass;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 pullsDown:(BOOL)arg2;
@property(nonatomic, retain) NSColor *badgeColor;
@property(nonatomic) BOOL badgeHidden;

@end

