//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/_TtC17SketchControllers26MSVectorComponentSpecifier.h>

@interface _TtC17SketchControllers26MSVectorComponentSpecifier (SketchControllers)
@property(nonatomic, readonly) long long hash;
- (BOOL)isEqual:(id)arg1;
@end

