//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/MSLayoutElement.h>

@class MISSING_TYPE;

@interface _TtC17SketchControllers7MSStack : MSLayoutElement
{
    MISSING_TYPE *axis;
    MISSING_TYPE *spacing;
}

@property(nonatomic) double spacing; // @synthesize spacing;

@end

