//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC17SketchControllers25MSCollectionOverlayLayout : NSObject
{
    MISSING_TYPE *collectionOverlay;
    MISSING_TYPE *zoomScale;
    MISSING_TYPE *invalidationContext;
}

- (void).cxx_destruct;
- (id)init;
- (id)layoutAttributesForSupplementaryElementOfKind:(id)arg1 at:(id)arg2;
- (id)layoutAttributesForItemAt:(id)arg1;
- (id)layoutAttributesForElementsIn:(struct CGRect)arg1;
- (void)prepareLayout;

@end

