//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/MSOverlay.h>

@class MISSING_TYPE, MSSelectHandleGestureRecognizer, NSArray, NSSet, _TtC17SketchControllers25MSCollectionOverlayLayout;
@protocol _TtP17SketchControllers27MSCollectionOverlayDelegate_, _TtP17SketchControllers29MSCollectionOverlayDataSource_;

@interface _TtC17SketchControllers19MSCollectionOverlay : MSOverlay
{
    MISSING_TYPE *layout;
    MISSING_TYPE *dataSource;
    MISSING_TYPE *delegate;
    MISSING_TYPE *allowsSelection;
    MISSING_TYPE *allowsMultipleSelection;
    MISSING_TYPE *allowsEmptySelection;
    MISSING_TYPE *selectionIndexPaths;
    MISSING_TYPE *$__lazy_storage_$_selectionGestureRecognizer;
    MISSING_TYPE *cachedOverlayItems;
}

- (void).cxx_destruct;
- (id)overlayItems:(unsigned long long)arg1 parameters:(struct MSRenderingParameters)arg2;
- (void)setNeedsDisplay;
- (id)overlayItemImages:(struct CGColorSpace *)arg1 backingScale:(double)arg2;
@property(nonatomic, retain) MSSelectHandleGestureRecognizer *selectionGestureRecognizer;
- (void)toggleSelectionOfItemAtIndexPath:(id)arg1 notifyDelegate:(BOOL)arg2;
- (void)deselectItemAtIndexPath:(id)arg1;
- (void)deselectItemsAtIndexPaths:(id)arg1;
- (void)selectItemAtIndexPath:(id)arg1;
- (void)selectItemsAtIndexPaths:(id)arg1;
@property(nonatomic, copy) NSSet *selectionIndexPaths;
@property(nonatomic) BOOL allowsEmptySelection; // @synthesize allowsEmptySelection;
@property(nonatomic) BOOL allowsMultipleSelection; // @synthesize allowsMultipleSelection;
@property(nonatomic) BOOL allowsSelection; // @synthesize allowsSelection;
- (void)reloadItemsAtIndexPaths:(id)arg1;
- (void)reloadData;
@property(nonatomic) __weak id <_TtP17SketchControllers27MSCollectionOverlayDelegate_> delegate; // @synthesize delegate;
@property(nonatomic) __weak id <_TtP17SketchControllers29MSCollectionOverlayDataSource_> dataSource; // @synthesize dataSource;
@property(nonatomic, readonly) NSArray *indexPaths;
- (long long)numberOfItemsIn:(long long)arg1;
@property(nonatomic, readonly) long long numberOfSections;
- (id)layoutAttributesForSupplementaryElementOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (id)indexPathForItemAtPoint:(struct CGPoint)arg1;
@property(nonatomic, retain) _TtC17SketchControllers25MSCollectionOverlayLayout *layout; // @synthesize layout;
- (id)init;
- (id)initWithLayout:(id)arg1;

@end

