//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPopUpButtonCell.h>

@class MISSING_TYPE;

@interface _TtC17SketchControllers36MSConditionallyOffsetPopUpButtonCell : NSPopUpButtonCell
{
    MISSING_TYPE *_yOffsets;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initTextCell:(id)arg1 pullsDown:(BOOL)arg2;
- (struct CGRect)imageRectForBounds:(struct CGRect)arg1;
- (void)setYOffset:(double)arg1 forOperatingSystemVersion:(CDStruct_2ec95fd7)arg2 backingScaleFactor:(double)arg3;
- (double)yOffsetFor:(double)arg1;

@end

