//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC17SketchControllers21MSLayerSnappingResult : NSObject
{
    MISSING_TYPE *result;
    MISSING_TYPE *alignmentRect;
    MISSING_TYPE *coordinateSpace;
    MISSING_TYPE *layers;
    MISSING_TYPE *tool;
    MISSING_TYPE *wantOppositeMeasurements;
}

- (void).cxx_destruct;
- (id)init;

@end

