//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/_TtC17SketchControllers26MSVectorComponentSpecifier.h>

#import <SketchControllers/NSCopying-Protocol.h>

@interface _TtC17SketchControllers26MSVectorComponentSpecifier (SketchControllers1) <NSCopying>
- (id)copyWithZone:(void *)arg1;
@end

