//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/_TtC17SketchControllers19MSCollectionOverlay.h>

#import <SketchControllers/MSSelectHandleGestureRecognizerDelegate-Protocol.h>

@interface _TtC17SketchControllers19MSCollectionOverlay (SketchControllers) <MSSelectHandleGestureRecognizerDelegate>
- (void)performSelection:(id)arg1;
- (BOOL)gestureRecognizerShouldDelaySelectionUntilMouseUp:(id)arg1;
@end

