//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface _TtC17SketchControllers21MSFrequentColorFinder : NSObject
{
}

+ (void)findFrequentColorsInDocument:(id)arg1 maxCount:(long long)arg2 ignoreAlpha:(BOOL)arg3 excludeForeignSymbols:(BOOL)arg4 callback:(CDUnknownBlockType)arg5;
- (id)init;

@end

