//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <BCFoundation/_TtC12BCFoundation9BCRounder.h>

@interface _TtC12BCFoundation9BCRounder (MSVectorRounding)
+ (id)vectorRounder;
+ (id)rounderWithPrecision:(unsigned long long)arg1;
- (struct CGPoint)roundedPoint:(struct CGPoint)arg1 coordinateSpace:(id)arg2 inCoordinateSpace:(id)arg3;
@end

