//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC17SketchControllers15ComponentDiffer : _TtCs12_SwiftObject
{
    MISSING_TYPE *oldDocument;
    MISSING_TYPE *newDocument;
    MISSING_TYPE *kind;
    MISSING_TYPE *addedComponents;
    MISSING_TYPE *addedForeignComponents;
    MISSING_TYPE *removedComponents;
    MISSING_TYPE *removedForeignComponents;
    MISSING_TYPE *changedComponents;
    MISSING_TYPE *changedForeignComponents;
}

@end

