//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/_TtC17SketchControllers12MSResizeTool.h>

@protocol MSLayerCoordinateSpace;

@interface _TtC17SketchControllers12MSResizeTool (SketchControllers)
- (struct CGRect)alignmentRectInCoordinateSpace:(id)arg1 options:(unsigned long long)arg2;
@property(nonatomic, readonly) id <MSLayerCoordinateSpace> coordinateSpaceForSnapping;
@end

