//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

__attribute__((visibility("hidden")))
@interface _TtC17SketchControllers20MSSavedLayerGeometry : NSObject
{
    MISSING_TYPE *layer;
    MISSING_TYPE *_framesByLayerID;
}

- (void).cxx_destruct;
- (id)init;

@end

