//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;
@protocol MSLayerCoordinateSpace;

@interface _TtC17SketchControllers22CoordinateSpaceAdaptor : _TtCs12_SwiftObject
{
    MISSING_TYPE *coordinateSpace;
    MISSING_TYPE *parentCoordinateSpace;
}

@property(nonatomic) __weak id <MSLayerCoordinateSpace> parentCoordinateSpace; // @synthesize parentCoordinateSpace;

@end

