//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSIndexPath, NSSet, _TtC17SketchControllers19MSCollectionOverlay;

@protocol _TtP17SketchControllers27MSCollectionOverlayDelegate_

@optional
- (BOOL)collectionOverlay:(_TtC17SketchControllers19MSCollectionOverlay *)arg1 shouldDeferSelectionAtIndexPath:(NSIndexPath *)arg2;
- (void)collectionOverlay:(_TtC17SketchControllers19MSCollectionOverlay *)arg1 didDeselectItemAtIndexPath:(NSIndexPath *)arg2;
- (BOOL)collectionOverlay:(_TtC17SketchControllers19MSCollectionOverlay *)arg1 shouldDeselectItemsAtIndexPaths:(NSSet *)arg2;
- (void)collectionOverlay:(_TtC17SketchControllers19MSCollectionOverlay *)arg1 didSelectItemAtIndexPath:(NSIndexPath *)arg2;
- (BOOL)collectionOverlay:(_TtC17SketchControllers19MSCollectionOverlay *)arg1 selectItemAtPoint:(struct CGPoint)arg2 modifierFlags:(unsigned long long)arg3;
@end

