//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/NSObject-Protocol.h>

@class BCOutlineViewDataController, NSArray;

@protocol BCOutlineViewDataControllerDataSource <NSObject>
- (id)rootObject;
- (NSArray *)dataController:(BCOutlineViewDataController *)arg1 childrenOfNode:(id)arg2;
@end

