//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SketchControllers/NSCopying-Protocol.h>

@class MSOverlayPathItem;

@interface MSAlignmentEngineResultGuide : NSObject <NSCopying>
{
    MSOverlayPathItem *_overlayPathItem;
    struct BCLineSegment _lineSegment;
}

@property(retain, nonatomic) MSOverlayPathItem *overlayPathItem; // @synthesize overlayPathItem=_overlayPathItem;
@property(readonly, nonatomic) struct BCLineSegment lineSegment; // @synthesize lineSegment=_lineSegment;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)drawWithLineWidth:(double)arg1;
- (id)bezierPath;
- (id)initWithLineSegment:(struct BCLineSegment)arg1;

@end

