//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSArtboardGroup.h>

@interface MSArtboardGroup (OptimalSize)
+ (struct CGRect)artboardRectFromLayersInArray:(id)arg1;
- (struct CGRect)optimalBoundingBox;
- (BOOL)canCopyToLayer:(id)arg1 beforeLayer:(id)arg2;
- (id)badgeImages;
- (unsigned long long)displayType;
- (id)parentForInsertingLayers;
- (id)displayName;
- (BOOL)canChangeBooleanOperation;
@end

