//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface MSAssistantsService : NSObject
{
    MISSING_TYPE *xpcConnection;
    MISSING_TYPE *assistantsRunner;
}

+ (id)shared;
+ (id)MSAssistantCheckDocumentAutomaticallyKey;
- (void).cxx_destruct;
- (void)runAssistantsWithAssistants:(id)arg1 forDocumentAt:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)init;
- (void)dealloc;

@end

