//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSDictionary, NSURL;

@protocol MSAssistantsRunner
- (void)runAssistantsWithAssistants:(NSDictionary *)arg1 forDocumentAt:(NSURL *)arg2 completionHandler:(void (^)(_TtC10Assistants20AssistantsRunResults *, NSError *))arg3;
@end

