//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MSAttributeConverter : NSObject
{
    NSString *_attributeName;
    CDUnknownBlockType _conversionBlock;
}

+ (id)converterWithAttributeName:(id)arg1 block:(CDUnknownBlockType)arg2;
@property(readonly, copy, nonatomic) CDUnknownBlockType conversionBlock; // @synthesize conversionBlock=_conversionBlock;
@property(readonly, copy, nonatomic) NSString *attributeName; // @synthesize attributeName=_attributeName;
- (void).cxx_destruct;
- (id)convertAttributes:(id)arg1;
- (id)initWithAttributeName:(id)arg1 block:(CDUnknownBlockType)arg2;

@end

