//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSBitmapLayer.h>

@interface MSBitmapLayer (DataApplicable)
- (void)applyData:(id)arg1 fromDataSupplier:(id)arg2 identifier:(id)arg3;
- (BOOL)canChangeBooleanOperation;
@end

