//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/MSToolbarItem.h>

@interface MSButtonToolbarItem : MSToolbarItem
{
}

- (id)toolTip;
- (void)setToolTip:(id)arg1;
- (void)setImage:(id)arg1;
- (id)makeViewForAction:(id)arg1;

@end

