//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/MSLocalDataSupplier.h>

@interface MSBuiltinDataSupplier : MSLocalDataSupplier
{
}

+ (id)sourceURLFromFolderURL:(id)arg1;
+ (id)linkedFolderNameFromFolderURL:(id)arg1;
+ (id)identifierForURL:(id)arg1;
+ (id)imageFileNamesFromFolderURL:(id)arg1;
- (void)makeFolderMonitor;
- (id)initWithCoder:(id)arg1;
- (id)initWithFileSystemURL:(id)arg1;

@end

