//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/NSObject-Protocol.h>

@class NSProgress, SCKOrganization, SCKProject, SCKShare;
@protocol MSCloudUploadProviderDelegate;

@protocol MSCloudUploadProvider <NSObject>
@property(nonatomic, readonly) NSProgress *progress;
- (void)cancel;
@property(nonatomic, readonly) BOOL finalized;
@property(nonatomic, readonly) BOOL cancelled;
@property(nonatomic, readonly) SCKProject *project;
@property(nonatomic, readonly) SCKOrganization *organization;
@property(nonatomic, readonly) SCKShare *createdShare;
@property(nonatomic, readonly) SCKShare *previousShare;
@property(nonatomic, readonly) SCKShare *existingShare;
- (void)startUpload;
@property(nonatomic) __weak id <MSCloudUploadProviderDelegate> delegate;
@end

