//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class MSCloudSharesController, NSArray, NSError;

@protocol MSCloudSharesControllerDelegate
- (void)cloudSharesController:(MSCloudSharesController *)arg1 didFailLoadingWithError:(NSError *)arg2;
- (void)cloudSharesController:(MSCloudSharesController *)arg1 didFinishLoadingShares:(NSArray *)arg2;
- (void)cloudSharesControllerWillStartLoading:(MSCloudSharesController *)arg1;
@end

