//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class SCKShare;

@protocol MSCloudAssetLibraryControllerDelegate
- (void)cloudLibrariesDidFinishUpdate;
- (void)cloudLibrariesWillUpdate;
- (void)updateCloudLibraryShare:(SCKShare *)arg1 editable:(BOOL)arg2;
@end

