//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/MSShapeChange.h>

@interface MSClosePathChange : MSShapeChange
{
}

+ (id)toggleClosePath;
- (id)titleForContext:(id)arg1;
- (BOOL)validateWithContext:(id)arg1;
- (void)closePathWithCurveIfNecessary:(id)arg1;
- (void)executeWithContext:(id)arg1;

@end

