//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/MSMathInspectorValueAdaptor.h>

@interface MSCornerRadiusInspectorValueAdaptor : MSMathInspectorValueAdaptor
{
}

- (id)transformAdaptorValue:(id)arg1 forModel:(id)arg2 context:(id *)arg3 error:(id *)arg4;
- (id)checkAndAdjustValues:(id)arg1 contexts:(id)arg2 withNumberFormatter:(id)arg3 error:(id *)arg4;
- (id)value;
- (id)initWithModelsController:(id)arg1;

@end

