//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/NSObject-Protocol.h>

@class MSColor, MSImmutableColor;

@protocol MSColorConverter <NSObject>
- (BOOL)shouldConvertImmutableColor:(MSImmutableColor *)arg1;
- (BOOL)shouldConvertColor:(MSColor *)arg1;
- (MSImmutableColor *)convertImmutableColor:(MSImmutableColor *)arg1;
- (MSColor *)convertColor:(MSColor *)arg1;
@end

