//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MSDataSupplierManager, MSDocumentData, NSSet, NSString;

@interface MSDataMenuHelper : NSObject
{
    MSDocumentData *_documentData;
    MSDataSupplierManager *_dataManager;
}

@property(readonly, nonatomic) __weak MSDataSupplierManager *dataManager; // @synthesize dataManager=_dataManager;
@property(nonatomic) __weak MSDocumentData *documentData; // @synthesize documentData=_documentData;
- (void).cxx_destruct;
- (void)clearDataIdentifiersOnSelectedLayers;
@property(readonly, nonatomic) BOOL selectedLayersHaveClearableDataIdentifiers;
@property(readonly, nonatomic) NSString *refreshDataText;
@property(readonly, nonatomic) BOOL canRefreshDataOnSelection;
- (void)refreshDataOnSelection;
@property(readonly, nonatomic) NSSet *dataIdentifiersInCurrentSelection;
- (id)dataPointsInLayersOfType:(unsigned long long)arg1 identifier:(id)arg2;
- (id)dataOverridesInInstancesOfType:(unsigned long long)arg1 identifier:(id)arg2;
- (void)applyDataFromSupplier:(id)arg1 toObjects:(id)arg2 identifier:(id)arg3;
- (void)applyDataFromSupplier:(id)arg1 toLayersWithIdentifier:(id)arg2;
- (void)applyDataFromSupplier:(id)arg1;
@property(readonly, nonatomic) unsigned long long applicableDataTypesDataTypeFromCurrentSelection;
- (id)selectedLayers;
- (id)initWithDataManager:(id)arg1;
- (id)init;

@end

