//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface MSDocumentationSearchEntry : NSObject
{
    BOOL _isDuplicateResult;
    NSDictionary *_data;
}

+ (void)markSearchEntriesAsDuplicates:(id)arg1;
+ (id)searchEntryWithDictionary:(id)arg1;
@property BOOL isDuplicateResult; // @synthesize isDuplicateResult=_isDuplicateResult;
@property(copy, nonatomic) NSDictionary *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (void)show;
- (BOOL)matchesSearchQuery:(id)arg1;
- (id)titles;

@end

