//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SketchControllers/NSUserInterfaceItemSearching-Protocol.h>

@class NSArray, NSOperationQueue, NSString;

@interface MSDocumentationSearcher : NSObject <NSUserInterfaceItemSearching>
{
    NSOperationQueue *_queue;
    NSArray *_searchEntries;
}

@property(retain) NSArray *searchEntries; // @synthesize searchEntries=_searchEntries;
@property(retain) NSOperationQueue *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (id)downloadRequest;
- (id)localizedTitlesForItem:(id)arg1;
- (void)performActionForItem:(id)arg1;
- (void)addSearchOperationForItemsWithSearchString:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)addDownloadOperation;
- (void)searchForItemsWithSearchString:(id)arg1 resultLimit:(long long)arg2 matchedItemHandler:(CDUnknownBlockType)arg3;
- (void)documentationMightHaveChanged;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

