//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SketchControllers/MSCloudUploadProvider-Protocol.h>
#import <SketchControllers/NSURLSessionTaskDelegate-Protocol.h>

@class MISSING_TYPE, NSProgress, SCKOrganization, SCKProject, SCKShare;
@protocol MSCloudExportableDocument, MSCloudUploadProviderDelegate;

@interface MSDocumentUpload : NSObject <MSCloudUploadProvider, NSURLSessionTaskDelegate>
{
    MISSING_TYPE *document;
    MISSING_TYPE *delegate;
    MISSING_TYPE *existingShare;
    MISSING_TYPE *previousShare;
    MISSING_TYPE *createdShare;
    MISSING_TYPE *organization;
    MISSING_TYPE *project;
    MISSING_TYPE *cancelled;
    MISSING_TYPE *finalized;
    MISSING_TYPE *progress;
    MISSING_TYPE *progressObserver;
    MISSING_TYPE *operationQueue;
    MISSING_TYPE *versionId;
    MISSING_TYPE *$__lazy_storage_$_urlSession;
}

- (void).cxx_destruct;
- (id)init;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)URLSession:(id)arg1 task:(id)arg2 didSendBodyData:(long long)arg3 totalBytesSent:(long long)arg4 totalBytesExpectedToSend:(long long)arg5;
- (void)cancel;
- (void)startUpload;
- (void)dealloc;
- (id)initWithDocument:(id)arg1 updatingShare:(id)arg2;
@property(nonatomic, readonly) NSProgress *progress; // @synthesize progress;
@property(nonatomic) BOOL finalized; // @synthesize finalized;
@property(nonatomic) BOOL cancelled; // @synthesize cancelled;
@property(nonatomic, retain) SCKProject *project; // @synthesize project;
@property(nonatomic, retain) SCKOrganization *organization; // @synthesize organization;
@property(nonatomic, retain) SCKShare *createdShare; // @synthesize createdShare;
@property(nonatomic, readonly) SCKShare *previousShare; // @synthesize previousShare;
@property(nonatomic, readonly) SCKShare *existingShare; // @synthesize existingShare;
@property(nonatomic, retain) id <MSCloudUploadProviderDelegate> delegate; // @synthesize delegate;
@property(nonatomic) __weak id <MSCloudExportableDocument> document; // @synthesize document;

@end

