//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;
@protocol MSLayerCoordinateSpace;

@interface MSDragInsertionTool : NSObject
{
    MISSING_TYPE *destinationGroup;
    MISSING_TYPE *zoomScale;
    MISSING_TYPE *alignmentSettings;
    MISSING_TYPE *state;
    MISSING_TYPE *position;
    MISSING_TYPE *vector;
    MISSING_TYPE *isAboutCenter;
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic) BOOL insertAboutCenter; // @synthesize insertAboutCenter=isAboutCenter;
@property(nonatomic) struct CGPoint position; // @synthesize position;
@property(nonatomic, readonly) id <MSLayerCoordinateSpace> parentCoordinateSpace;
- (void)updateWithLocation:(struct CGPoint)arg1 lockSize:(BOOL)arg2 alignedAxes:(unsigned long long)arg3;
- (struct CGPoint)locationIn:(id)arg1;
- (void)beginDragging;
- (void)beginDraggingWithLocation:(struct CGPoint)arg1;
@property(nonatomic) double zoomScale; // @synthesize zoomScale;
- (id)initWithDestination:(id)arg1;

@end

