//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/NSObject-Protocol.h>

@class MSGestureRecognizer;

@protocol MSGestureRecognizerDelegate <NSObject>

@optional
- (BOOL)gestureRecognizer:(MSGestureRecognizer *)arg1 shouldAttemptToRecognizeAtPoint:(struct CGPoint)arg2 modifierFlags:(unsigned long long)arg3;
@end

