//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/NSObject-Protocol.h>

@class MSHistory, MSMoment;

@protocol MSHistoryDelegate <NSObject>
- (void)history:(MSHistory *)arg1 didCommitMoment:(MSMoment *)arg2;
@end

