//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class MSLayer, MSPage, NSArray;

@protocol MSHoverableItem
@property(nonatomic, readonly) MSLayer *hoveredLayer;
- (BOOL)matchesLayerListNode:(id)arg1;
- (BOOL)canBeHoveredOnPage:(MSPage *)arg1;
- (NSArray *)hoverItemsWithColor:(struct CGColor *)arg1;
@end

