//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/NSObject-Protocol.h>

@class MSLayer, MSPage, NSData, NSString, NSURL;

@protocol MSImporter <NSObject>
- (MSLayer *)importAsLayer;
- (BOOL)shouldCollapseSinglePage;
- (BOOL)shouldExpandPages;
- (NSString *)secondPhaseSubtitleForValue:(long long)arg1 maximum:(long long)arg2;
- (NSString *)firstPhaseSubtitle;
- (void)finishImporting;
- (void)importIntoPage:(MSPage *)arg1 name:(NSString *)arg2 progress:(void (^)(void))arg3;
- (unsigned long long)prepareToImportFromURL:(NSURL *)arg1 error:(id *)arg2;
- (unsigned long long)prepareToImportFromData:(NSData *)arg1;
@end

