//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/MSObjectCounter.h>

@class MSImageData, NSString;

@interface MSImageCounter : MSObjectCounter
{
    NSString *_sizeString;
}

@property(retain, nonatomic) NSString *sizeString; // @synthesize sizeString=_sizeString;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *title;
@property(readonly, nonatomic) MSImageData *imageData;

@end

