//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSImmutableStyledLayer.h>

#import <SketchControllers/FrequentColorEnumeration-Protocol.h>

@interface MSImmutableStyledLayer (FrequentColors) <FrequentColorEnumeration>
- (void)trackColorsForBasicFill:(id)arg1 enumeratorBlock:(CDUnknownBlockType)arg2;
- (void)enumerateColors:(CDUnknownBlockType)arg1;
@end

