//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSImmutableBitmapLayer.h>

@interface MSImmutableBitmapLayer (LayerList)
- (id)basePreviewImageForTraits:(long long)arg1 inDocument:(id)arg2;
- (id)overridePreviewImageInDocument:(id)arg1;
- (id)previewImageForOverrideManagement;
@end

