//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSImmutableHotspotLayer.h>

@interface MSImmutableHotspotLayer (MSOverrideRepresentationPreview)
- (id)overridePreviewImageInDocument:(id)arg1;
- (void)drawPreviewInRect:(struct CGRect)arg1 bezier:(id)arg2;
- (BOOL)hasDynamicPreview;
- (id)previewImageForOverrideManagement;
@end

