//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSNumberFormatter.h>

@interface MSInspectorNumberFormatter : NSNumberFormatter
{
}

+ (id)standardPercentFormatterWithoutPercentSign;
+ (id)standardPercentFormatter;
+ (id)standardIntegerFormatter;
+ (id)standardPositiveFloatFormatter;
+ (id)standardFloatFormatter;
- (id)stringForObjectValue:(id)arg1;

@end

