//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/MSInspectorPopUpButtonCell.h>

@class NSImage;

@interface MSInspectorPreviewPopupButtonCell : MSInspectorPopUpButtonCell
{
    NSImage *_previewImage;
}

@property(retain, nonatomic) NSImage *previewImage; // @synthesize previewImage=_previewImage;
- (void).cxx_destruct;
- (void)drawImageWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (struct CGRect)imageRectForBounds:(struct CGRect)arg1;

@end

