//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSLayerGroup.h>

@interface MSLayerGroup (LayerList)
- (long long)calculatePreviewIconTraitsForState:(unsigned long long)arg1;
- (BOOL)expandableInLayerList;
- (id)pathForHoverInBounds;
- (void)applyData:(id)arg1 fromDataSupplier:(id)arg2 identifier:(id)arg3;
- (void)prepareAsMaskContainer;
- (id)styleForBooleanOperation;
@end

