//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, MSLayer;

@interface MSLayerPositioningItem : NSObject
{
    MISSING_TYPE *layer;
    MISSING_TYPE *offset;
    MISSING_TYPE *originalParent;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithLayer:(id)arg1 offset:(struct CGVector)arg2;
@property(nonatomic, readonly) struct CGVector offset; // @synthesize offset;
@property(nonatomic, retain) MSLayer *layer; // @synthesize layer;

@end

