//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/MSLayerProtocol-Protocol.h>

@protocol MSLayerDataType <MSLayerProtocol>
@property(readonly, nonatomic) unsigned long long dataType;
@end

