//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/MSLayerPositioningTool.h>

@class NSArray;

@interface MSLayerPositioningTool (SketchControllers)
- (struct CGRect)alignmentRectInCoordinateSpace:(id)arg1 options:(unsigned long long)arg2;
@property(nonatomic, readonly) NSArray *layers;
@end

