//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/NSObject-Protocol.h>

@class MSDocumentData, NSString;

@protocol MSLibraryObject <NSObject>
@property(readonly, nonatomic) BOOL enabled;
@property(readonly, nonatomic) MSDocumentData *document;
@property(readonly, nonatomic) NSString *libraryID;
@property(readonly, nonatomic) NSString *name;
@end

