//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MSMaskWithShape : NSObject
{
}

+ (id)nameForMaskWithLayers:(id)arg1;
+ (id)createMaskWithShapeFromMultipleLayers:(id)arg1;
+ (id)toggleMaskForSingleShape:(id)arg1;
+ (id)createMaskForSingleBitmap:(id)arg1;
+ (id)createMaskWithShapeForLayers:(id)arg1;

@end

