//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSModelObject.h>

@interface MSModelObject (MSPluginDiff)
- (void)pluginDiffCompareChildrenAgainst:(id)arg1 treeComparison:(id)arg2;
@end

