//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/MSOverrideManagementItem.h>

@class NSImage, NSString;

@interface MSOverrideManagementPropertyTitle : MSOverrideManagementItem
{
}

- (unsigned long long)indentationLevel;
@property(readonly, nonatomic) NSImage *previewIcon;
- (id)description;
@property(readonly, nonatomic) NSString *title;
- (id)initWithComplimentaryOverrides:(id)arg1;

@end

