//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MSExportRequest, NSData, NSOperationQueue;

@interface MSPasteboardImageProvider : NSObject
{
    NSOperationQueue *_queue;
    MSExportRequest *_request;
    NSData *_data;
}

+ (void)preparePasteboard:(id)arg1 withExportRequest:(id)arg2;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(copy, nonatomic) MSExportRequest *request; // @synthesize request=_request;
- (void).cxx_destruct;
- (void)pasteboard:(id)arg1 provideDataForType:(id)arg2;
@property(readonly, nonatomic) NSOperationQueue *queue; // @synthesize queue=_queue;

@end

