//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSPath.h>

@interface MSPath (OutlineBorder)
- (id)outlinePathWithBorderPosition:(long long)arg1 lineWidth:(double)arg2 borderOptions:(id)arg3;
- (id)outlinedSubPathWithBorderPosition:(long long)arg1 lineWidth:(double)arg2 borderOptions:(id)arg3 clockwise:(BOOL)arg4;
@end

