//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSString;

@interface MSPluginDataSupplierContext : NSObject
{
    BOOL _isSymbolInstanceOverride;
    NSArray *_items;
    NSString *_key;
}

@property(readonly, nonatomic) NSString *key; // @synthesize key=_key;
@property(readonly, nonatomic) NSArray *items; // @synthesize items=_items;
@property(readonly, nonatomic) BOOL isSymbolInstanceOverride; // @synthesize isSymbolInstanceOverride=_isSymbolInstanceOverride;
- (void).cxx_destruct;
@property(readonly, nonatomic) unsigned long long requestedCount;
@property(readonly, nonatomic) NSDictionary *dictionaryRepresentation;
- (id)initWithOverrides:(id)arg1;
- (id)initWithLayers:(id)arg1;
- (id)initWithIsSymbolInstanceOverride:(BOOL)arg1 items:(id)arg2;

@end

