//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/MSToolbarItem.h>

@class NSColor;

@interface MSPopUpToolbarItem : MSToolbarItem
{
    BOOL _badgeHidden;
    NSColor *_badgeColor;
}

@property(retain, nonatomic) NSColor *badgeColor; // @synthesize badgeColor=_badgeColor;
@property(nonatomic) BOOL badgeHidden; // @synthesize badgeHidden=_badgeHidden;
- (void).cxx_destruct;
- (id)makeViewForAction:(id)arg1;

@end

