//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface MSRulerSnapTargetGenerator : NSObject
{
    MISSING_TYPE *mask;
    MISSING_TYPE *zoomScale;
}

- (id)init;
@property(nonatomic) double zoomScale; // @synthesize zoomScale;
@property(nonatomic) unsigned long long mask; // @synthesize mask;

@end

