//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/MSShareableObjectReference.h>

@class MSStyle;

@interface MSSharedStyleReference : MSShareableObjectReference
{
}

- (id)localLocationPath;
- (BOOL)isEqual:(id)arg1;
@property(readonly, nonatomic) MSStyle *style;
- (id)sharedObjectID;

@end

