//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SketchControllers/NSCopying-Protocol.h>

@class NSArray;

@interface MSShapeChangeContext : NSObject <NSCopying>
{
    NSArray *_layers;
    NSArray *_componentSpecifiers;
}

@property(readonly, copy, nonatomic) NSArray *componentSpecifiers; // @synthesize componentSpecifiers=_componentSpecifiers;
@property(readonly, copy, nonatomic) NSArray *layers; // @synthesize layers=_layers;
- (void).cxx_destruct;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (struct CGRect)rectOfSelectedPoints;
- (id)selectedHandlesSortedByAxis:(unsigned long long)arg1;
- (void)setLocation:(struct CGPoint)arg1 ofHandle:(id)arg2;
- (struct CGPoint)locationOfHandle:(id)arg1 inCoordinateSpace:(id)arg2;
- (id)curvePointAtIndexPath:(id)arg1;
- (void)enumerateCurvePointsUsingBlock:(CDUnknownBlockType)arg1;
@property(readonly, copy, nonatomic) NSArray *orderedComponentSpecifiers;
- (id)initWithLayers:(id)arg1 components:(id)arg2;

@end

