//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/_TtC17SketchControllers35MSCollectionOverlayLayoutAttributes.h>

@class MISSING_TYPE;

@interface MSSpecOverlayLayoutAttributes : _TtC17SketchControllers35MSCollectionOverlayLayoutAttributes
{
    MISSING_TYPE *coordinateSpaceTransform;
    MISSING_TYPE *startpoint;
    MISSING_TYPE *endpoint;
    MISSING_TYPE *displacement;
    MISSING_TYPE *anchorPoint;
}

@end

