//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/_TtC17SketchControllers19MSCollectionOverlay.h>

@class MISSING_TYPE, MSSpecOverlayItemCache, NSColor;

@interface MSSpecOverlay : _TtC17SketchControllers19MSCollectionOverlay
{
    MISSING_TYPE *itemCache;
    MISSING_TYPE *textColor;
    MISSING_TYPE *coordinateSpaceTransform;
    MISSING_TYPE *fontSize;
    MISSING_TYPE *fontWeight;
    MISSING_TYPE *guideColor;
}

- (void).cxx_destruct;
- (id)initWithLayout:(id)arg1;
@property(nonatomic, retain) NSColor *guideColor; // @synthesize guideColor;
@property(nonatomic) struct CGAffineTransform coordinateSpaceTransform; // @synthesize coordinateSpaceTransform;
- (void)bindColorsToUserDefaults;
@property(nonatomic, retain) NSColor *textColor; // @synthesize textColor;
@property(nonatomic, readonly) MSSpecOverlayItemCache *itemCache; // @synthesize itemCache;
- (void)dealloc;
- (id)init;

@end

