//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/MSSpecOverlayItemCache.h>

@interface MSSpecOverlayItemCache (SketchControllers)
- (id)overlayItemContainerForSupplementaryElementOfKind:(id)arg1 layoutAttributes:(id)arg2 parameters:(struct MSRenderingParameters)arg3 in:(id)arg4;
- (id)overlayItemContainerForItemAt:(id)arg1 layoutAttributes:(id)arg2 parameters:(struct MSRenderingParameters)arg3;
@end

