//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/_TtC17SketchControllers25MSCollectionOverlayLayout.h>

@class MISSING_TYPE;

@interface MSSpecOverlayLayout : _TtC17SketchControllers25MSCollectionOverlayLayout
{
    MISSING_TYPE *cache;
}

+ (struct CGRect)spacingRectFromRect:(struct CGRect)arg1 toRect:(struct CGRect)arg2 axis:(unsigned long long)arg3;
+ (struct CGPoint)endpointWithRect:(struct CGRect)arg1 startpoint:(struct CGPoint)arg2 edge:(unsigned int)arg3;
- (void).cxx_destruct;
- (id)init;
- (BOOL)shouldInvalidateLayoutForZoomScaleChange:(double)arg1;
- (id)layoutAttributesForItemAt:(id)arg1;
- (id)layoutAttributesForElementsIn:(struct CGRect)arg1;
- (void)prepareLayout;

@end

