//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchRendering/MSOverlayItemImageCache.h>

@class MISSING_TYPE, NSColor;

@interface MSSpecOverlayItemCache : MSOverlayItemImageCache
{
    MISSING_TYPE *measurementColor;
    MISSING_TYPE *guideColor;
}

- (void).cxx_destruct;
- (id)createOverlayItemImagesForColorSpace:(struct CGColorSpace *)arg1 backingScale:(double)arg2;
@property(nonatomic, retain) NSColor *guideColor; // @synthesize guideColor;
@property(nonatomic, retain) NSColor *measurementColor; // @synthesize measurementColor;
- (void)dealloc;
- (id)init;

@end

