//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSStyleFill.h>

@interface MSStyleFill (Previewing)
- (void)configureFillForPreview:(id)arg1;
- (BOOL)hasEqualAppearance:(id)arg1;
@end

