//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSStylePart.h>

@interface MSStylePart (Previewing)
+ (BOOL)stylesHaveEqualAppearance:(id)arg1;
- (id)previewImageForSize:(struct CGSize)arg1 colorSpace:(id)arg2;
- (void)configureFillForPreview:(id)arg1;
- (BOOL)hasEqualAppearance:(id)arg1;
@end

