//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchControllers/MSTextAttributeRun.h>

@interface MSTextAttributeRun (SketchControllers)
+ (id)gatherRunsOfAttribute:(id)arg1 inLayers:(id)arg2;
+ (id)gatherRunsOfAttribute:(id)arg1 inTextView:(id)arg2 inRanges:(id)arg3;
+ (id)gatherSelectedRunsOfAttribute:(id)arg1 inTextView:(id)arg2;
@end

