//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSDictionary;

@interface MSTextAttributeEditingContext : NSObject
{
    MISSING_TYPE *isFinalized;
    MISSING_TYPE *layerEditStringMap;
    MISSING_TYPE *textViewEditMap;
    MISSING_TYPE *$__lazy_storage_$_defaultTextStyle;
}

- (void).cxx_destruct;
- (id)init;
- (id)attributeRunsForUndoingInTextView:(id)arg1;
- (void)editInBlock:(CDUnknownBlockType)arg1;
@property(nonatomic, copy) NSDictionary *defaultTextStyle;

@end

