//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSSegmentedControl.h>

@class MISSING_TYPE;

@interface MSVerticalOffsetSegmentedControl : NSSegmentedControl
{
    MISSING_TYPE *_contentEdgeInsets;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setContentEdgeInsets:(struct NSEdgeInsets)arg1 forOperatingSystemVersion:(CDStruct_2ec95fd7)arg2 backingScaleFactor:(double)arg3;
- (struct NSEdgeInsets)contentEdgeInsetsFor:(double)arg1;

@end

