//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSControl.h>

@interface NSControl (Inspector)
+ (id)inpectorFocusRingPathForRect:(struct CGRect)arg1 borderRadius:(double)arg2;
+ (id)inpectorBorderPathForRect:(struct CGRect)arg1 borderRadius:(double)arg2;
+ (id)inpectorBorderPathForRectWithMaxRadius:(struct CGRect)arg1;
+ (id)inpectorCheckmarkBorderPathForRect:(struct CGRect)arg1;
+ (id)inpectorFocusRingPathForRect:(struct CGRect)arg1;
+ (id)inpectorBorderPathForRect:(struct CGRect)arg1;
@end

