//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSMenuItem.h>

@class MSDataMenuProvider, MSDataSupplier, NSArray;

@interface NSMenuItem (SharedObjects)
- (BOOL)generatePreviewWithColorSpace:(id)arg1 backingScale:(double)arg2 completionHandler:(CDUnknownBlockType)arg3;
@property(retain, nonatomic) NSArray *shareableObjectReferences;
@property(readonly, nonatomic) NSArray *symbolMasterReferences;
@property(nonatomic) unsigned long long dataSupplierType;
@property(retain, nonatomic) MSDataSupplier *dataSupplier;
- (void)setDataSupplierManager:(id)arg1;
- (id)dataSupplierManager;
@property(retain, nonatomic) MSDataMenuProvider *dataMenuProvider;
- (id)getDataObjectForKey:(id)arg1;
- (void)setDataObject:(id)arg1 forKey:(id)arg2;
@end

