//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class _TtC12BCFoundation7Variant;

@protocol _TtP12BCFoundation22CurrentVariantDelegate_
- (_TtC12BCFoundation7Variant *)currentVariant;
@end

