//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface BCArrayConsolidator : NSObject
{
    CDUnknownBlockType _comparisonBlock;
    CDUnknownBlockType _updateBlock;
    CDUnknownBlockType _createBlock;
    CDUnknownBlockType _postRemoveBlock;
}

@property(copy, nonatomic) CDUnknownBlockType postRemoveBlock; // @synthesize postRemoveBlock=_postRemoveBlock;
@property(copy, nonatomic) CDUnknownBlockType createBlock; // @synthesize createBlock=_createBlock;
@property(copy, nonatomic) CDUnknownBlockType updateBlock; // @synthesize updateBlock=_updateBlock;
@property(copy, nonatomic) CDUnknownBlockType comparisonBlock; // @synthesize comparisonBlock=_comparisonBlock;
- (void).cxx_destruct;

@end

