//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface BCAtomicStack : NSObject
{
    CDStruct_eb6fb79d *_cacheQueueHead;
}

@property(nonatomic) CDStruct_eb6fb79d *cacheQueueHead; // @synthesize cacheQueueHead=_cacheQueueHead;
- (id)pop;
- (void)push:(id)arg1;
- (void)dealloc;
- (id)init;

@end

