//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <BCFoundation/BCComparisonItem.h>

@class NSString;

@interface BCComparisonPropertyChange : BCComparisonItem
{
    NSString *_propertyName;
}

@property(retain, nonatomic) NSString *propertyName; // @synthesize propertyName=_propertyName;
- (void).cxx_destruct;
- (long long)type;
- (id)internalFullPath;

@end

