//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <BCFoundation/BCComparisonItem.h>

@class NSString;

@interface BCComparisonPathItem : BCComparisonItem
{
    NSString *_objectName;
}

+ (id)pathItemWithParent:(id)arg1 newObject:(id)arg2 oldObject:(id)arg3 named:(id)arg4;
@property(retain, nonatomic) NSString *objectName; // @synthesize objectName=_objectName;
- (void).cxx_destruct;
- (id)internalFullPath;

@end

