//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <BCFoundation/BCJSONEncoder.h>

@class NSMutableData;

@interface BCJSONDataEncoder : BCJSONEncoder
{
    NSMutableData *_data;
}

@property(retain, nonatomic) NSMutableData *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (void)writeData:(const void *)arg1 length:(unsigned long long)arg2;
- (id)initWithData:(id)arg1;

@end

