//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class BCReadWriteLock, NSHashTable;

@interface BCObjectPool : NSObject
{
    NSHashTable *_pool;
    unsigned long long _maximumPoolCount;
    BCReadWriteLock *_lock;
    CDUnknownBlockType _creatorBlock;
}

@property(readonly, copy, nonatomic) CDUnknownBlockType creatorBlock; // @synthesize creatorBlock=_creatorBlock;
- (void).cxx_destruct;
@property unsigned long long maximumPoolCount;
- (id)removeAllObjects;
- (void)recycleObject:(id)arg1;
- (id)vendObject;
- (void)dealloc;
- (id)initWithObjectCreatorBlock:(CDUnknownBlockType)arg1;

@end

