//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol NSObject;

@interface BCRangeMapEntry : NSObject
{
    id <NSObject> _object;
    struct _NSRange _range;
}

@property(readonly, nonatomic) id <NSObject> object; // @synthesize object=_object;
@property(readonly, nonatomic) struct _NSRange range; // @synthesize range=_range;
- (void).cxx_destruct;
- (id)initWithObject:(id)arg1 range:(struct _NSRange)arg2;

@end

