//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSMutableIndexSet;

@interface BCRangeMap : NSObject
{
    NSMutableIndexSet *_locations;
    NSMutableDictionary *_locationsToEntries;
}

@property(retain, nonatomic) NSMutableDictionary *locationsToEntries; // @synthesize locationsToEntries=_locationsToEntries;
@property(retain, nonatomic) NSMutableIndexSet *locations; // @synthesize locations=_locations;
- (void).cxx_destruct;
- (void)removeObjectsAtOrBeyondLocation:(unsigned long long)arg1;
- (struct _NSRange)rangeForLocation:(unsigned long long)arg1;
- (id)objectForLocation:(unsigned long long)arg1;
- (void)setObject:(id)arg1 forRange:(struct _NSRange)arg2;
- (id)allObjects;
- (id)allRanges;
- (id)init;

@end

