//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <BCFoundation/NSObject-Protocol.h>

@protocol BCRect <NSObject>
@property(nonatomic) struct CGSize size;
@property(nonatomic) struct CGPoint origin;
@property(nonatomic) double maxY;
@property(nonatomic) double maxX;
@property(nonatomic) double height;
@property(nonatomic) double width;
@property(nonatomic) double y;
@property(nonatomic) double x;
@property(nonatomic) struct CGRect rect;
@end

