//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface BCToolRunner : NSObject
{
}

- (BOOL)validateWorkingDirectoryURL:(id)arg1 error:(id *)arg2;
- (BOOL)validateToolURL:(id)arg1 error:(id *)arg2;
- (void)runToolAtExecutableURL:(id)arg1 workingDirectoryURL:(id)arg2 arguments:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;

@end

