//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <BCFoundation/BCMutableTreeComparison-Protocol.h>

@class BCComparisonItem, NSArray, NSMutableArray;
@protocol BCTreeComparisonDelegate;

@interface BCTreeComparison : NSObject <BCMutableTreeComparison>
{
    NSMutableArray *_mutableChanges;
    id _root1;
    id _root2;
    id <BCTreeComparisonDelegate> _delegate;
    BCComparisonItem *_currentParent;
}

@property(retain, nonatomic) BCComparisonItem *currentParent; // @synthesize currentParent=_currentParent;
@property(nonatomic) __weak id <BCTreeComparisonDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) id root2; // @synthesize root2=_root2;
@property(retain, nonatomic) id root1; // @synthesize root1=_root1;
@property(retain, nonatomic) NSMutableArray *mutableChanges; // @synthesize mutableChanges=_mutableChanges;
- (void).cxx_destruct;
- (void)findCrossArrayMoves;
- (void)compareOldObject:(id)arg1 againstNewObject:(id)arg2 withName:(id)arg3;
- (void)compareOldArray:(id)arg1 againstNewArray:(id)arg2 withName:(id)arg3;
- (void)compareNode:(id)arg1 against:(id)arg2;
@property(readonly, copy, nonatomic) NSArray *changes;
- (id)initWithRoot1:(id)arg1 root2:(id)arg2 delegate:(id)arg3;

@end

