//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <BCFoundation/BCOperation.h>

@class NSURLSession;

@interface BCURLOperation : BCOperation
{
    NSURLSession *_urlSession;
}

+ (id)defaultURLSession;
@property(retain) NSURLSession *urlSession; // @synthesize urlSession=_urlSession;
- (void).cxx_destruct;
- (id)init;

@end

