//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MSRange : NSObject
{
}

+ (void)from:(unsigned long long)arg1 to:(unsigned long long)arg2 do:(CDUnknownBlockType)arg3;

@end

