//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSData.h>

@class NSString;

@interface NSData (BCFoundation)
@property(nonatomic, readonly) NSString *hexString;
@property(readonly, nonatomic) NSString *sha1String_bc;
@property(readonly, nonatomic) NSData *sha1Data_bc;
- (id)sha1AsString;
- (id)sha1;
- (void)encodeAsRAWArchive:(id)arg1;
- (id)dataByDecompressing_bc;
- (id)dataByCompressingWithAlgorithm_bc:(int)arg1;
@end

