//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSMutableDictionary.h>

@interface NSMutableDictionary (BCFoundation)
- (id)objectForKey:(id)arg1 orBySettingMissingObject:(id)arg2;
- (void)addObject:(id)arg1 forKey:(id)arg2;
@end

