//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSURL.h>

@interface NSURL (BCFoundation)
- (BOOL)isSubURLOf:(id)arg1;
- (BOOL)isEqualToFileURL_bc:(id)arg1;
@property(readonly, nonatomic) BOOL isInTrash_bc;
- (id)URLByResolvingSymlinksAndAliases;
- (BOOL)hasExtension:(id)arg1;
- (id)withExtension:(id)arg1;
- (id)URLByAppendingNameWithSeparators:(id)arg1 defaultName:(id)arg2;
- (id)URLByStrippingInvisiblePeriod_bc;
@end

