//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSValue.h>

@interface NSValue (BCJSONEncoder)
+ (id)valueWithBCFloatRange:(CDStruct_c3b9c2ee)arg1;
+ (id)valueWithCGVector:(struct CGVector)arg1;
- (void)encodeAsRAWArchive:(id)arg1;
- (CDStruct_c3b9c2ee)BCFloatRangeValue;
@property(readonly) struct CGVector CGVectorValue;
- (id)initWithJSONDecoder:(id)arg1;
@end

