//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <BCLayerList/NSSearchFieldDelegate-Protocol.h>

@class NSSearchField, NSText;

@protocol BCFilterTextFieldDelegate <NSSearchFieldDelegate>
- (void)filterTextField:(NSSearchField *)arg1 willUseFieldEditor:(NSText *)arg2;
@end

