//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface BCFilterInfo : NSObject
{
    NSString *_filterString;
    unsigned long long _filterTypeMask;
    NSObject *_cacheGeneration;
}

@property(readonly, nonatomic) NSObject *cacheGeneration; // @synthesize cacheGeneration=_cacheGeneration;
@property(nonatomic) unsigned long long filterTypeMask; // @synthesize filterTypeMask=_filterTypeMask;
@property(copy, nonatomic) NSString *filterString; // @synthesize filterString=_filterString;
- (void).cxx_destruct;
- (BOOL)shouldIncludeNode:(id)arg1;
- (BOOL)filterTypeMatchesNode:(id)arg1;
- (BOOL)filterTypeApplies:(unsigned long long)arg1;
@property(readonly, nonatomic) BOOL isActive;
- (void)resetCacheGeneration;
- (id)init;

@end

