//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <BCLayerList/NSOutlineViewDelegate-Protocol.h>

@class BCOutlineView;

@protocol BCOutlineViewDelegate <NSOutlineViewDelegate>
- (BOOL)isOutlineViewShowingContextMenu:(BCOutlineView *)arg1;

@optional
- (void)outlineView:(BCOutlineView *)arg1 disclosureTriangleClickedForItem:(id)arg2;
@end

