//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface BCRowViewVisuals : NSObject
{
    MISSING_TYPE *dimensions;
    MISSING_TYPE *renderer;
    MISSING_TYPE *$__lazy_storage_$_sectionRowBoundsWithBottomBorder;
    MISSING_TYPE *$__lazy_storage_$_sectionRowBoundsWithTopAndBottomBorders;
    MISSING_TYPE *$__lazy_storage_$_plainSectionRowImageWithTopBorder;
    MISSING_TYPE *$__lazy_storage_$_plainSectionRowImageWithBottomBorder;
    MISSING_TYPE *$__lazy_storage_$_plainSectionRowImageWithTopAndBottomBorders;
    MISSING_TYPE *$__lazy_storage_$_highlightedActiveSectionRowImageWithBottomBorder;
    MISSING_TYPE *$__lazy_storage_$_highlightedInactiveSectionRowImageWithBottomBorder;
    MISSING_TYPE *$__lazy_storage_$_highlightedActiveSectionRowImageWithTopAndBottomBorders;
    MISSING_TYPE *$__lazy_storage_$_highlightedInactiveSectionRowImageWithTopAndBottomBorders;
    MISSING_TYPE *$__lazy_storage_$_selectedActiveSectionRowImageWithBottomBorder;
    MISSING_TYPE *$__lazy_storage_$_selectedInactiveSectionRowImageWithBottomBorder;
    MISSING_TYPE *$__lazy_storage_$_selectedActiveSectionRowImageWithTopAndBottomBorders;
    MISSING_TYPE *$__lazy_storage_$_selectedInactiveSectionRowImageWithTopAndBottomBorders;
    MISSING_TYPE *$__lazy_storage_$_groupRowBounds;
    MISSING_TYPE *$__lazy_storage_$_highlightedActiveGroupRowImage;
    MISSING_TYPE *$__lazy_storage_$_highlightedInactiveGroupRowImage;
    MISSING_TYPE *$__lazy_storage_$_selectedActiveGroupRowImageWithBlockyCorners;
    MISSING_TYPE *$__lazy_storage_$_selectedInactiveGroupRowImageWithBlockyCorners;
    MISSING_TYPE *$__lazy_storage_$_selectedActiveGroupRowImageWithRoundCorners;
    MISSING_TYPE *$__lazy_storage_$_selectedInactiveGroupRowImageWithRoundCorners;
    MISSING_TYPE *$__lazy_storage_$_selectedActiveGroupRowImageWithRoundTopCorners;
    MISSING_TYPE *$__lazy_storage_$_selectedInactiveGroupRowImageWithRoundTopCorners;
    MISSING_TYPE *$__lazy_storage_$_selectedActiveGroupRowImageWithRoundBottomCorners;
    MISSING_TYPE *$__lazy_storage_$_selectedInactiveGroupRowImageWithRoundBottomCorners;
    MISSING_TYPE *$__lazy_storage_$_plainGroupRowImageWithTopBorder;
    MISSING_TYPE *$__lazy_storage_$_highlightedActiveGroupRowImageAndTopBorder;
    MISSING_TYPE *$__lazy_storage_$_highlightedInactiveGroupRowImageAndTopBorder;
    MISSING_TYPE *$__lazy_storage_$_selectedActiveGroupRowImageWithRoundCornersAndTopBorder;
    MISSING_TYPE *$__lazy_storage_$_selectedInactiveGroupRowImageWithRoundCornersAndTopBorder;
    MISSING_TYPE *$__lazy_storage_$_regularRowBounds;
    MISSING_TYPE *$__lazy_storage_$_highlightedActiveRegularRowImage;
    MISSING_TYPE *$__lazy_storage_$_highlightedInactiveRegularRowImage;
    MISSING_TYPE *$__lazy_storage_$_selectedActiveRegularRowImageWithBlockyCorners;
    MISSING_TYPE *$__lazy_storage_$_selectedInactiveRegularRowImageWithBlockyCorners;
    MISSING_TYPE *$__lazy_storage_$_selectedActiveRegularRowImageWithRoundCorners;
    MISSING_TYPE *$__lazy_storage_$_selectedInactiveRegularRowImageWithRoundCorners;
    MISSING_TYPE *$__lazy_storage_$_selectedActiveRegularRowImageWithRoundTopCorners;
    MISSING_TYPE *$__lazy_storage_$_selectedInactiveRegularRowImageWithRoundTopCorners;
    MISSING_TYPE *$__lazy_storage_$_selectedActiveRegularRowImageWithRoundBottomCorners;
    MISSING_TYPE *$__lazy_storage_$_selectedInactiveRegularRowImageWithRoundBottomCorners;
    MISSING_TYPE *$__lazy_storage_$_subselectedActiveRegularRowImageWithBlockyCorners;
    MISSING_TYPE *$__lazy_storage_$_subselectedInactiveRegularRowImageWithBlockyCorners;
    MISSING_TYPE *$__lazy_storage_$_subselectedActiveRegularRowImageWithRoundCorners;
    MISSING_TYPE *$__lazy_storage_$_subselectedInactiveRegularRowImageWithRoundCorners;
    MISSING_TYPE *$__lazy_storage_$_subselectedActiveRegularRowImageWithRoundTopCorners;
    MISSING_TYPE *$__lazy_storage_$_subselectedInactiveRegularRowImageWithRoundTopCorners;
    MISSING_TYPE *$__lazy_storage_$_subselectedActiveRegularRowImageWithRoundBottomCorners;
    MISSING_TYPE *$__lazy_storage_$_subselectedInactiveRegularRowImageWithRoundBottomCorners;
}

- (void).cxx_destruct;
- (id)init;
- (void)updateVisualStateOfRowView:(id)arg1;
@property(nonatomic, readonly) double width;
@property(nonatomic, readonly) double scale;
- (id)initWithWidth:(double)arg1 sectionRowHeight:(double)arg2 borderWidth:(double)arg3 groupRowHeight:(double)arg4 regularRowHeight:(double)arg5 scale:(double)arg6;

@end

