//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButton.h>

@class BCSidebarTabButtonCell;
@protocol BCSidebarTabButtonDelegate;

@interface BCSidebarTabButton : NSButton
{
    id <BCSidebarTabButtonDelegate> _delegate;
}

+ (Class)cellClass;
@property(nonatomic) __weak id <BCSidebarTabButtonDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (struct CGSize)intrinsicContentSize;
- (void)drawRect:(struct CGRect)arg1;
@property(nonatomic) BOOL isIndifferent;
@property(nonatomic) BOOL isTabSelected;
@property(readonly, nonatomic) BCSidebarTabButtonCell *tabButtonCell;

@end

