//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSPopUpButtonCell.h>

@interface BCTableCellPopUpButtonCell : NSPopUpButtonCell
{
}

- (void)dismissPopUp;
- (void)attachPopUpWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)nudgeControlView:(id)arg1 by:(double)arg2;

@end

