//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSImage.h>

@interface NSImage (LayerListPreviewIconBadging)
- (id)tintedForLayerListState:(unsigned long long)arg1;
- (id)badgedWithImage:(id)arg1 maskImage:(id)arg2 offset:(struct CGPoint)arg3;
- (id)badgedWithImageNamed:(id)arg1 maskImageNamed:(id)arg2 offset:(struct CGPoint)arg3;
- (id)badgedAs:(unsigned long long)arg1;
@end

