//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchPDF/NSObject-Protocol.h>

@class NSData, NSString, NSURL, PDFScanner;

@protocol PDFParser <NSObject>
- (BOOL)isLocked;
- (NSString *)name;
- (unsigned long long)pageCount;
- (void)parsePastedDocument;
- (void)parseWithProgress:(void (^)(void))arg1;
- (void)loadDocumentFromData:(NSData *)arg1;
- (void)loadDocumentFromURL:(NSURL *)arg1;
- (id)initWithScanner:(PDFScanner *)arg1;
@end

