//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSView.h>

@class MISSING_TYPE;

@interface _TtC8Chocolat19MSKeyEquivalentView : NSView
{
    MISSING_TYPE *keyEquivalents;
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (BOOL)performKeyEquivalent:(id)arg1;
- (void)addTarget:(id)arg1 action:(SEL)arg2 forKeyEquivalent:(id)arg3 modifierMask:(unsigned long long)arg4;

@end

