//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC8Chocolat21MSEmbeddedFontManager : NSObject
{
    MISSING_TYPE *sessionIdentifier;
    MISSING_TYPE *documentIDsByFamilyName;
    MISSING_TYPE *extractedFontURLsByFamilyName;
}

+ (id)shared;
- (void).cxx_destruct;
- (id)init;
- (id)managedFontFamilyNamesForDocumentID:(id)arg1;
- (id)allManagedFontFamilyNames;
- (void)hardReset;
- (void)unregisterDocumentID:(id)arg1;
- (void)registerEmbeddedFontsWithReferences:(id)arg1 forDocumentID:(id)arg2;
- (void)dealloc;

@end

