//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButton.h>

@interface BCFilterTokenButton : NSButton
{
}

+ (id)tokenButtonWithTitle:(id)arg1 tag:(long long)arg2;
- (void)keyDown:(id)arg1;
- (BOOL)resignFirstResponder;

@end

