//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSButtonCell.h>

@interface BCFilterTokenButtonCell : NSButtonCell
{
}

- (void)drawWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (id)attributedTitle;
- (id)backgroundColor;
- (struct CGSize)cellSize;
- (struct CGSize)preferredTextSize;

@end

