//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <BCFoundation/BCJSONDecoder.h>

@interface BCJSONZippedDecoder : BCJSONDecoder
{
    void *_zip;
}

@property(nonatomic) void *zip; // @synthesize zip=_zip;
- (id)decodeFileAtSubpath:(id)arg1 error:(id *)arg2;
- (id)rawDataAtSubpath:(id)arg1 error:(id *)arg2;
- (id)filePathsInSubpath:(id)arg1 error:(id *)arg2;
- (BOOL)containsFileAtSubpath:(id)arg1;
- (void)dealloc;
- (id)initWithURL:(id)arg1;

@end

