//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTableView.h>

@class NSMutableDictionary;

@interface BCKeyEventActionTableView : NSTableView
{
    NSMutableDictionary *_keyEvents;
}

@property(retain, nonatomic) NSMutableDictionary *keyEvents; // @synthesize keyEvents=_keyEvents;
- (void).cxx_destruct;
- (void)keyDown:(id)arg1;
- (void)setTarget:(id)arg1 action:(SEL)arg2 forKeyDownEventWithCharacters:(id)arg3;

@end

