//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSWindow.h>

@interface BCPopoverWindow : NSWindow
{
}

+ (id)attachedWindowWithView:(id)arg1;
- (id)arrowView;
@property(nonatomic) double arrowPosition; // @dynamic arrowPosition;
@property(nonatomic) unsigned long long arrowEdge; // @dynamic arrowEdge;
- (unsigned long long)collectionBehavior;
- (BOOL)canBecomeKeyWindow;
- (void)sendEvent:(id)arg1;
- (void)setFrame:(struct CGRect)arg1 display:(BOOL)arg2 animate:(BOOL)arg3;
- (void)resignMainWindow;
- (id)initWithContentRect:(struct CGRect)arg1;

@end

