//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSTextField.h>

@interface BCZeroHeightWhenEmptyTextField : NSTextField
{
    double _paddingIfNotEmpty;
}

@property(nonatomic) double paddingIfNotEmpty; // @synthesize paddingIfNotEmpty=_paddingIfNotEmpty;
- (struct CGSize)intrinsicContentSize;

@end

