//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Chocolat/MSColorView.h>

@class NSString;

@interface MSThemedColorView : MSColorView
{
    NSString *_colorName;
}

@property(copy, nonatomic) NSString *colorName; // @synthesize colorName=_colorName;
- (void).cxx_destruct;
- (id)color;

@end

