//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSImageView.h>

@class NSString;
@protocol MSThemeImageViewDelegate;

@interface MSThemeImageView : NSImageView
{
    NSString *_imageName;
    id <MSThemeImageViewDelegate> _delegate;
}

@property(nonatomic) __weak id <MSThemeImageViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *imageName; // @synthesize imageName=_imageName;
- (void).cxx_destruct;
- (void)setThemedImage;
- (void)viewDidChangeEffectiveAppearance;

@end

