//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSAlert.h>

@interface NSAlert (Chocolat)
+ (void)runSheetWithMessage:(id)arg1 info:(id)arg2 buttons:(id)arg3;
+ (long long)runModalSessionWithMessage:(id)arg1 info:(id)arg2 buttons:(id)arg3;
+ (long long)runModalWithMessage:(id)arg1 info:(id)arg2 buttons:(id)arg3;
+ (id)alertWithMessage:(id)arg1 info:(id)arg2 buttons:(id)arg3;
@end

