//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSAttributedString.h>

@interface NSAttributedString (CHAttributedStringAdditions)
+ (id)attributedStringWithString:(id)arg1 font:(id)arg2;
+ (id)attributedStringWithString:(id)arg1 attributes:(id)arg2;
- (id)attributedStringWithHighlightColor:(id)arg1;
- (BOOL)attributesMatch:(id)arg1 comparison:(CDUnknownBlockType)arg2;
- (BOOL)attributesMatch:(id)arg1;
- (id)attributeOrNil:(id)arg1 atIndex:(unsigned long long)arg2;
@end

