//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSCell.h>

@interface NSCell (Chocolat)
+ (struct CGRect)drawBaselineAlignedAttributedTitle:(id)arg1 forCell:(id)arg2 controlView:(id)arg3;
- (long long)inheritedBackgroundStyle;
@end

