//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSCursor.h>

@interface NSCursor (CHCursorExtensions)
+ (id)cursorWithImageNamed:(id)arg1 hotSpot:(struct CGPoint)arg2;
+ (id)cursorWithImageNamed:(id)arg1;
@end

