//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSFont.h>

@class NSURL;

@interface NSFont (Chocolat)
+ (BOOL)isEmbeddableFontWithDescriptor:(const struct __CTFontDescriptor *)arg1;
+ (BOOL)isSystemFontWithDescriptor:(const struct __CTFontDescriptor *)arg1;
+ (BOOL)isFontFileRegisteredWithURL:(id)arg1;
+ (id)fileURLWithDescriptor:(const struct __CTFontDescriptor *)arg1;
+ (id)postscriptNameFromDescriptor:(const struct __CTFontDescriptor *)arg1;
+ (BOOL)isTrueTypeOrOpenTypeFontWithDescriptor:(const struct __CTFontDescriptor *)arg1;
+ (id)embeddableFontExtensions;
@property(nonatomic, readonly) BOOL isEmbeddable;
@property(nonatomic, readonly) BOOL isSystemFont;
@property(nonatomic, readonly) NSURL *fileURL;
@end

