//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSMenuItem.h>

@interface NSMenuItem (CHMenuItemAdditions)
+ (id)menuItemWithTruncatedTitle:(id)arg1 target:(id)arg2 action:(SEL)arg3;
+ (id)itemWithTitle:(id)arg1 small:(BOOL)arg2 target:(id)arg3 action:(SEL)arg4;
+ (id)itemWithTitle:(id)arg1 target:(id)arg2 action:(SEL)arg3;
+ (id)itemWithTitle:(id)arg1 action:(SEL)arg2;
- (void)applyBlockToMenuItemAndItemsInSubmenus:(CDUnknownBlockType)arg1;
- (BOOL)isInMainMenu;
- (void)setSmallCenteredFont;
- (void)setSmallFont;
@end

