//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSObject (Chocolat)
- (id)coderSafeVersion_bc;
- (void)removeObserver:(id)arg1 forKeyPaths:(id)arg2;
- (void)addObserver:(id)arg1 forKeyPaths:(id)arg2 options:(unsigned long long)arg3 context:(void *)arg4;
- (void)updateValueViaKVOBindings;
@end

