//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSShadow.h>

@interface NSShadow (CHShadowExtensions)
+ (void)clearShadow;
+ (id)shadowWithColor:(id)arg1 offset:(struct CGSize)arg2 blur:(double)arg3;
@property(nonatomic) double blurRadius;
@property(nonatomic) double offsetY;
@property(nonatomic) double offsetX;
@end

