//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (UIStringDrawingCompatibility)
+ (id)staticColorDictionary;
- (struct CGSize)sizeWithFont:(id)arg1;
- (void)drawCenteredAtPoint:(struct CGPoint)arg1 withFont:(id)arg2 color:(id)arg3;
- (void)drawAtPoint:(struct CGPoint)arg1 withFont:(id)arg2;
- (id)colorFromHSL;
- (id)sRGBColorFromHexColor;
- (id)colorFromHex;
- (id)colorFromRGB:(id)arg1;
- (id)colorValue;
- (id)nonWhitespaceRanges;
- (void)enumerateNonWhitespaceRanges:(CDUnknownBlockType)arg1;
@end

