//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <AppKit/NSViewController.h>

@interface NSViewController (BCPopover)
- (id)presentViewController:(id)arg1 asBCPopoverRelativeToView:(id)arg2 preferredEdge:(unsigned long long)arg3 screenEdgeBehaviour:(long long)arg4;
- (void)addChildViewController:(id)arg1 fittingIntoView:(id)arg2;
- (void)ensureLoaded;
- (id)rootViewController;
- (id)targetViewControllerForAction:(SEL)arg1 sender:(id)arg2;
@end

