//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Chocolat/NSObject-Protocol.h>

@class NSViewController;

@protocol NSViewControllerPresentationAnimator <NSObject>
- (void)animateDismissalOfViewController:(NSViewController *)arg1 fromViewController:(NSViewController *)arg2;
- (void)animatePresentationOfViewController:(NSViewController *)arg1 fromViewController:(NSViewController *)arg2;
@end

