//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface MSGraphQLSubscription : NSObject
{
    MISSING_TYPE *status;
    MISSING_TYPE *socket;
    MISSING_TYPE *request;
    MISSING_TYPE *messageHandler;
    MISSING_TYPE *subscriptions;
    MISSING_TYPE *reconnector;
}

- (void).cxx_destruct;
- (id)init;
- (void)close;
- (void)subscribeWithGraphQL:(id)arg1 errorHandler:(CDUnknownBlockType)arg2 callback:(CDUnknownBlockType)arg3;
- (id)initWithRequest:(id)arg1;
@property(nonatomic) long long status; // @synthesize status;

@end

