//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSArray.h>

@interface NSArray (Parsing)
- (id)cloudObjectsOfType:(Class)arg1 parentObject:(id)arg2;
- (id)signableString;
@end

