//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSData.h>

@class NSString;

@interface NSData (Base64URL)
@property(readonly, nonatomic) NSString *base64URLEncodedString;
- (id)initWithBase64URLEncodedString:(id)arg1;
@end

