//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSError.h>

@class NSArray;

@interface NSError (Cloud)
+ (id)cloudErrorFromAPIResponse_sck:(id)arg1 jsonBody:(id)arg2;
+ (id)cloudErrorFromAPIResponse_sck:(id)arg1 data:(id)arg2;
@property(readonly, nonatomic) NSArray *cloudFields_sck;
@property(readonly, nonatomic) BOOL isURLCancelled_sck;
@property(readonly, nonatomic) BOOL isCloudServerRelated_sck;
@property(readonly, nonatomic) long long cloudCode_sck;
@end

