//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSURL.h>

@class NSString, SCKAPIEnvironment;

@interface NSURL (SketchCloudKit)
+ (id)appcastURLWithShareID:(id)arg1 environment:(id)arg2;
+ (id)cloudShareURLWithShortID:(id)arg1 environment:(id)arg2;
- (id)appendingCloudDeeplinkComponentsToArtboard:(id)arg1 usingPageSelectorComponent:(id)arg2;
- (id)appendingCloudDeeplinkComponentsInPageToArtboard:(id)arg1;
- (id)appendingCloudDeeplinkComponentsToArtboard:(id)arg1;
@property(readonly, nonatomic) NSString *cloudArtboardSlug;
@property(readonly, nonatomic) NSString *cloudArtboardShortID;
@property(readonly, nonatomic) NSString *cloudPageSlug;
@property(readonly, nonatomic) NSString *cloudAppcastIdentifier;
@property(readonly, nonatomic) NSString *cloudShareShortID;
- (id)cloudShareShortIDForEnvironment:(id)arg1;
@property(readonly, nonatomic) NSURL *cloudShareURL;
@property(readonly, nonatomic) BOOL isCloudAppcast;
@property(readonly, nonatomic) BOOL isCloudShare;
@property(readonly, nonatomic) SCKAPIEnvironment *cloudAPIEnvironment;
@property(readonly, nonatomic) NSString *cloudAPIName;
- (id)cloudAPIComponents;
@end

