//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSInputStream, NSOutputStream, NSString, PSWebSocketBuffer;

@interface PSWebSocketServerConnection : NSObject
{
    BOOL _inputStreamOpenCompleted;
    BOOL _outputStreamOpenCompleted;
    NSString *_identifier;
    long long _readyState;
    NSInputStream *_inputStream;
    NSOutputStream *_outputStream;
    PSWebSocketBuffer *_inputBuffer;
    PSWebSocketBuffer *_outputBuffer;
}

@property(retain, nonatomic) PSWebSocketBuffer *outputBuffer; // @synthesize outputBuffer=_outputBuffer;
@property(retain, nonatomic) PSWebSocketBuffer *inputBuffer; // @synthesize inputBuffer=_inputBuffer;
@property(nonatomic) BOOL outputStreamOpenCompleted; // @synthesize outputStreamOpenCompleted=_outputStreamOpenCompleted;
@property(nonatomic) BOOL inputStreamOpenCompleted; // @synthesize inputStreamOpenCompleted=_inputStreamOpenCompleted;
@property(retain, nonatomic) NSOutputStream *outputStream; // @synthesize outputStream=_outputStream;
@property(retain, nonatomic) NSInputStream *inputStream; // @synthesize inputStream=_inputStream;
@property(nonatomic) long long readyState; // @synthesize readyState=_readyState;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (id)init;

@end

