//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchCloudKit/SCKDocumentDiff.h>

@class SCKCloudDocument;

@interface SCKCloudDocumentDiff : SCKDocumentDiff
{
}

- (id)initWithObject:(id)arg1 comparedTo:(id)arg2;

// Remaining properties
@property(nonatomic) unsigned long long attributes; // @dynamic attributes;
@property(readonly, nonatomic) SCKCloudDocument *comparedObject; // @dynamic comparedObject;
@property(readonly, nonatomic) SCKCloudDocument *object; // @dynamic object;

@end

