//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchCloudKit/SCKObject.h>

#import <SketchCloudKit/SCKDiffable-Protocol.h>

@class NSString, SCKLayer;

@interface SCKFlowConnection : SCKObject <SCKDiffable>
{
    BOOL _isBackAction;
    BOOL _maintainScrollPosition;
    struct NSString *_destinationArtboardID;
    NSString *_animationType;
}

@property(readonly, nonatomic) BOOL maintainScrollPosition; // @synthesize maintainScrollPosition=_maintainScrollPosition;
@property(readonly, nonatomic) NSString *animationType; // @synthesize animationType=_animationType;
@property(readonly, nonatomic) NSString *destinationArtboardID; // @synthesize destinationArtboardID=_destinationArtboardID;
@property(readonly, nonatomic) BOOL isBackAction; // @synthesize isBackAction=_isBackAction;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
@property(readonly, nonatomic) SCKLayer *layer;
- (id)dictionaryRepresentation;
- (id)initWithDictionary:(id)arg1;
- (id)diffComparedTo:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

