//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSURL;

@interface SCKFileUploadSpecs : NSObject
{
    NSString *_fileHash;
    NSURL *_uploadURL;
}

@property(readonly, nonatomic) NSURL *uploadURL; // @synthesize uploadURL=_uploadURL;
@property(readonly, nonatomic) NSString *fileHash; // @synthesize fileHash=_fileHash;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

