//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSNumber, NSString;

@interface SCKJWT : NSObject
{
    NSDictionary *_header;
    NSDictionary *_payload;
    NSArray *_components;
}

+ (id)dictionaryFromJWTComponentString:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *components; // @synthesize components=_components;
- (void).cxx_destruct;
- (BOOL)isSignatureValidForPublicKey:(struct __SecKey *)arg1;
@property(readonly, nonatomic) NSString *signature;
@property(readonly, nonatomic) NSDictionary *payload; // @synthesize payload=_payload;
@property(readonly, nonatomic) NSDictionary *header; // @synthesize header=_header;
@property(readonly, nonatomic) NSString *stringValue;
- (id)initWithString:(id)arg1;
- (id)init;
- (BOOL)isSignatureValidForEnvironment:(id)arg1;
@property(readonly, nonatomic) NSString *email;
@property(readonly, nonatomic) NSString *variant;
@property(readonly, nonatomic) NSString *deviceID;
@property(readonly, nonatomic) NSString *sessionID;
@property(readonly, nonatomic) NSNumber *criticalRefreshTime;
@property(readonly, nonatomic) NSNumber *recommendedRefreshTime;
@property(readonly, nonatomic) NSNumber *expirationTime;
@property(readonly, nonatomic) NSNumber *issuedAt;
@property(readonly, nonatomic) NSString *subject;
@property(readonly, nonatomic) NSString *type;
@property(readonly, nonatomic) NSString *algorithm;

@end

