//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchCloudKit/SCKAPIOperation.h>

@class NSArray, SCKAPIURLRequest;

@interface SCKRestAPIOperation : SCKAPIOperation
{
    NSArray *_result;
}

+ (void)executeRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
+ (id)resultOfType:(Class)arg1 fromData:(id)arg2 error:(id *)arg3;
@property(readonly) NSArray *result; // @synthesize result=_result;
- (void).cxx_destruct;
- (id)resultFromData:(id)arg1 error:(id *)arg2;
- (void)processData:(id)arg1 response:(id)arg2 error:(id)arg3;

// Remaining properties
@property(retain, nonatomic) SCKAPIURLRequest *request; // @dynamic request;

@end

