//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchCloudKit/SCKObject.h>

@class NSString, SCKCloudDocument;

@interface SCKShareVersion : SCKObject
{
    unsigned long long _number;
    NSString *_message;
    SCKCloudDocument *_document;
}

@property(readonly, nonatomic) SCKCloudDocument *document; // @synthesize document=_document;
@property(readonly, nonatomic) NSString *message; // @synthesize message=_message;
@property(readonly, nonatomic) unsigned long long number; // @synthesize number=_number;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

