//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchCloudKit/SCKAPIURLRequest.h>

@interface SCKShareAPIURLRequest : SCKAPIURLRequest
{
}

+ (id)shareCancelUpdateRequestWithID:(struct NSString *)arg1;
+ (id)shareDeletionRequestWithID:(struct NSString *)arg1;
+ (id)shareUpdateRequestWithManifest:(id)arg1 existingShare:(id)arg2;
+ (id)shareCreationRequestWithManifest:(id)arg1;
+ (id)userSharesListRequest;
+ (id)shareRequestWithShortID:(struct NSString *)arg1;
+ (id)shareRequestWithID:(struct NSString *)arg1;
+ (id)baseURLForEnvironment:(id)arg1;
- (Class)resultType;

@end

