//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchCloudKit/SCKShare.h>

@class NSArray, NSString;

@interface SCKShareUploadSpecs : SCKShare
{
    NSString *_cloudDocumentID;
    NSArray *_fileUploadSpecs;
}

@property(readonly, nonatomic) NSArray *fileUploadSpecs; // @synthesize fileUploadSpecs=_fileUploadSpecs;
@property(readonly, nonatomic) NSString *cloudDocumentID; // @synthesize cloudDocumentID=_cloudDocumentID;
- (void).cxx_destruct;
- (id)initWithDictionary:(id)arg1;

@end

