//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchCloudKit/SCKObject.h>

@class NSURL;

@interface SCKThumbnail : SCKObject
{
    NSURL *_URL;
    unsigned long long _fileSize;
    struct CGSize _dimensions;
}

@property(readonly, nonatomic) unsigned long long fileSize; // @synthesize fileSize=_fileSize;
@property(readonly, nonatomic) struct CGSize dimensions; // @synthesize dimensions=_dimensions;
@property(readonly, nonatomic) NSURL *URL; // @synthesize URL=_URL;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (id)initWithDictionary:(id)arg1;

@end

