//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface SCKUserNotificationsController : NSObject
{
    MISSING_TYPE *subscription;
}

+ (id)notificationKey;
+ (id)didReceiveNotification;
- (void).cxx_destruct;
- (void)apiSessionDidChange:(id)arg1;
- (id)init;

@end

