//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSSet;

@interface _TtC13SharedEditing21MSPatchChangeManifest : NSObject
{
    MISSING_TYPE *addedPages;
    MISSING_TYPE *removedPages;
    MISSING_TYPE *changedPages;
    MISSING_TYPE *unchangedPages;
    MISSING_TYPE *addedArtboards;
    MISSING_TYPE *removedArtboards;
    MISSING_TYPE *changedArtboards;
    MISSING_TYPE *unchangedArtboards;
    MISSING_TYPE *affectedPages;
    MISSING_TYPE *affectedArtboards;
}

- (void).cxx_destruct;
- (id)init;
@property(nonatomic, copy) NSSet *affectedArtboards;
@property(nonatomic, copy) NSSet *affectedPages;
@property(nonatomic, copy) NSSet *unchangedArtboards;
@property(nonatomic, copy) NSSet *changedArtboards;
@property(nonatomic, copy) NSSet *removedArtboards;
@property(nonatomic, copy) NSSet *addedArtboards;
@property(nonatomic, copy) NSSet *unchangedPages;
@property(nonatomic, copy) NSSet *changedPages;
@property(nonatomic, copy) NSSet *removedPages;
@property(nonatomic, copy) NSSet *addedPages;

@end

