//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SharedEditing/_TtC13SharedEditing21MSPatchChangeManifest.h>

@interface _TtC13SharedEditing21MSPatchChangeManifest (SharedEditing)
+ (id)loadFromJSON:(id)arg1;
- (id)toJSON;
@end

