//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SharedEditing/_TtC13SharedEditing21MSPatchChangeManifest.h>

@class MISSING_TYPE;

@interface _TtC13SharedEditing28MSPatchChangeManifestBuilder : _TtC13SharedEditing21MSPatchChangeManifest
{
    MISSING_TYPE *doc;
    MISSING_TYPE *originalDocument;
}

- (void).cxx_destruct;
- (id)init;
- (void)buildManifest;
- (id)initWithDocument:(id)arg1;

@end

