//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class MSBaseArchiver, MSBaseUnarchiver, NSString;

@protocol MSCoding
- (id)initWithUnarchiver:(MSBaseUnarchiver *)arg1;
- (void)encodeWithArchiver:(MSBaseArchiver *)arg1;

@optional
@property(readonly, nonatomic) NSString *archiveReferenceIdentifier_bc;
- (id)initWithUnarchiver:(MSBaseUnarchiver *)arg1 migratingFrom:(long long)arg2 toVersion:(long long)arg3;
@end

