//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SharedEditing/MSPatchOperation.h>

@class MSModelObject, MSPatchArrayAddPosition, MSPatchArrayRemovePosition;

@interface MSMoveArrayItemPatchOperation : MSPatchOperation
{
    MSPatchArrayRemovePosition *_fromPosition;
    MSPatchArrayAddPosition *_toPosition;
    MSModelObject *_removedObject;
}

@property(retain, nonatomic) MSModelObject *removedObject; // @synthesize removedObject=_removedObject;
@property(readonly, nonatomic) MSPatchArrayAddPosition *toPosition; // @synthesize toPosition=_toPosition;
@property(readonly, nonatomic) MSPatchArrayRemovePosition *fromPosition; // @synthesize fromPosition=_fromPosition;
- (void).cxx_destruct;
- (long long)compare:(id)arg1;
- (unsigned long long)traits;
- (id)removalPosition;
- (id)insertionPosition;
- (unsigned long long)applyInsertionToDocument:(id)arg1;
- (unsigned long long)applyRemovalToDocument:(id)arg1;
- (id)initWithUnarchiver:(id)arg1;
- (void)encodeWithArchiver:(id)arg1;
- (id)initWithComparisonItem:(id)arg1;

@end

