//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SharedEditing/MSCoding-Protocol.h>

@class NSString;

@interface MSPatchArrayRemovePosition : NSObject <MSCoding>
{
    NSString *_objectID;
}

@property(readonly, nonatomic) NSString *objectID; // @synthesize objectID=_objectID;
- (void).cxx_destruct;
- (id)applyRemovalToDocument:(id)arg1;
- (id)initWithUnarchiver:(id)arg1;
- (void)encodeWithArchiver:(id)arg1;
- (void)encodeAsJSON:(id)arg1;
- (id)initWithArrayChangeItem:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) NSString *archiveReferenceIdentifier_bc;

@end

