//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SharedEditing/MSCoding-Protocol.h>

@class NSString;

@interface MSPatchArrayAddPosition : NSObject <MSCoding>
{
    NSString *_parentID;
    NSString *_propertyName;
    unsigned long long _index;
}

@property(readonly, nonatomic) unsigned long long index; // @synthesize index=_index;
@property(readonly, nonatomic) NSString *propertyName; // @synthesize propertyName=_propertyName;
@property(readonly, nonatomic) NSString *parentID; // @synthesize parentID=_parentID;
- (void).cxx_destruct;
- (long long)compare:(id)arg1;
- (unsigned long long)insertObject:(id)arg1 withDocument:(id)arg2;
- (id)initWithUnarchiver:(id)arg1;
- (void)encodeWithArchiver:(id)arg1;
- (void)encodeAsJSON:(id)arg1;
- (id)initWithArrayChangeItem:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) NSString *archiveReferenceIdentifier_bc;

@end

