//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class BCReadWriteLock, NSArray, NSMutableArray;
@protocol MSCoding;

@interface MSPatchContainer : NSObject
{
    BCReadWriteLock *_locker;
    NSMutableArray *_localPatches;
    id <MSCoding> _statusInfo;
}

@property(retain) id <MSCoding> statusInfo; // @synthesize statusInfo=_statusInfo;
- (void).cxx_destruct;
- (void)deletePatch:(id)arg1;
- (id)objectForKeyedSubscript:(id)arg1;
- (void)addPatch:(id)arg1;
- (id)patchWithID:(id)arg1 inArray:(id)arg2;
- (void)removePatchWithID:(id)arg1 fromArray:(id)arg2;
- (unsigned long long)indexOfPatchWithID:(id)arg1 inArray:(id)arg2;
@property(readonly, nonatomic) NSArray *localPatches;
- (id)init;
- (id)initWithPatches:(id)arg1;

@end

