//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchMirrorServerKit/NSObject-Protocol.h>

@class GCDWebServer;

@protocol GCDWebServerDelegate <NSObject>

@optional
- (void)webServerDidStop:(GCDWebServer *)arg1;
- (void)webServerDidDisconnect:(GCDWebServer *)arg1;
- (void)webServerDidConnect:(GCDWebServer *)arg1;
- (void)webServerDidUpdateNATPortMapping:(GCDWebServer *)arg1;
- (void)webServerDidCompleteBonjourRegistration:(GCDWebServer *)arg1;
- (void)webServerDidStart:(GCDWebServer *)arg1;
@end

