//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSNetService.h>

@class NSArray;

@interface NSNetService (SMKWebConnection)
+ (id)addressStringWithData:(id)arg1;
@property(readonly, nonatomic) NSArray *addressStrings;
@end

