//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SketchMirrorServerKit/SMKMessageCoding-Protocol.h>

@class NSDictionary, NSString;

@interface SMKArtboardMessageContent : NSObject <SMKMessageCoding>
{
    NSString *_identifier;
    struct CGSize _constrainingSize;
    struct CGRect _rect;
}

@property(nonatomic) struct CGSize constrainingSize; // @synthesize constrainingSize=_constrainingSize;
@property(nonatomic) struct CGRect rect; // @synthesize rect=_rect;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSDictionary *dictionaryRepresentation;
- (id)initWithDictionary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

