//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchMirrorServerKit/NSObject-Protocol.h>

@class NSArray, NSData, SMKConnectionInfo;

@protocol SMKCommunicationResponseInterface <NSObject>
- (void)connectionInfo:(SMKConnectionInfo *)arg1 didReceiveData:(NSData *)arg2;
- (void)connectionAdvertisementDidChange:(SMKConnectionInfo *)arg1;
- (void)connectionStatusDidChange:(SMKConnectionInfo *)arg1;
- (void)connectionInfoDidChange:(NSArray *)arg1;
@end

