//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSFileManager;
@protocol OS_dispatch_queue, SMKDiskCacheDelegate;

@interface SMKDiskCache : NSObject
{
    id <SMKDiskCacheDelegate> _delegate;
    NSObject<OS_dispatch_queue> *_queue;
    NSFileManager *_fileManager;
}

@property(retain) NSFileManager *fileManager; // @synthesize fileManager=_fileManager;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(nonatomic) __weak id <SMKDiskCacheDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;
- (id)objectForKeyedSubscript:(id)arg1;
- (BOOL)containsObjectForKey:(id)arg1;
- (id)filePathForKey:(id)arg1;
- (id)fileNameForKey:(id)arg1;
- (void)removeCacheDirectory;
- (void)createCacheDirectory;
- (void)applicationWillTerminateNotification:(id)arg1;
- (void)dealloc;
- (id)initWithQOS:(unsigned int)arg1;
- (id)init;

@end

