//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SketchMirrorServerKit/SMKMessageCoding-Protocol.h>

@class NSData, NSDictionary, NSString;
@protocol SMKMessageCoding;

@interface SMKMessage : NSObject <SMKMessageCoding>
{
    NSString *_type;
    id <SMKMessageCoding> _content;
}

+ (Class)classForType:(id)arg1;
+ (id)messageFromData:(id)arg1;
@property(retain, nonatomic) id <SMKMessageCoding> content; // @synthesize content=_content;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)initWithType:(id)arg1;
@property(readonly, nonatomic) Class contentClass;
@property(readonly, nonatomic) NSDictionary *dictionaryRepresentation;
- (id)initWithDictionary:(id)arg1;
@property(readonly, nonatomic) NSData *messageData;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

