//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SketchMirrorServerKit/NSSecureCoding-Protocol.h>

@class NSData, NSError, NSURLRequest, NSURLResponse;

@interface SMKURLResponse : NSObject <NSSecureCoding>
{
    NSURLRequest *_request;
    NSURLResponse *_response;
    NSData *_data;
    NSError *_error;
}

+ (BOOL)supportsSecureCoding;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(retain, nonatomic) NSURLResponse *response; // @synthesize response=_response;
@property(retain, nonatomic) NSURLRequest *request; // @synthesize request=_request;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

