//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class MISSING_TYPE;

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct BCEdgePaddings {
    double maxYEdge;
    double minXEdge;
    double minYEdge;
    double maxXEdge;
};

struct BCLine {
    double _field1;
    double _field2;
    double _field3;
};

struct CGAffineTransform {
    double a;
    double b;
    double c;
    double d;
    double tx;
    double ty;
};

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    double width;
    double height;
};

struct CGVector {
    double dx;
    double dy;
};

struct MSArcVertex {
    union {
        struct {
            float _field1;
            float _field2;
        } _field1;
    } _field1;
};

struct MSFlowEndpoint {
    unsigned long long edge;
    struct CGRect rect;
};

struct MSFlowInfo {
    struct MSFlowEndpoint from;
    struct MSFlowEndpoint to;
    long long type;
};

struct MSRenderingParameters {
    struct CGRect pageRect;
    double zoomLevel;
    double backingScale;
    struct CGSize pixelSize;
    unsigned long long options;
};

struct MSTextureVertex;

struct MSTextureVertexQuad {
    union {
        struct {
            struct MSTextureVertex _field1;
            struct MSTextureVertex _field2;
            struct MSTextureVertex _field3;
            struct MSTextureVertex _field4;
        } _field1;
        struct MSTextureVertex _field2[4];
    } _field1;
};

struct _NSRange {
    unsigned long long _field1;
    unsigned long long _field2;
};

struct _opaque_pthread_mutex_t {
    long long __sig;
    char __opaque[56];
};

#pragma mark Typedef'd Structures

typedef struct {
    MISSING_TYPE *_field1[4];
} CDStruct_f1db2b5e;

typedef struct {
    float red;
    float green;
    float blue;
    float alpha;
} CDStruct_0b1c536a;

typedef struct {
    int x;
    int y;
    int width;
    int height;
} CDStruct_bf95b13b;

typedef struct {
    int x;
    int y;
} CDStruct_ffe6b7c1;

typedef struct CDStruct_183601bc;

typedef struct {
    unsigned int _field1;
    unsigned int _field2;
    CDStruct_183601bc *_field3;
} CDStruct_3b01f0aa;

typedef struct {
    CDStruct_183601bc *_field1;
    unsigned int _field2;
    unsigned int _field3;
} CDStruct_e817f9f7;

typedef struct {
    CDStruct_bf95b13b _field1;
    CDStruct_183601bc *_field2;
} CDStruct_75f85af1;

typedef struct {
    struct CGRect _field1;
    char _field2;
} CDStruct_3f22a1f4;

