//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

#import <SketchRendering/MSBackgroundBlurRenderer-Protocol.h>

@class NSString;

@interface MSBackgroundBlurRendererCG : NSObject <MSBackgroundBlurRenderer>
{
}

- (void)renderDocumentContentUnderLayer:(id)arg1 inContext:(struct CGContext *)arg2 rect:(struct CGRect)arg3 scale:(double)arg4 forRenderingContext:(id)arg5;
- (void)renderBackgroundBlurBehindLayer:(id)arg1 context:(id)arg2 clippedToPath:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

