//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MSCachedShadowMask : NSObject
{
    struct CGImage *_image;
    struct CGRect _drawingRect;
}

@property(readonly, nonatomic) struct CGRect drawingRect; // @synthesize drawingRect=_drawingRect;
@property(readonly, nonatomic) struct CGImage *image; // @synthesize image=_image;
- (void)dealloc;
- (id)initWithCGImage:(struct CGImage *)arg1 drawingRect:(struct CGRect)arg2;

@end

