//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchRendering/NSObject-Protocol.h>

@class MSCloudManifestMaker, NSDictionary, _TtC11SketchModel24MSImmutableLayerAncestry;

@protocol MSCloudManifestMakerDelegate <NSObject>
- (NSDictionary *)cloudManifestMaker:(MSCloudManifestMaker *)arg1 fileMetadataForAncestry:(_TtC11SketchModel24MSImmutableLayerAncestry *)arg2 layerBehavior:(unsigned long long)arg3 atScale:(double)arg4;
@end

