//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchRendering/NSObject-Protocol.h>

@class MSImmutableDocumentData, NSData, NSDictionary, NSMutableDictionary;

@protocol MSDocumentTextPreviews <NSObject>
- (NSData *)createPreviewMetadataForTextLayers:(NSDictionary *)arg1 pageMapping:(NSDictionary *)arg2;
- (NSData *)createPreviewPDFDataForTextLayers:(NSDictionary *)arg1 document:(MSImmutableDocumentData *)arg2 pageMapping:(NSMutableDictionary *)arg3;
@end

