//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSDocumentWriter.h>

#import <SketchRendering/MSDocumentPreviewGeneration-Protocol.h>
#import <SketchRendering/MSDocumentTextPreviews-Protocol.h>

@class NSString;

@interface MSDocumentWriter (PreviewGeneration) <MSDocumentPreviewGeneration, MSDocumentTextPreviews>
+ (id)findLibraryPreviewArtboardForDocument:(id)arg1 outPage:(id *)arg2;
+ (id)previewImageForDocument:(id)arg1 page:(id)arg2 rect:(struct CGRect)arg3;
+ (id)generatePreviewsForDocument:(id)arg1;
- (id)createPreviewMetadataForTextLayers:(id)arg1 pageMapping:(id)arg2;
- (id)createPreviewPDFDataForTextLayers:(id)arg1 document:(id)arg2 pageMapping:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

