//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchRendering/MSRenderer-Protocol.h>

@class MSImmutableStyleFill, MSImmutableStyledLayer, MSPath, MSRenderingContext;

@protocol MSFillRenderer <MSRenderer>
- (void)renderFill:(MSImmutableStyleFill *)arg1 path:(MSPath *)arg2 layer:(MSImmutableStyledLayer *)arg3 index:(long long)arg4 rect:(struct CGRect)arg5 hasInnerStroke:(BOOL)arg6 context:(MSRenderingContext *)arg7;
@end

