//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class MSArcVertexBuffer, MSFlowItem;

@interface MSFlowItemBufferOperation : NSOperation
{
    BOOL _clipToArtboards;
    MSFlowItem *_item;
    double _zoomLevel;
    MSArcVertexBuffer *_buffer;
}

@property(readonly, nonatomic) MSArcVertexBuffer *buffer; // @synthesize buffer=_buffer;
@property(readonly, nonatomic) double zoomLevel; // @synthesize zoomLevel=_zoomLevel;
@property(readonly, nonatomic) BOOL clipToArtboards; // @synthesize clipToArtboards=_clipToArtboards;
@property(readonly, nonatomic) MSFlowItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)main;
- (id)segmentsByClippingSegment:(id)arg1 toRects:(id)arg2;
- (id)initWithFlowItem:(id)arg1 clipToArtboards:(BOOL)arg2 zoomLevel:(double)arg3;

@end

