//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSImmutableStyledLayer.h>

@interface MSImmutableStyledLayer (BlurEffect)
- (id)renderBitmapEffects:(id)arg1;
- (id)strokeStyleForDecoratedPath;
- (id)fillStyleForDecoratedPath;
- (id)fillPathWithDecorations:(id *)arg1;
- (BOOL)shouldSkipDrawingInContext:(id)arg1;
- (BOOL)shouldRenderInTransparencyLayer;
@property(readonly, nonatomic) BOOL shouldRasterize;
- (void)prepareDrawingInContext:(id)arg1 inBlock:(CDUnknownBlockType)arg2;
@end

