//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSImmutableStyleBorder.h>

@interface MSImmutableStyleBorder (Rendering)
- (void)drawGradientBorder:(id)arg1 advancedOptions:(id)arg2 originalPath:(id)arg3 isArtistic:(BOOL)arg4 frame:(struct CGRect)arg5 context:(id)arg6;
- (void)drawBorder:(id)arg1 advancedOptions:(id)arg2 applyClip:(BOOL)arg3 context:(id)arg4;
@end

