//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchModel/MSImmutableLayer.h>

@interface MSImmutableLayer (CoreImageEffects)
- (id)renderBitmapEffects:(id)arg1;
- (BOOL)shouldSkipDrawingInContext:(id)arg1;
- (unsigned long long)transparencyLayerUseRectCondition;
- (BOOL)shouldRenderInTransparencyLayer;
- (void)prepareForRender:(id)arg1;
- (void)gatherForRenderPreparation:(id)arg1;
- (void)configureBackgroundOfRequest:(id)arg1 isContainedInGroup:(BOOL)arg2;
- (void)renderToCanvas:(struct EKRasterCanvasStruct *)arg1;
@end

