//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@protocol MTLTexture;

@interface MSMetalTexture : NSObject
{
    id <MTLTexture> _metalTexture;
}

@property(retain, nonatomic) id <MTLTexture> metalTexture; // @synthesize metalTexture=_metalTexture;
- (void).cxx_destruct;
- (unsigned long long)height;
- (unsigned long long)width;
- (void)replaceRegion:(CDStruct_bf95b13b)arg1 bytesPerRow:(unsigned long long)arg2 pixels:(const void *)arg3;
- (id)initWithMetalTexture:(id)arg1;

@end

