//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class CAMetalLayer, MSArcVertexBuffer, MSTextureVertexBuffer;
@protocol CAMetalDrawable, MTLBuffer, MTLCommandBuffer, MTLCommandQueue, MTLDepthStencilState, MTLLibrary, MTLRenderPipelineState, MTLTexture;

@interface MSMetalRenderer : NSObject
{
    BOOL _hasScissor;
    BOOL _drawing;
    CAMetalLayer *_metalLayer;
    id <MTLCommandBuffer> _currentCommands;
    id <CAMetalDrawable> _currentDrawable;
    id <MTLLibrary> _metalLibrary;
    id <MTLCommandQueue> _metalCommandQueue;
    id <MTLRenderPipelineState> _drawTextureState;
    id <MTLRenderPipelineState> _drawTextureNearestState;
    id <MTLRenderPipelineState> _drawColorQuadState;
    id <MTLRenderPipelineState> _drawArcVertexBufferState;
    id <MTLRenderPipelineState> _drawTextureVertexBufferState;
    id <MTLRenderPipelineState> _drawColorQuadWithStencilState;
    id <MTLDepthStencilState> _disableOverlappingTriangleBlendingState;
    id <MTLTexture> _stencilTexture;
    MSArcVertexBuffer *_arcVertexBuffer;
    MSTextureVertexBuffer *_textureVertexBuffer;
    id <MTLBuffer> _arcVerticesBuffer;
    id <MTLBuffer> _arcIndexesBuffer;
    id <MTLBuffer> _textureVerticesBuffer;
    id <MTLBuffer> _textureIndexesBuffer;
    CDUnknownBlockType _drawCompletionHandler;
    CDStruct_bf95b13b _scissorRect;
    struct _opaque_pthread_mutex_t _textureLock;
}

+ (id)createWithCompletionHandler:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) struct _opaque_pthread_mutex_t textureLock; // @synthesize textureLock=_textureLock;
@property(getter=isDrawing) BOOL drawing; // @synthesize drawing=_drawing;
@property(copy, nonatomic) CDUnknownBlockType drawCompletionHandler; // @synthesize drawCompletionHandler=_drawCompletionHandler;
@property(retain, nonatomic) id <MTLBuffer> textureIndexesBuffer; // @synthesize textureIndexesBuffer=_textureIndexesBuffer;
@property(retain, nonatomic) id <MTLBuffer> textureVerticesBuffer; // @synthesize textureVerticesBuffer=_textureVerticesBuffer;
@property(retain, nonatomic) id <MTLBuffer> arcIndexesBuffer; // @synthesize arcIndexesBuffer=_arcIndexesBuffer;
@property(retain, nonatomic) id <MTLBuffer> arcVerticesBuffer; // @synthesize arcVerticesBuffer=_arcVerticesBuffer;
@property(retain, nonatomic) MSTextureVertexBuffer *textureVertexBuffer; // @synthesize textureVertexBuffer=_textureVertexBuffer;
@property(retain, nonatomic) MSArcVertexBuffer *arcVertexBuffer; // @synthesize arcVertexBuffer=_arcVertexBuffer;
@property(nonatomic) CDStruct_bf95b13b scissorRect; // @synthesize scissorRect=_scissorRect;
@property(nonatomic) BOOL hasScissor; // @synthesize hasScissor=_hasScissor;
@property(retain, nonatomic) id <MTLTexture> stencilTexture; // @synthesize stencilTexture=_stencilTexture;
@property(retain, nonatomic) id <MTLDepthStencilState> disableOverlappingTriangleBlendingState; // @synthesize disableOverlappingTriangleBlendingState=_disableOverlappingTriangleBlendingState;
@property(retain, nonatomic) id <MTLRenderPipelineState> drawColorQuadWithStencilState; // @synthesize drawColorQuadWithStencilState=_drawColorQuadWithStencilState;
@property(retain, nonatomic) id <MTLRenderPipelineState> drawTextureVertexBufferState; // @synthesize drawTextureVertexBufferState=_drawTextureVertexBufferState;
@property(retain, nonatomic) id <MTLRenderPipelineState> drawArcVertexBufferState; // @synthesize drawArcVertexBufferState=_drawArcVertexBufferState;
@property(retain, nonatomic) id <MTLRenderPipelineState> drawColorQuadState; // @synthesize drawColorQuadState=_drawColorQuadState;
@property(retain, nonatomic) id <MTLRenderPipelineState> drawTextureNearestState; // @synthesize drawTextureNearestState=_drawTextureNearestState;
@property(retain, nonatomic) id <MTLRenderPipelineState> drawTextureState; // @synthesize drawTextureState=_drawTextureState;
@property(retain, nonatomic) id <MTLCommandQueue> metalCommandQueue; // @synthesize metalCommandQueue=_metalCommandQueue;
@property(retain, nonatomic) id <MTLLibrary> metalLibrary; // @synthesize metalLibrary=_metalLibrary;
@property(retain, nonatomic) id <CAMetalDrawable> currentDrawable; // @synthesize currentDrawable=_currentDrawable;
@property(retain, nonatomic) id <MTLCommandBuffer> currentCommands; // @synthesize currentCommands=_currentCommands;
@property(retain, nonatomic) CAMetalLayer *metalLayer; // @synthesize metalLayer=_metalLayer;
- (void).cxx_destruct;
- (CDStruct_ffe6b7c1)maximumTextureSize;
- (void)unlockTextures;
- (void)lockTextures;
- (id)layer;
- (id)createBufferWithBytes:(const void *)arg1 length:(unsigned long long)arg2 count:(unsigned long long)arg3;
- (id)createTextureWithWidth:(unsigned long long)arg1 height:(unsigned long long)arg2;
- (void)endFrameAndWaitForFrame:(BOOL)arg1;
- (BOOL)beginFrameWithClearColor:(CDStruct_0b1c536a)arg1 drawableSize:(struct CGSize)arg2 backingScaleFactor:(double)arg3 colorSpace:(struct CGColorSpace *)arg4;
- (void)resetScissorRect;
- (void)setScissorRectWithX:(int)arg1 y:(int)arg2 width:(int)arg3 height:(int)arg4;
- (void)drawTextureVertexBuffer:(id)arg1 sourceTexture:(id)arg2 modelViewTransform:(struct CGAffineTransform)arg3;
- (void)drawArcVertexBuffer:(id)arg1 color:(const CDStruct_0b1c536a *)arg2 modelViewTransform:(struct CGAffineTransform)arg3 backingScale:(double)arg4;
- (void)drawTexturedQuadInDestinationRect:(struct CGRect)arg1 sourceTexture:(id)arg2 sourceRect:(struct CGRect)arg3 bilinearFilter:(BOOL)arg4;
- (void)drawTexturedQuadInDestinationRect:(struct CGRect)arg1 sourceTexture:(id)arg2 bilinearFilter:(BOOL)arg3;
- (void)drawTexturedTriangleMeshFromBuffer:(id)arg1 modelViewTransform:(struct CGAffineTransform)arg2 sourceTexture:(id)arg3;
- (void)drawTexturedTriangleMesh:(const CDStruct_e817f9f7 *)arg1 sourceTexture:(id)arg2;
- (void)drawColorTriangleMeshFromBuffer:(id)arg1 modelViewMatrix:(CDStruct_f1db2b5e)arg2 projectionMatrix:(CDStruct_f1db2b5e)arg3 disableOverlappingFragmentBlending:(BOOL)arg4;
- (void)drawColorTriangleMesh:(const CDStruct_e817f9f7 *)arg1 modelViewMatrix:(CDStruct_f1db2b5e)arg2 projectionMatrix:(CDStruct_f1db2b5e)arg3 disableOverlappingFragmentBlending:(BOOL)arg4;
- (id)ms_createStencilTextureForColorAttachment:(id)arg1;
- (void)drawColorTriangleMeshFromBuffer:(id)arg1 modelViewTransform:(struct CGAffineTransform)arg2 disableOverlappingFragmentBlending:(BOOL)arg3;
- (void)drawColorTriangleMesh:(const CDStruct_e817f9f7 *)arg1 modelViewTransform:(struct CGAffineTransform)arg2 disableOverlappingFragmentBlending:(BOOL)arg3;
- (void)drawColorQuadInRect:(struct CGRect)arg1 color:(CDStruct_0b1c536a)arg2;
- (void)_setupScissorRect:(id)arg1 forTargetTexture:(id)arg2;
- (void)dealloc;
- (id)initWithCompletionHandler:(CDUnknownBlockType)arg1 device:(id)arg2;

@end

