//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MSNoise : NSObject
{
}

+ (void)drawWithIntensity:(double)arg1 ofType:(long long)arg2 inRect:(struct CGRect)arg3 zoomValue:(double)arg4 context:(struct CGContext *)arg5;
+ (void)drawWithIntensity:(double)arg1 ofType:(long long)arg2 inPath:(id)arg3 windingRule:(unsigned long long)arg4 zoomValue:(double)arg5 context:(struct CGContext *)arg6;
+ (BOOL)noiseIsOpaqueForType:(long long)arg1;

@end

