//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface MSOptionalRenderer : NSObject
{
    id _baseRenderer;
    NSString *_disableSetting;
}

+ (void)initialize;
@property(retain, nonatomic) NSString *disableSetting; // @synthesize disableSetting=_disableSetting;
@property(retain, nonatomic) id baseRenderer; // @synthesize baseRenderer=_baseRenderer;
- (void).cxx_destruct;
@property(readonly, nonatomic) BOOL enabled;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (id)initWithBaseRenderer:(id)arg1 disableSetting:(id)arg2;

@end

