//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface MSOverlayItemImageCache : NSObject
{
    double _cachedBackingScale;
    struct CGColorSpace *_cachedColorspace;
    NSDictionary *_cachedImages;
    CDUnknownBlockType _createImageBlock;
}

+ (id)cacheWithCreateImageBlock:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) CDUnknownBlockType createImageBlock; // @synthesize createImageBlock=_createImageBlock;
@property(retain, nonatomic) NSDictionary *cachedImages; // @synthesize cachedImages=_cachedImages;
@property(nonatomic) struct CGColorSpace *cachedColorspace; // @synthesize cachedColorspace=_cachedColorspace;
@property(nonatomic) double cachedBackingScale; // @synthesize cachedBackingScale=_cachedBackingScale;
- (void).cxx_destruct;
- (void)removeAllCachedImages;
- (id)createOverlayItemImagesForColorSpace:(struct CGColorSpace *)arg1 backingScale:(double)arg2;
- (id)overlayItemImages:(struct CGColorSpace *)arg1 backingScale:(double)arg2;
- (void)dealloc;
- (id)init;
- (id)initWithCreateImageBlock:(CDUnknownBlockType)arg1;

@end

