//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchRendering/MSOverlayBitmapItem.h>

@interface MSOverlayLinearBitmapItem : MSOverlayBitmapItem
{
    struct CGPoint _endPoint;
    struct CGVector _startDisplacement;
    struct CGVector _endDisplacement;
}

@property(readonly, nonatomic) struct CGVector endDisplacement; // @synthesize endDisplacement=_endDisplacement;
@property(readonly, nonatomic) struct CGVector startDisplacement; // @synthesize startDisplacement=_startDisplacement;
@property(readonly, nonatomic) struct CGPoint endPoint; // @synthesize endPoint=_endPoint;
@property(readonly, nonatomic) struct CGPoint startPoint;
- (id)initWithImageID:(id)arg1 startPoint:(struct CGPoint)arg2 endPoint:(struct CGPoint)arg3 startDisplacement:(struct CGVector)arg4 endDisplacement:(struct CGVector)arg5;
- (id)initWithImageID:(id)arg1 startPoint:(struct CGPoint)arg2 endPoint:(struct CGPoint)arg3;

@end

