//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchRendering/MSRenderer-Protocol.h>

@class MSImmutableStyle, MSImmutableStyledLayer, MSPath, MSRenderingContext;

@protocol MSPathRenderer <MSRenderer>
- (void)renderBordersForPath:(MSPath *)arg1 style:(MSImmutableStyle *)arg2 applyClip:(BOOL)arg3 rect:(struct CGRect)arg4 context:(MSRenderingContext *)arg5;
- (void)renderFillsForPath:(MSPath *)arg1 style:(MSImmutableStyle *)arg2 layer:(MSImmutableStyledLayer *)arg3 rect:(struct CGRect)arg4 context:(MSRenderingContext *)arg5;
- (void)renderPath:(MSPath *)arg1 style:(MSImmutableStyle *)arg2 layer:(MSImmutableStyledLayer *)arg3 inRect:(struct CGRect)arg4 fallbackColor:(struct CGColor *)arg5 context:(MSRenderingContext *)arg6;
@end

