//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchRendering/MSRenderingDriverCG.h>

@class NSMutableString, NSString;
@protocol MSProfilingRendererDelegate;

@interface MSRenderingDriverCGProfiling : MSRenderingDriverCG
{
    NSMutableString *_traversalLog;
    NSString *_traversalIndent;
    id <MSProfilingRendererDelegate> _delegate;
}

@property(readonly, nonatomic) id <MSProfilingRendererDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSString *traversalIndent; // @synthesize traversalIndent=_traversalIndent;
@property(readonly, nonatomic) NSMutableString *traversalLog; // @synthesize traversalLog=_traversalLog;
- (void).cxx_destruct;
- (id)setupRendererMap;
- (id)initWithDelegate:(id)arg1;

@end

