//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMapTable;

@interface MSRenderingDriver : NSObject
{
    NSMapTable *_renderers;
}

@property(retain, nonatomic) NSMapTable *renderers; // @synthesize renderers=_renderers;
- (void).cxx_destruct;
- (id)contextWithName:(id)arg1 forCGContext:(struct CGContext *)arg2 renderingRequest:(id)arg3;
- (id)rendererForObject:(id)arg1 protocol:(id)arg2;
- (id)setupRendererMap;
- (id)init;

@end

