//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchRendering/MSRenderingDriver.h>

@interface MSRenderingDriverCG : MSRenderingDriver
{
}

- (id)contextWithName:(id)arg1 forCGContext:(struct CGContext *)arg2 renderingRequest:(id)arg3;
- (void)addSimpleRenderersToMap:(id)arg1;
- (id)setupRendererMap;

@end

