//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class BCAtomicStack, MSImmutableDocumentData, NSOperationQueue;

@interface MSRenderPreparer : NSObject
{
    NSOperationQueue *_operationQueue;
    BCAtomicStack *_layerStack;
    MSImmutableDocumentData *_document;
}

@property(retain, nonatomic) MSImmutableDocumentData *document; // @synthesize document=_document;
@property(retain, nonatomic) BCAtomicStack *layerStack; // @synthesize layerStack=_layerStack;
@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
- (void).cxx_destruct;
- (void)prepareDocument:(id)arg1;
- (id)init;

@end

