//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@interface MSSliceTrimming : NSObject
{
}

+ (struct CGRect)simpleSafeRectFromLayerAncestry:(id)arg1;
+ (struct CGRect)safeRectForLayerAncestry:(id)arg1;
+ (id)exportRequestFromLayerAncestry:(id)arg1;
+ (struct CGRect)_trimmedRectFromLayerAncestry:(id)arg1;
+ (BOOL)shouldTrimByDefault:(id)arg1;
+ (struct CGRect)rectForLayerAncestry:(id)arg1 withTrimming:(BOOL)arg2;
+ (struct CGRect)trimmedRectForLayerAncestry:(id)arg1;
+ (void)trimSlice:(id)arg1;

@end

