//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class CALayer, MSRenderInstruction, NSView;
@protocol MSTiledRendererHostView;

@protocol MSTilingSystemProvider
@property(readonly, copy) MSRenderInstruction *renderedInstruction;
@property(nonatomic) __weak NSView<MSTiledRendererHostView> *hostView;
@property(readonly, nonatomic) CALayer *layer;
- (BOOL)isDrawing;
- (void)updateContentWithRenderInstruction:(MSRenderInstruction *)arg1 synchronously:(BOOL)arg2 hasUserFocus:(BOOL)arg3;
- (id)initWithCompletionHandler:(void (^)(struct CGImage *))arg1 syncFirstFrame:(BOOL)arg2;
@end

