//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jun 13 2020 22:17:22).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <SketchRendering/MSExportRequest.h>

@class MSImmutableLayer;
@protocol MSWebExportableRootLayer;

@interface MSWebExportRequest : MSExportRequest
{
    unsigned long long _layerBehavior;
}

+ (id)webExportRequestFromLayerAncestry:(id)arg1 atScale:(double)arg2;
@property(nonatomic) unsigned long long layerBehavior; // @synthesize layerBehavior=_layerBehavior;
- (id)includedLayerIDs;
- (id)includedLayerIDsFromLayer:(id)arg1 ancestors:(id)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;

// Remaining properties
@property(retain, nonatomic) MSImmutableLayer<MSWebExportableRootLayer> *rootLayer; // @dynamic rootLayer;

@end

